import { canAccessJyotishModule } from '@/lib/tierAccess';

export type JyotishTier = 'free' | 'prana' | 'siddha' | 'akasha';

export interface JyotishModule {
  id: number;
  tier: JyotishTier;
  title: string;
  subtitle: string;
  description: string;
  duration: string;
  topics: string[];
  sourceText?: string;
  isSecret?: boolean;
}

export const TIER_CONFIG = {
  free: {
    label: 'Portal I',
    name: 'Ākāsha Free',
    price: 'Free Forever',
    color: '#6B7280',
    slug: 'free',
    moduleRange: [1, 6] as [number, number],
  },
  prana: {
    label: 'Portal II',
    name: 'Prāna-Flow',
    price: '€19 / month',
    color: '#22D3EE',
    slug: 'prana-flow',
    moduleRange: [7, 14] as [number, number],
  },
  siddha: {
    label: 'Portal III',
    name: 'Siddha Quantum',
    price: '€45 / month',
    color: '#D4AF37',
    slug: 'siddha-quantum',
    moduleRange: [15, 22] as [number, number],
  },
  akasha: {
    label: 'Portal IV',
    name: 'Akasha Infinity',
    price: '€1111 Lifetime',
    color: '#ffffff',
    slug: 'akasha-infinity',
    moduleRange: [23, 32] as [number, number],
  },
};

export const TIER_ACCESS: Record<string, JyotishTier[]> = {
  free: ['free'],
  'prana-flow': ['free', 'prana'],
  'siddha-quantum': ['free', 'prana', 'siddha'],
  'akasha-infinity': ['free', 'prana', 'siddha', 'akasha'],
};

export const JYOTISH_MODULES: JyotishModule[] = [
  // ── TIER I: FREE ─────────────────────────────────────────────────────────
  {
    id: 1, tier: 'free',
    title: 'The Eye of the Veda',
    subtitle: 'Origin, Purpose & Sacred Context of Jyotish',
    description: 'Before a student sees a chart, they must understand WHY the Rishis looked at the sky. This module anchors Jyotish not as fortune-telling but as a consciousness technology.',
    duration: '15 min video + PDF',
    sourceText: 'Bṛhat Parāśara Horā Śāstra — Adhyāya 1',
    topics: [
      'What is Vedānga — the 6 limbs of the Veda and Jyotish as the supreme eye',
      'History: Satya Yuga transmissions — Brahma → Nārada → Parāśara → Vedavyāsa',
      'The three skandhas: Siddhānta (astronomy), Saṃhitā (mundane), Horā (natal)',
      'Bhrigu Muni — the Bhrigu Samhitā story and 500,000 horoscopes',
      'Difference from Western tropical astrology (sidereal vs tropical, Ayanāmsa)',
      'The spiritual purpose of a birth chart — karma, dharma, and liberation',
      'Jyotish as a healing science — not fatalism but illumination',
    ],
  },
  {
    id: 2, tier: 'free',
    title: 'Cosmic Architecture: The 9 Grahas',
    subtitle: 'The Divine Actors in Your Life Story',
    description: 'A deep dive into all 9 planetary archetypes — their nature, deity, mantra, and role in your chart.',
    duration: '27 min video + Planet Cards PDF',
    sourceText: 'BPHS Chapters 3–4 · Sārāvalī',
    topics: [
      'Sun (Sūrya) — soul, father, authority, vitality, Pitta nature',
      'Moon (Chandra) — mind, mother, emotions, public life, Vāta/Kapha',
      'Mars (Maṅgala) — energy, courage, brothers, land, surgery',
      'Mercury (Budha) — intellect, communication, trade, skin',
      'Jupiter (Bṛhaspati/Guru) — wisdom, children, dharma, expansion',
      'Venus (Śukra) — beauty, love, wealth, creative arts, relationships',
      'Saturn (Śani) — discipline, karma, service, longevity, delays',
      'Rāhu (North Node) — obsession, illusion, foreign, amplification',
      'Ketu (South Node) — liberation, past life, detachment, spirituality',
      'Natural benefics vs malefics — functional benefics by Lagna',
      'Graha devatās and their seed (beej) mantras — basic introduction',
      'Planets and body parts — foundation for medical Jyotish',
    ],
  },
  {
    id: 3, tier: 'free',
    title: 'The 12 Rashis',
    subtitle: 'Signs as Fields of Karmic Expression',
    description: 'The zodiac signs as energetic fields through which karma is expressed — their elements, modes, and planetary relationships.',
    duration: '30 min video series + Sign Cards PDF',
    sourceText: 'BPHS Chapters 6–7 · Bṛhat Jātaka Chapter 1',
    topics: [
      'Sign elements: Agni (fire), Pṛthvī (earth), Vāyu (air), Jala (water)',
      'Sign modes: Cara (movable), Sthira (fixed), Dvisvabhāva (dual)',
      'Sign lordships — which planet rules which sign',
      'Sign karakatvas — what each sign represents in life areas',
      'Exaltation (Uccha) and debilitation (Nīcha) of planets across signs',
      'Understanding your Moon sign (Rāśi) and Sun sign',
      'Sign as a karmic field — reading your rising sign for life themes',
      'Aries through Pisces — detailed profiles of all 12 signs',
      'Sign compatibility — natural friendship chart for signs',
    ],
  },
  {
    id: 4, tier: 'free',
    title: 'The 12 Bhāvas (Houses)',
    subtitle: 'The Map of Your Life\'s Karma',
    description: 'Houses as the living map of your karmic agreements — understanding the four aims of life and how each house expresses them.',
    duration: '20 min video + House Matrix PDF',
    sourceText: 'BPHS Chapters 11–12 · Phaladeepikā',
    topics: [
      'Four aims of life (Puruṣārthas): Dharma, Artha, Kāma, Moksha — mapped to houses',
      'Kendra houses (1, 4, 7, 10) — the four pillars of existence',
      'Trikona houses (1, 5, 9) — most auspicious, dharmic trinity',
      'Dusthāna houses (6, 8, 12) — challenge, transformation, liberation',
      'Upachaya houses (3, 6, 10, 11) — growing and expanding houses',
      'The Lagna (Ascendant) — the most important single point in the chart',
      'Each house\'s complete karakatvas — 1st through 12th',
      'How lords traveling to different houses create specific life narratives',
      'Simple chart reading — identifying your 1st, 7th & 10th house themes',
    ],
  },
  {
    id: 5, tier: 'free',
    title: '27 Nakshatra Awakening',
    subtitle: 'Lunar Mansions — Your Soul\'s Original Frequency',
    description: 'The 27 lunar mansions as the deepest layer of Vedic astrology — your birth star as the frequency code of your soul.',
    duration: '25 min video + Nakshatra Table PDF',
    sourceText: 'BPHS Chapter 5 · Taittirīya Brāhmaṇa',
    topics: [
      'What is a Nakshatra — the Moon\'s 27 daily mansions in the sky',
      'Your Janma Nakshatra (birth star) — how to find it and what it means',
      'Nakshatra devatā (deity), ruling planet, symbol, and body part',
      'The 27 Nakshatras: complete list from Ashvinī to Revatī with keywords',
      'Navtara Chakra basics — the 9-fold cycle from your birth star',
      'Nakshatra compatibility — Tārā matching for relationships',
      'Nakshatra as the psychological-spiritual signature of the soul',
      'How to identify your current Nakshatra period energy',
      'Nakshatra-specific practices, mantras, and offerings (naivedya)',
    ],
  },
  {
    id: 6, tier: 'free',
    title: 'Reading Your Own Chart: First Light',
    subtitle: 'From Theory to the Living Chart',
    description: 'Your first complete chart reading — putting all foundations together to see your own life blueprint.',
    duration: '20 min screen tutorial + Checklist PDF',
    sourceText: 'Practical synthesis of BPHS foundation chapters',
    topics: [
      'How to cast your chart — Jagannātha Hora (free software) walkthrough',
      'North Indian vs South Indian chart layout — how to read both',
      'Identifying: Lagna, Lagna lord, Moon sign, Sun sign',
      'Basic combinations — what it means when a planet is in a specific house',
      'Reading your dharmic trinity: 1st, 5th, and 9th houses',
      'Understanding your Moon Nakshatra and emotional blueprint',
      'When to seek a professional reading vs continue self-study',
      'Ethical considerations — reading charts for others responsibly',
    ],
  },

  // ── TIER II: PRANA-FLOW ───────────────────────────────────────────────────
  {
    id: 7, tier: 'prana',
    title: 'Planetary Dignity: Strength & Weakness',
    subtitle: 'Shadbala and the Six Pillars of Graha Power',
    description: 'The complete science of planetary strength — learning to assess whether a planet will deliver its results or withhold them.',
    duration: '35 min video + Shadbala Worksheet',
    sourceText: 'BPHS Chapters 27–28 · Sārāvalī on Shadbala',
    topics: [
      'Six dignity states: Uccha, Svagṛha, Mūlatrikoṇa, Mitra, Sama, Shatru, Nīcha',
      'Vargottama — planet in same sign in D1 and D9 (supreme dignity)',
      'Shadbala (6-fold strength): Sthānabala, Digbala, Kālabala, Cheshtabala, Naisargikabala, Drikbala',
      'Planetary Avasthas (5 maturity states): Bāla, Kumāra, Yuva, Vṛddha, Mṛta',
      'Combustion (Astangata) — planets too close to Sun and what they lose',
      'Retrograde planets — introspection, rework, and karmic intensity',
      'Stationary planets — extreme power at station points (direct/retrograde)',
      'Planetary war (Graha Yuddha) — when two planets share the same degree',
      'Practical: ranking planets in a real chart by combined strength',
    ],
  },
  {
    id: 8, tier: 'prana',
    title: 'Bhāva Analysis Mastery',
    subtitle: 'Precision House Reading with Every Tool',
    description: 'Going beyond basic house meanings to true precision — using all classical tools to read any house with confidence.',
    duration: '40 min video + 144 Combinations PDF',
    sourceText: 'BPHS Chapters 24–26 · Phaladeepikā Chapters 4–6',
    topics: [
      'Lord of each house placed in every other house — all 144 combinations',
      'Kāraka and Bhāva Kāraka — when the significator harms its own house',
      'Argalā (planetary intervention) — which planets block or amplify houses',
      'Bhāva Arudha Padas — the public perception layer of each house',
      'Multiple indicators for one life theme — the confirmation principle',
      'Detailed reading: 4th house (mother, home, property, peace of mind)',
      'Detailed reading: 7th house (spouse, partners, public reputation)',
      'Detailed reading: 10th house (career, social standing, mission)',
      'Exceptions and overrides — when rules bend in complex charts',
    ],
  },
  {
    id: 9, tier: 'prana',
    title: 'Aspects & Yogas: Core Combinations',
    subtitle: 'The Grammar of Chart Synthesis',
    description: 'The planetary language of combination — how aspects create conversations and yogas create destiny.',
    duration: '45 min video + Yoga Identification Guide',
    sourceText: 'BPHS Chapters 36–37 · Phala Deepikā on Yogas',
    topics: [
      'Graha drishti — Mars 4th & 8th, Jupiter 5th & 9th, Saturn 3rd & 10th',
      'Rāśi drishti (sign aspects) — Jaimini\'s unique innovation',
      'Rāja Yoga — all main types combining 1/5/9 with 4/7/10 lords',
      'Dhana Yoga — wealth combinations (2nd, 11th, Jupiter, Venus)',
      'Pancha Mahāpurusha Yogas: Ruchaka, Bhadra, Hamsa, Malavya, Śaśa',
      'Viparīta Rāja Yoga — lords of 6/8/12 in each other\'s houses',
      'Moon-based yogas: Sunapha, Anapha, Durudharā, Kemadruma',
      'Kesari Yoga, Gaja Kesari — correct interpretation vs common error',
      'Daridra Yoga and poverty combinations — identifying challenge patterns',
      'Auspicious aggregate yogas: Sankha, Bheri, Mridanga',
    ],
  },
  {
    id: 10, tier: 'prana',
    title: 'Vimshottari Dasha: The Master Clock',
    subtitle: '120-Year Planetary Timing System',
    description: 'The supreme timing system of Vedic astrology — learning to navigate the 120-year karmic river of your life.',
    duration: '50 min video + Personal Timeline Worksheet',
    sourceText: 'BPHS Chapter 46 · Uttara Kālamṛta',
    topics: [
      'The 9-planet sequence: Sun 6, Moon 10, Mars 7, Rāhu 18, Jupiter 16, Saturn 19, Mercury 17, Ketu 7, Venus 20',
      'Calculating starting point from birth Nakshatra and its balance',
      'Mahādasha, Antardasha, Pratyantardasha, Sūkshmadasha levels',
      'Psychology of each Mahādasha — what each 7–20 year period feels like',
      'Rāhu Mahādasha — 18 years of illusion, obsession, and breakthrough',
      'Saturn Mahādasha — 19 years of karma settlement and discipline',
      'Ketu Mahādasha — 7 years of release, liberation, and past-life resolution',
      'Activating dormant yogas through favorable dasha sequences',
      'Case studies: marriage, career change, illness, spiritual awakening events',
    ],
  },
  {
    id: 11, tier: 'prana',
    title: 'Transit Science (Gochar)',
    subtitle: 'Current Planetary Weather & Your Karmic Window',
    description: 'How current planetary movements activate your natal chart — the living astrology happening right now in your life.',
    duration: '35 min video + 3-Month Forecast Template',
    sourceText: 'BPHS Chapter 49 · Brihat Samhita on Gochar',
    topics: [
      'How transits interact with natal chart — not a blank slate but an activation',
      'Saturn\'s Sade Sati — the 7.5-year trial (before, during, after Moon sign)',
      'Jupiter\'s annual transit — which house it illuminates and expands',
      'Rāhu-Ketu 18-month axis shift — collective and personal karmic themes',
      'Mars transit — 45-day activations (energy, conflict, drive windows)',
      'Ashtakavarga in transit — scoring bindu strength for each transit',
      'Navtara (Tārā) in transit — auspicious vs inauspicious Nakshatras from birth star',
      'Transit over dasha lord — the most critical trigger moments',
      'Eclipse effects on natal chart — 6-month shadow period',
    ],
  },
  {
    id: 12, tier: 'prana',
    title: '27 Nakshatras: Complete System',
    subtitle: 'Full Nakshatra Predictive Science',
    description: 'The complete 27-star system in full depth — from personality profiling to prediction, compatibility, and remedies.',
    duration: '60 min video series + Complete Nakshatra Reference',
    sourceText: 'Taittirīya Brāhmaṇa · Nakshatra Chandrikā · BPHS Chapter 5',
    topics: [
      'All 27 Nakshatras — full profiles: deity, planet, symbol, guna, caste, body part',
      'Psychological expression, spiritual quality, and shadow expression of each star',
      'Nakshatra Padas — 108 divisions with Navamsha sign lords',
      'Nakshatra in each of the 12 houses — how the star flavors house themes',
      'Navtara Chakra complete 9-fold classification from Janma star',
      'Nakshatra-to-Nakshatra compatibility: full Tārā matching system',
      'Nakshatra remedies — specific mantra, flower, gemstone, color for all 27',
      'Advanced: Nakshatra placement in Navamsha (D9) and Daśāṃśa (D10)',
      'Nakshatra as the foundation of Nadi astrology — the bridge to Tier IV',
    ],
  },
  {
    id: 13, tier: 'prana',
    title: 'Pañcāṅga: Sacred Calendar Science',
    subtitle: 'The Five Limbs of Living in Cosmic Rhythm',
    description: 'How to read the living cosmic clock — the five-limbed system for choosing the right moment for every action.',
    duration: '30 min video + Daily Pañcāṅga Practice Guide',
    sourceText: 'Muhūrta Cintāmaṇi · Bṛhat Saṃhitā · Rāmānuja Prasna Mārga',
    topics: [
      'Tithi (lunar day) — 30 tithis, their deities, energy qualities, and auspicious activities',
      'Vāra (weekday) — planetary lord, sacred activities, fasting protocols',
      'Nakshatra of the day — how it affects mood, decisions, and actions',
      'Yoga (27 Sun-Moon combinations) — from Vishkambha through Vaidhṛti',
      'Karaṇa (11 half-tithis) — for short-duration actions and commerce',
      'How to read a Pañcāṅga almanac in daily practice',
      'Pañcāṅga Śuddhi — the 5-fold purity check for Muhurta selection',
      'Living by Pañcāṅga as a daily spiritual and practical alignment tool',
      'Rāhu Kāla, Yamagaṇḍa, Gulika — the three daily inauspicious periods',
    ],
  },
  {
    id: 14, tier: 'prana',
    title: 'Navamsha (D9): The Soul Chart',
    subtitle: 'The Inner Blueprint — Reading the 9th Divisional',
    description: 'The most important divisional chart — the soul\'s true nature, spiritual path, and the blueprint for the second half of life.',
    duration: '40 min video + D1/D9 Combined Reading Template',
    sourceText: 'BPHS Chapter 6 on Shodashavargas · Jaimini on Navamsha',
    topics: [
      'What the Navamsha represents — inner soul, spiritual path, life after 36',
      'How to construct and read the Navamsha chart correctly',
      'Vargottama planets — the highest dignity when D1 and D9 signs match',
      'Navamsha Lagna and its ruling planet — the soul\'s deepest nature',
      'D9 for marriage — reading the quality and nature of the spouse principle',
      'Pushkara Navamsha — the 5 most auspicious degree positions in any chart',
      'D9 as confirmation tool — does D1 yoga manifest or dissolve in D9?',
      'Reading D9 for spiritual life, guru connection, and pilgrimage',
      'Combining D1 + D9 + D10 for career-soul alignment predictions',
    ],
  },

  // ── TIER III: SIDDHA QUANTUM ──────────────────────────────────────────────
  {
    id: 15, tier: 'siddha',
    title: 'All 16 Divisional Charts (Varga)',
    subtitle: 'The 16 Lenses of Karmic Life Areas',
    description: 'The complete Shodasha Varga system — 16 charts that reveal the full karmic blueprint of every area of life.',
    duration: '90 min video series + Varga Reference Guide',
    sourceText: 'BPHS Chapter 6 · Jaimini Sutras on Vargas · Brihat Jataka',
    topics: [
      'D-1 Rāśi (overall life) · D-2 Horā (wealth potential)',
      'D-3 Drekkāṇa 3 types: Parāśara, Jaimini, Somanātha (siblings, courage)',
      'D-4 Chaturthamsha (property, fixed assets) · D-5 Pañchamsha (past-life merit)',
      'D-6 Ṣaṣṭhāṃśa (enemies, disease) · D-7 Saptamsha (children)',
      'D-9 Navamsha (soul, dharma) · D-10 Daśāṃśa (career, social impact)',
      'D-12 Dvādaśāṃśa (parents, ancestral karma) · D-16 Ṣoḍaśāṃśa (vehicles, comforts)',
      'D-20 Viṃśāṃśa (spiritual practice, upāsanā) · D-24 Siddhamsha (education)',
      'D-27 Nakṣatrāṃśa (physical strength) · D-30 Triṃśāṃśa (karmic debts)',
      'D-60 Ṣaṣṭyaṃśa — deepest past-life karma (requires accurate birth time to the minute)',
    ],
  },
  {
    id: 16, tier: 'siddha',
    title: 'Ashtakavarga System',
    subtitle: 'The 8-Source Strength Grid for Transits & Houses',
    description: 'The most sophisticated planetary scoring system — assigning bindu points to precisely measure house strength and transit power.',
    duration: '50 min video + Ashtakavarga Calculation Workbook',
    sourceText: 'BPHS Chapters 66–70 · Ashtakavarga Mahānibandha',
    topics: [
      'What is Ashtakavarga — 8 sources of bindus (benefic points) for each planet',
      'Bhinna (individual) Ashtakavarga — separate grid for all 8 planets',
      'Sarva (combined) Ashtakavarga — total house strength, maximum 337 points',
      'Trikona Śodhana — triangular reduction of raw bindus',
      'Ekadhipatya Śodhana — equal lordship reduction',
      'Using Sarva Ashtakavarga to rank the 12 houses by strength',
      'Transit predictions: bindu count in each sign for each transiting planet',
      'Longevity assessment via Pindāyu (Ashtakavarga lifespan method)',
      'Kakṣyā system — sub-lord scoring within each sign',
      'Practical 12-month transit forecast using the Bindu table',
    ],
  },
  {
    id: 17, tier: 'siddha',
    title: 'Special Dasha Systems',
    subtitle: 'Three Master Clocks Beyond Vimshottari',
    description: 'When Vimshottari is not enough — three advanced timing systems that unlock events the standard system misses.',
    duration: '75 min video series + Triple Dasha Cross-Reference Guide',
    sourceText: 'BPHS Chapters 46–53 · Kālachakra Tantra · Jaimini Sutras',
    topics: [
      'Yogini Dasha (36-year cycle) — 8 Yoginis: Mangalā, Piṅgalā, Dhanyā, Bhrāmarī, Bhadrikā, Ulkā, Siddhā, Mahāmārī',
      'Yogini cross-reference with Vimshottari for event confirmation',
      'Kālachakra Dasha — the most complex system, based on Navamsha Pada position',
      'Savya (forward) vs Apasavya (reverse) Kālachakra rotation rules',
      'Kālachakra for longevity assessment — Deha and Jeeva Rashis',
      'Chara Dasha (Jaimini) — sign-based dasha unlike any planet-based system',
      'Special rules for short-lived vs long-lived charts in Chara Dasha',
      'Rāja Yogas activating through specific sign periods in Chara Dasha',
      'Narayana Dasha — for material events, property, and status changes',
      'Triple-dasha cross-referencing methodology on historical charts',
    ],
  },
  {
    id: 18, tier: 'siddha',
    title: 'Jaimini Jyotish System',
    subtitle: 'The Second Eye — Soul-Level Vedic Astrology',
    description: 'Maharishi Jaimini\'s complete system — a parallel universe of astrology focused on the soul\'s journey and karmic appointments.',
    duration: '80 min video series + Jaimini Chart Overlay Guide',
    sourceText: 'Jaimini Upadeśa Sūtras (all 4 Adhyāyas) · Neelakantta Commentary',
    topics: [
      'Chara Kārakas — 8 soul significators based on degree position in chart',
      'Ātmakāraka (AK) — the soul planet, the most important in Jaimini',
      'Amātyakāraka, Bhrātṛkāraka, Mātṛkāraka, Putrakāraka, Jñātikāraka, Dārakāraka',
      'Karakāṃśa — Ātmakāraka in Navamsha: the soul\'s true purpose revealed',
      'Ārūḍha Padas — the world of appearances vs the world of reality',
      'Ārūḍha Lagna (AL) — how the world perceives you (vs your true Lagna self)',
      'All 12 Bhāva Ārūḍhas (A2 through A12) — appearance of each life area',
      'Upapada Lagna (UL) — the TRUE relationship and marriage quality indicator',
      'Rāśi drishti vs Graha drishti — how Jaimini aspects differ from Parāśara',
      'Navamsha of Ātmakāraka — reading the soul\'s spiritual path and dharma',
    ],
  },
  {
    id: 19, tier: 'siddha',
    title: 'Prashna Jyotish: Horary Astrology',
    subtitle: 'Answering Any Question Without a Birth Chart',
    description: 'The art of answering life\'s questions from the chart of the asking moment — one of the most powerful and immediate tools in Jyotish.',
    duration: '60 min video + 5 Real Prashna Case Studies',
    sourceText: 'Prashna Mārga (full text) · Krishnamurti Paddhati · Śaṭpañcāśikā',
    topics: [
      'The metaphysics of Prashna — why the moment of asking contains the answer',
      'Prashna Lagna strength assessment — the 26 classical factors (Prashna Mārga)',
      'Kashyap Hora — number-based system (1–12 or 1–249) for instant answers',
      'Career Prashna: Will I get the job? Will the business succeed?',
      'Finance Prashna: Will the investment return? Is this transaction safe?',
      'Health Prashna: What is the nature of the illness? Will it resolve?',
      'Relationship Prashna: Will this lead to marriage? Is the partner faithful?',
      'Lost items and missing persons — the Prashna method',
      'Prashna for spiritual guidance — accessing divine direction',
      'Ethics of Prashna — questions that should not be answered and why',
    ],
  },
  {
    id: 20, tier: 'siddha',
    title: 'Muhurta: Electional Mastery',
    subtitle: 'Choosing the Perfect Moment for Every Action',
    description: 'The science of auspicious timing — how to select the right cosmic moment to begin any significant action in life.',
    duration: '55 min video + Muhurta Checklist System',
    sourceText: 'Muhūrta Cintāmaṇi · Muhurta Martanda · Classical Muhurta by Ernst Wilhelm',
    topics: [
      'Why Muhurta matters — how starting in an aligned moment changes outcomes',
      'Three core requirements: Chandra Bala, Tārā Bala, Pañcāṅga Śuddhi',
      'Muhurta for marriage — the complete wedding chart analysis',
      'Muhurta for business launch — 10th house, Mercury, Jupiter requirements',
      'Muhurta for surgery — avoiding Mars 8th, Saturn 8th, inauspicious tithis',
      'Muhurta for travel, learning (Vidyārambha), property purchase',
      'Abhijit Muhurta — the universal shortcut (midday window, always available)',
      'Rāhu Kāla, Yamagaṇḍa, Gulika — calculating and avoiding daily inauspicious periods',
      'Shodasha Samskāra (16 life rites) — optimal Muhurta for each sacred ceremony',
      'Tarabala + Chandrabala + Pañchashuddhi combined master checklist',
    ],
  },
  {
    id: 21, tier: 'siddha',
    title: 'Medical Jyotish',
    subtitle: 'Body, Disease & Healing Through the Vedic Chart',
    description: 'The complete system for reading health, vitality, longevity, and the body\'s karmic vulnerabilities from the birth chart.',
    duration: '65 min video + Medical Jyotish Reference Map',
    sourceText: 'BPHS on Medical Astrology · Sarvartha Chintamani · Ayurvedic-Jyotish integration',
    topics: [
      'Each planet\'s body parts and organ systems — complete anatomical map',
      'Each house\'s anatomical territory (1st = head through 12th = feet)',
      'Sign-body connections: Aries = head, Taurus = neck through Pisces = feet',
      'Identifying disease periods through dasha and transit activation',
      'Dusthāna analysis — 6th (disease), 8th (chronic), 12th (hospitalization)',
      'Gulika, Mandi, Upagrahas — shadow points indicating health karma',
      'Longevity assessment: Āyurdhāya, Pindāyu, Nishargāyu methods',
      'Bādhaka planet — the karmic obstructor, house, and its mitigation',
      'Maraka planets — indicators of vulnerability during critical transit periods',
      'Ayurvedic dosha correlation: Lagna, Moon, and Nakshatra → Vāta/Pitta/Kapha',
      'Graha-specific healing: gems, mantras, diet, herbs for each planet',
    ],
  },
  {
    id: 22, tier: 'siddha',
    title: 'Relationships & Compatibility',
    subtitle: 'Full Vedic Synastry — Complete Compatibility Science',
    description: 'The complete system for assessing relationship compatibility — from traditional Ashtakoot to advanced Jaimini synastry.',
    duration: '60 min video + Full Compatibility Analysis Template',
    sourceText: 'BPHS on Compatibility · Jaimini Sutras · Prashna Mārga on Relationships',
    topics: [
      'Ashtakoot (8-fold) system — Varṇa (1), Vashya (2), Tārā (3), Yoni (4), Grahemaitri (5), Gaṇa (6), Bhakūṭa (7), Nāḍi (8) = max 36 pts',
      'Why Ashtakoot alone is insufficient — the deeper compatibility layers',
      '7th house lords in both charts — synastry of the partnership principle',
      'Venus (female chart) and Mars (male chart) synastry overlay',
      'Moon-Moon relationship — emotional compatibility and mental harmony',
      'Upapada Lagna (Jaimini) — the ultimate marriage quality indicator',
      'Navamsha (D9) synastry — comparing D9 charts for soul compatibility',
      'Timing marriage: dasha + transit + Muhurta trinity confirmation',
      'Multiple marriages, late marriage, and denied marriage yogas',
      'Business partnership compatibility (7th and 10th house synastry)',
    ],
  },

  // ── TIER IV: AKASHA INFINITY ──────────────────────────────────────────────
  {
    id: 23, tier: 'akasha',
    title: 'Bhrigu Nandi Nadi System (BNN)',
    subtitle: '5000-Year-Old Predictive Palm-Leaf Science',
    description: 'The most powerful predictive system in existence — Bhrigu\'s own grammar of planetary conjunctions and progressions, transmitted directly.',
    duration: '120 min video series + 108 Planetary Combinations Reference',
    sourceText: 'R.G. Rao BNN Research · Vinayak Bhatt BNN System · Original Bhrigu-Nandi lineage',
    isSecret: true,
    topics: [
      'BNN Core Grammar — conjunction as event language (not house lordship)',
      'Same-sign conjunction (A+B), adjacent sign relation, 6/8 and 3/11 relationships',
      'Sign exchange (mutual reception) as a powerful BNN activation',
      'Planetary significations in BNN — where they differ from Parāśara',
      'Jupiter progression — 12-year journey through signs as life chapters',
      'Saturn progression — 30-year cycle of karma and maturation',
      'Transit activation: slow planets (Jupiter, Saturn, Rāhu/Ketu) trigger events',
      'Fast planet transits as sub-event precision triggers',
      '108 core planetary combinations and their specific predicted events',
      'CCTV Technique — reading planets in degree sequence like a camera scan',
      'M-Technique — precise marriage timing method',
      'D-Technique — disease, difficulty, and accident prediction',
      'Retrograde planets in BNN — completely different interpretation',
      'BNN for Prashna — applying conjunction grammar to horary questions',
    ],
  },
  {
    id: 24, tier: 'akasha',
    title: 'Nadi Secrets: The 18 Siddhar Transmissions',
    subtitle: 'Secret Science of the Tamil Siddhars\' Palm Leaf Oracle',
    description: 'The unwritten Nadi traditions of the 18 Tamil Siddhars — each lineage holding unique keys to the Akashic record of souls.',
    duration: '90 min video series + Siddhar Lineage Map',
    sourceText: '18 Tamil Siddhar traditions · Agastya Nadi · Saptarishi Nadi · Maha Shiva Ajeeva Nadi',
    isSecret: true,
    topics: [
      'Agastya Nadi — root of all Nadi astrology, the primordial transmission',
      'Bogar Nadi — alchemical and medical Jyotish, the 18-Siddha lineage head',
      'Machamuni Nadi — aquatic and emotional karma patterns',
      'Nandhidevar Nadi — liberation path and Shiva consciousness map',
      'Thirumoolar Nadi — tantric patterns and Kundalini Shakti in the chart',
      'Koṅgaṇar, Korakkar, Sattaimuni, Sundaranar — travel, longevity, speech Nadis',
      'Narada Nadi (devotion, music, relationships), Ramadevar Nadi (breath science)',
      'Physical palm leaf repositories — Vaitheswaran Koil, Adyar Library, Saraswati Mahal',
      'The 16 Kāṇḍas of Ajeeva Nadi — 1st through 12th house chapters + 4 special chapters',
      'Thumb impression method — how the correct palm leaf finds its owner',
      'Siddha Pariharam Thulavaranam — sacred weight-based remedy unique to Siddhar tradition',
      'Accessing the Nadi field through meditation — not just physical palm leaves',
      'Nadi as Akashic Record technology — how Siddhars encoded future timelines',
    ],
  },
  {
    id: 25, tier: 'akasha',
    title: 'Bhrigu Samhitā Technique',
    subtitle: 'The Original 500,000-Horoscope Database of Maharishi Bhrigu',
    description: 'Bhrigu\'s own predictive method — the Jupiter progression system and the secret Bhrigu Bindu point that acts as a personal oracle.',
    duration: '75 min video + Bhrigu Bindu Calculator',
    sourceText: 'Bhrigu Samhitā manuscripts · R.G. Rao system · Hoshiarpur lineage',
    isSecret: true,
    topics: [
      'The Bhrigu Samhitā history — how 500,000 charts were compiled in Satya Yuga',
      'Repository locations: Hoshiarpur (Punjab), Varanasi, Gujarat, Nepal',
      'How a traditional Bhrigu Samhitā reading works in practice today',
      'Jupiter as the primary timing engine in the Bhrigu system',
      'Jupiter\'s natal house position as the primary life theme indicator',
      'Jupiter\'s transit activation of natal houses — year-by-year life chapters',
      'Bhrigu Bindu — the most sensitive degree in any chart (midpoint of Rāhu and Moon)',
      'Any planet transiting Bhrigu Bindu triggers the most significant life events',
      'Bhrigu Bindu as a personal oracle point — calculating and tracking yours',
      'Bhrigu Sutras — key aphorisms for predicting specific events',
      'Current life chapter identification through Bhrigu Jupiter progression',
      'Integrating Bhrigu with BNN and Parāśara for triple confirmation',
    ],
  },
  {
    id: 26, tier: 'akasha',
    title: 'Kālachakra Dasha: Quantum Timing',
    subtitle: 'The Most Secret Advanced Dasha System — Time as Spiral',
    description: 'The rarest and most powerful timing system in Jyotish — preserved in tantric lineages and rarely taught publicly.',
    duration: '80 min video + Kālachakra Calculation Manual',
    sourceText: 'Kālachakra Tantra · BPHS Chapter 48 · Tantric Jyotish lineages',
    isSecret: true,
    topics: [
      'Kālachakra meaning — "wheel of time," the most ancient dasha system',
      'The Nakshatra Pada as starting point — which specific quarter of birth star',
      'Savya (clockwise) vs Apasavya (counter-clockwise) rotation — how determined',
      'The 9 signs in each direction with their specific year allocations',
      'How Kālachakra Dasha periods differ fundamentally from Vimshottari logic',
      'Using Kālachakra for longevity (Āyu) calculation — the death timing method',
      'Extreme event forecasting — events missed by Vimshottari appear here',
      'The Mṛtyu (death/crisis) chakra within the Kālachakra framework',
      'Deha Rashi (body sign) and Jeeva Rashi (life sign) — their significance',
      'Relationship between Kālachakra and quantum cyclical consciousness models',
      'Cross-confirming: events must appear in Vimshottari + Kālachakra + transit',
    ],
  },
  {
    id: 27, tier: 'akasha',
    title: 'Mundane Jyotish',
    subtitle: 'Nations, Leaders, Collective Karma & Civilizational Cycles',
    description: 'Scaling Jyotish from the individual soul to nations, epochs, and civilizational movements — the astrology of collective consciousness.',
    duration: '70 min video + World Chart Analysis Guide',
    sourceText: 'Brihat Samhita (Varahamihira) · Tajika Nīlakanthi · Jupiter-Saturn cycle research',
    topics: [
      'National horoscopes — how to read a country\'s birth chart',
      'Independence charts: India (15 Aug 1947), USA, major nations comparison',
      'Solar Ingress charts — cast for Sun entering Aries (annual world forecast)',
      'Eclipse charts and their 6-month shadow effect on collective events',
      'Jupiter-Saturn conjunctions — 20-year civilizational epoch markers',
      'The 2020 Capricorn conjunction (the Great Reset) and its full unfolding',
      'Historical conjunction sequence — Air, Fire, Earth, Water element ages',
      'Rāhu-Ketu axis transits and their collective karmic shadow themes',
      'Mundane house rulerships (distinct from natal house meanings)',
      'Reading for social movements, economic shifts, pandemics, and natural events',
      'Vedic economic astrology — commodity cycles, currency, market timing windows',
    ],
  },
  {
    id: 28, tier: 'akasha',
    title: 'Svara Śāstra: Breath Astrology',
    subtitle: 'The Most Secret Siddha Oracle — The Breath Itself as the Answer',
    description: 'The deepest secret of all Siddha sciences — predicting events and answering questions through the breath alone, without any chart.',
    duration: '60 min video + 7-Day Svara Observation Journal',
    sourceText: 'Śiva Svarodaya (Lord Shiva\'s transmission to Pārvatī) · Svara Yoga texts',
    isSecret: true,
    topics: [
      'The three Svara Nāḍīs: Iḍā (left/Moon/cool), Piṅgalā (right/Sun/hot), Suṣumnā (neutral/sacred)',
      'The five Tatvas (elements) in the breath cycle and their duration counts',
      'Pṛthvī (earth, 20 counts) · Jala (water, 16) · Agni (fire, 12) · Vāyu (air, 8) · Ākāśa (space, 4)',
      'How to detect which Tatva is active in your breath right now',
      'Predicting success or failure of actions from active Svara + Tatva combination',
      'Svara for answering questions (Prashna through breath) — no chart needed',
      'Svara and Nakshatra — which lunar mansion enhances which nostril',
      'Daily Svara practice — optimizing breath for cosmic life alignment',
      'Advanced: detecting emotional, physical, and spiritual states through breath',
      'Svara and mantra — which mantras to chant in which nostril dominance',
      'Svara in meditation — using breath as the most precise cosmic GPS',
    ],
  },
  {
    id: 29, tier: 'akasha',
    title: 'Jyotish & Mantra Vidya',
    subtitle: 'Planetary Seed Mantras — The Sonic Alchemy of Graha Pacification',
    description: 'The complete science of planetary mantras — from seed syllables to full Vedic hymns, and how to build a personal Graha sādhana.',
    duration: '75 min video + Complete Mantra Protocol PDF + Audio Tracks',
    sourceText: 'Navagraha Stotra · Vedic mantra traditions · Rig Veda planetary hymns',
    topics: [
      'Beej (seed) mantras for all 9 Grahas — complete text, syllable count, pronunciation',
      'Sun: Aum Hrāṃ Hrīṃ Hrauṃ Saḥ Sūryāya Namaḥ (7,000 count)',
      'Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rāhu, Ketu — full prescriptions',
      'Navagraha Stotra — complete collective hymn to all nine planets',
      'Graha Shānti pūjā protocol — complete ceremony structure',
      'Mantra timing: best Nakshatra, Tithi, and Vāra for each planet\'s japa',
      'Mālā (bead) selection — rudraksha, crystal, coral, emerald — which for which',
      'Yantra construction — geometric consciousness maps for each Graha',
      'Kavacha (armor mantra) — planetary protection fields for self and others',
      'Āditya Hṛdayam (Sun), Śiva Mahimna Stotra (Saturn) — complete texts',
      'Sound frequency correlations — SQI bioenergetic library integration',
      'Building a personal 40-day Graha sādhana protocol from your chart',
    ],
  },
  {
    id: 30, tier: 'akasha',
    title: 'Siddha Parihāram: Advanced Remedial Science',
    subtitle: 'Remedies from the Tamil Siddhar Tradition — Beyond Mainstream Jyotish',
    description: 'The most powerful remedial system in existence — Siddhar technology for pacifying karmic planetary patterns at their root.',
    duration: '80 min video + Complete Remedy Protocol System',
    sourceText: '18 Siddhar parihara traditions · Agastya Nadi remedies · Tantric Jyotish remedies',
    isSecret: true,
    topics: [
      'Gemstone (Ratna) prescription — primary stone, supporting stone, quality, weight, metal, finger',
      'Stone combinations to avoid — dangerous pairings and their effects',
      'Yantra construction and consecration (prāṇa pratiṣṭhā) for each planet',
      'Siddha herbs (aushadhi) for each planet — complete materia medica',
      'Color therapy per chart — clothing, room, light codes from birth chart',
      'Dietary adjustments per Graha weakness — specific foods to eat and avoid',
      'Dāna (charity) protocol — what to donate, to whom, on which day',
      'Saturn: oil, sesame, black cloth, service to elderly on Saturdays',
      'Complete dāna table for all 9 Grahas with timing and recipient specifications',
      'Thulāvaraṇam — the sacred Siddhar weight-based remedy (unique to Tamil tradition)',
      'Agni Karma — Navagraha homa (9-planet fire ceremony) complete protocol',
      'Śrī Yantra installation and activation for overall life upliftment',
      'Siddha Pariharam through music — specific rāgas for planetary remedy',
    ],
  },
  {
    id: 31, tier: 'akasha',
    title: 'Spirituality, Moksha & the Chart of Liberation',
    subtitle: 'Reading the Soul\'s Journey Toward Liberation',
    description: 'The highest dimension of Jyotish — reading the chart for liberation potential, spiritual path, and the soul\'s final destination.',
    duration: '70 min video + Siddha Master Chart Study Series',
    sourceText: 'BPHS on Moksha · Jaimini on Karakamsha · Upanishadic Jyotish traditions',
    topics: [
      'Moksha indicators: 12th lord strength, Ketu placement, Jupiter in 12th',
      'Viparīta Rāja Yoga involving the 12th — the saint pattern',
      'Ātmakāraka (Jaimini) — the soul planet and its deepest spiritual purpose',
      'Karakāṃśa in 12th house — the renunciate, mystic, or Siddha indicator',
      'Dharma-Moksha axis — 9th and 12th house relationship and harmony',
      'Jñāna Yoga signatures — Mercury, 5th, Ketu, 4th as knowledge path',
      'Bhakti Yoga signatures — Venus, Moon, 5th, Jupiter as devotion path',
      'Karma Yoga path — Saturn, 10th house, 6th house, service orientation',
      'Reading charts of Siddha masters: Ramana Maharshi, Ramakrishna Paramahamsa',
      'Swami Vivekananda, Ānandamayī Mā, Neem Karoli Baba — chart analysis',
      'Timing of spiritual awakening — which dasha, which transit opens the door',
      'Past-life indicators through D-60, 12th house, and Ketu sign/nakshatra',
    ],
  },
  {
    id: 32, tier: 'akasha',
    title: 'Chart Reading at Siddha Level',
    subtitle: 'Full Integration — Reading Charts as Bhrigu Would',
    description: 'The capstone transmission — the complete 10-step methodology for reading any chart at the level of a Siddha Jyotishi.',
    duration: '90 min masterclass + Capstone Chart Reading Submission',
    sourceText: 'Synthesis of all preceding modules — Bhrigu consciousness transmission',
    isSecret: true,
    topics: [
      'The hierarchy of indicators — how to weigh conflicting chart signals',
      'The rule of 3 confirmations — never predict from a single indicator',
      'Step 1: Assess Lagna and Lagna lord strength (the chart\'s foundation)',
      'Step 2: Assess Moon — mental health, emotional blueprint, public reception',
      'Step 3: Find the most powerful planet by Shadbala + dignity',
      'Step 4: Identify strongest Rāja, Dhana, Viparīta, and Mahāpurusha yogas',
      'Step 5: Read D9 for soul-level confirmation of D1 patterns',
      'Step 6: Read D10 for career, purpose, and social contribution direction',
      'Step 7: Apply Vimshottari dasha timeline to current life chapter',
      'Step 8: Cross-check with BNN progression and Bhrigu Bindu activation',
      'Step 9: Transit confirmation — current planetary weather on the natal map',
      'Step 10: Prescribe remedies — complete Siddha parihara protocol',
      'Predicting specific events with confidence: time window, type, duration',
      'Ethics, consciousness, and the responsibility of a Jyotishi',
      'Capstone: recorded 60-min chart reading submitted to SQI Akashic Codex',
    ],
  },
];

export const getModulesByTier = (tier: JyotishTier): JyotishModule[] =>
  JYOTISH_MODULES.filter(m => m.tier === tier);

export const getModuleById = (id: number): JyotishModule | undefined =>
  JYOTISH_MODULES.find(m => m.id === id);

/** Aligns with app tier gates (guest preview 1–3, admin, membership slugs). */
export function canAccessModule(
  module: JyotishModule,
  membershipSlug: string | null | undefined,
  opts?: { isAdmin?: boolean; userId?: string | undefined },
): boolean {
  return canAccessJyotishModule({
    isAdmin: opts?.isAdmin ?? false,
    userId: opts?.userId,
    tier: membershipSlug ?? null,
    moduleId: module.id,
  });
}
