project_id = "ssygukfdbtehvtndandn"

[functions.shc-transfer]
verify_jwt = false

[functions.purchase-music]
verify_jwt = false

[functions.create-healing-checkout]
verify_jwt = false

[functions.purchase-healing-audio]
verify_jwt = false

[functions.enroll-course]
verify_jwt = false
