#!/usr/bin/env python3
"""
Regenerates src/data/ekadashiTithiTable.ts — the precise UTC tithi-boundary
table that powers the Ekadashi Oracle card (src/lib/ekadashiEngine.ts).

Tithi = 12° step in Moon–Sun geocentric ecliptic longitude. This script scans
time in 2-hour steps and bisects each 12°-multiple crossing down to ~20s
precision, using pymeeus (ELP2000-82 Moon / VSOP87 Sun — arcsecond-class
accuracy). Verified against Drik Panchang for Jul 2026 Yogini Ekadashi to
within ~2 minutes.

Run this whenever the table needs extending past its current end date
(currently through end of 2028):

    pip install pymeeus --break-system-packages
    python3 scripts/generate-ekadashi-table.py

It overwrites src/data/ekadashiTithiTable.ts directly. Sunrise/Arunodaya
logic (location-dependent) lives separately in ekadashiEngine.ts and needs
no changes when this table is regenerated.
"""
import os
from datetime import datetime, timedelta, timezone
from pymeeus.Sun import Sun
from pymeeus.Moon import Moon
from pymeeus.Epoch import Epoch

START = datetime(2026, 1, 1, tzinfo=timezone.utc)
END = datetime(2029, 1, 1, tzinfo=timezone.utc)  # bump this forward to extend
STEP = timedelta(hours=2)

OUT_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'ekadashiTithiTable.ts')


def elong_deg(dt_utc: datetime) -> float:
    e = Epoch(dt_utc.year, dt_utc.month, dt_utc.day,
              dt_utc.hour + dt_utc.minute / 60 + dt_utc.second / 3600)
    sun_lon = float(Sun.apparent_geocentric_position(e)[0])
    moon_lon = float(Moon.apparent_ecliptical_pos(e)[0])
    return (moon_lon - sun_lon) % 360.0


def tithi_index(elong: float) -> int:
    # 1..30 ; 1-15 Shukla paksha, 16-30 Krishna paksha
    return int(elong // 12) + 1


def find_boundaries():
    boundaries = []
    t = START
    prev_t = t
    prev_idx = tithi_index(elong_deg(t))
    t += STEP
    while t <= END:
        idx = tithi_index(elong_deg(t))
        if idx != prev_idx:
            lo, hi, lo_idx = prev_t, t, prev_idx
            for _ in range(30):
                mid = lo + (hi - lo) / 2
                mid_idx = tithi_index(elong_deg(mid))
                if mid_idx == lo_idx:
                    lo = mid
                else:
                    hi = mid
                if (hi - lo) < timedelta(seconds=20):
                    break
            boundaries.append((hi.isoformat(), idx))
        prev_t, prev_idx = t, idx
        t += STEP
    return boundaries


def build_ekadashi_periods(boundaries):
    segments = []
    for i in range(len(boundaries) - 1):
        start_iso, idx = boundaries[i]
        end_iso, _ = boundaries[i + 1]
        segments.append({"tithi": idx, "start": start_iso, "end": end_iso})

    periods = []
    for i, seg in enumerate(segments):
        if seg["tithi"] in (11, 26):  # Ekadashi in either paksha
            paksha = "Shukla" if seg["tithi"] == 11 else "Krishna"
            dwadashi_end = segments[i + 1]["end"] if i + 1 < len(segments) else None
            periods.append({
                "paksha": paksha,
                "tithiStartUtc": seg["start"],
                "tithiEndUtc": seg["end"],
                "dwadashiEndUtc": dwadashi_end,
            })
    return periods


def write_ts(periods):
    lines = [
        '// Auto-generated by scripts/generate-ekadashi-table.py — precise geocentric tithi boundaries',
        '// computed with pymeeus (ELP2000-82 Moon / VSOP87 Sun, apparent geocentric longitude).',
        '// Cross-checked against Drik Panchang for Jul 2026 Yogini Ekadashi: agreement within ~2 minutes.',
        f'// Covers {START.date()} \u2013 {END.date()}. Regenerate this script (bump END) to extend the range.',
        'export interface TithiPeriod {',
        '  paksha: "Shukla" | "Krishna";',
        '  tithiStartUtc: string; // Ekadashi (11th) tithi begins \u2014 Dashami ends',
        '  tithiEndUtc: string;   // Ekadashi tithi ends \u2014 Dwadashi begins',
        '  dwadashiEndUtc: string; // Dwadashi ends \u2014 Trayodashi begins (for Parana window)',
        '}',
        '',
        'export const EKADASHI_TITHI_TABLE: TithiPeriod[] = [',
    ]
    for p in periods:
        lines.append(
            f'  {{ paksha: "{p["paksha"]}", tithiStartUtc: "{p["tithiStartUtc"]}", '
            f'tithiEndUtc: "{p["tithiEndUtc"]}", dwadashiEndUtc: "{p["dwadashiEndUtc"]}" }},'
        )
    lines.append('];')
    lines.append('')
    with open(OUT_PATH, 'w') as f:
        f.write('\n'.join(lines))


if __name__ == '__main__':
    print(f'Scanning {START.date()} to {END.date()} in {STEP} steps...')
    boundaries = find_boundaries()
    periods = build_ekadashi_periods(boundaries)
    print(f'Found {len(periods)} Ekadashi tithi periods.')
    write_ts(periods)
    print(f'Wrote {OUT_PATH}')
