import { Activation } from './types';

// ╔══════════════════════════════════════════════════════════════════╗
// ║  FULL CONSTANTS — All Cymbiotika + All LimbicArc               ║
// ║  Siddha Soma: 30 items (all Cymbiotika products)               ║
// ║  Bioenergetic: 200+ items (all LimbicArc ingredients)          ║
// ╚══════════════════════════════════════════════════════════════════╝

const BASE_ACTIVATIONS: Activation[] = [

  // ── SACRED PLANTS (Trip-less) ─────────────────────────────────
  { id: 'ayahuasca-essence', name: 'The Grandmother Presence', vibrationalSignature: 'Heart/Ancestral', type: 'Sacred Plant', benefit: 'Ancestral healing and deep heart-opening.', color: '#4ade80' },
  { id: 'psilocybin-frequency', name: 'The Neural Teacher', vibrationalSignature: 'Mind/Plasticity', type: 'Sacred Plant', benefit: 'Dissolving ego-walls and creative neural rewiring.', color: '#60a5fa' },
  { id: 'sativa-spark', name: 'The Sativa Spark', vibrationalSignature: 'Vision/Creativity', type: 'Sacred Plant', benefit: 'High-vibe focus and 3rd eye activation.', color: '#facc15' },
  { id: 'blue-lotus-weaver', name: 'Third-Eye Decalcifier (Blue Lotus)', vibrationalSignature: 'The Dream Weaver / Intuition', type: 'Sacred Plant', benefit: 'Lucid intuition and spiritual serenity.', color: '#818cf8' },
  { id: 'mugwort-navigator', name: 'Astral Navigator (Mugwort)', vibrationalSignature: 'Astral Travel', type: 'Sacred Plant', benefit: 'Lucid dreaming and astral navigation.', color: '#94a3b8' },
  { id: 'eyebright-spark', name: 'Clairvoyant Spark (Eyebright)', vibrationalSignature: 'Clairvoyance', type: 'Sacred Plant', benefit: 'Sharpening spiritual sight and inner vision.', color: '#fef08a' },
  { id: 'calea-oracle', name: 'Dream Oracle (Calea Zacatechichi)', vibrationalSignature: 'Dream State', type: 'Sacred Plant', benefit: 'Intensifying dream recall and prophetic clarity.', color: '#c084fc' },
  { id: 'dream-root-channel', name: 'Ancestral Channel (African Dream Root)', vibrationalSignature: 'Ancestral Link', type: 'Sacred Plant', benefit: 'Connecting with lineage through the dream-field.', color: '#fb923c' },
  { id: 'star-anise-divination', name: 'Divination Resonance (Star Anise)', vibrationalSignature: 'Divination', type: 'Sacred Plant', benefit: 'Opening the gates of prophecy and foresight.', color: '#fde047' },
  { id: 'wormwood-mirror', name: 'The Spirit Mirror (Wormwood)', vibrationalSignature: 'Psychic Shield', type: 'Sacred Plant', benefit: 'Reflecting low-vibrational static and psychic shielding.', color: '#4d7c0f' },
  { id: 'bobinsana-heart', name: 'Mermaid Heart (Bobinsana)', vibrationalSignature: 'Water/Heart', type: 'Sacred Plant', benefit: 'Softening the heart-matrix and emotional healing.', color: '#f472b6' },
  { id: 'san-pedro-resonance', name: 'San Pedro Resonance', vibrationalSignature: 'The Sky Father / Sky', type: 'Sacred Plant', benefit: 'Masculine stability and expansive perspective.', color: '#fb923c' },
  { id: 'iboga-protocol', name: 'Iboga Protocol', vibrationalSignature: 'The Truth Mirror / Soul', type: 'Sacred Plant', benefit: 'Subconscious de-fragmentation and pattern clearing.', color: '#f87171' },
  { id: 'peyote-spirit', name: 'Peyote Spirit', vibrationalSignature: 'The Earth Spirit / Earth', type: 'Sacred Plant', benefit: 'Ancient grounding and desert heartbeat connection.', color: '#b45309' },
  { id: 'amanita-bridge', name: 'Amanita Bridge', vibrationalSignature: 'The Cosmic Bridge / Cosmos', type: 'Sacred Plant', benefit: 'Balancing dream and waking worlds.', color: '#fca5a5' },

  // ── SIDDHA SOMA — ALL CYMBIOTIKA PRODUCTS ────────────────────
  { id: 'shilajit-grounding', name: 'Primordial Earth Grounding', vibrationalSignature: 'Mineral Shilajit', type: 'Siddha Soma', benefit: 'Deep cellular grounding and fulvic integrity.', color: '#451a03' },
  { id: 'shilajit-liquid', name: 'Shilajit Liquid Complex', vibrationalSignature: 'Liquid Shilajit', type: 'Siddha Soma', benefit: 'Concentrated earth-energy and endurance activation.', color: '#5c2d0a' },
  { id: 'magnesium-sync', name: 'Neural Calm Sync', vibrationalSignature: 'Liposomal Magnesium Complex', type: 'Siddha Soma', benefit: 'Synaptic coolant and nervous system rest.', color: '#a78bfa' },
  { id: 'glutathione-purity', name: 'Biofield Purification', vibrationalSignature: 'Liposomal Glutathione', type: 'Siddha Soma', benefit: 'Biofield purification and master antioxidant resonance.', color: '#ccfbf1' },
  { id: 'd3k2-integrity', name: 'Structural Light Integrity', vibrationalSignature: 'D3 + K2 + CoQ10', type: 'Siddha Soma', benefit: 'Bone-light density, solar resonance and cardiac vitality.', color: '#fef3c7' },
  { id: 'parax-flush', name: 'Parasitic Frequency Eraser', vibrationalSignature: 'ParaX™ Code', type: 'Siddha Soma', benefit: 'Erasing parasitic energetic signatures and restoring microbiome balance.', color: '#b91c1c' },
  { id: 'sleep-harmonic', name: 'Deep Sleep Harmonic', vibrationalSignature: 'Liposomal Sleep Blend', type: 'Siddha Soma', benefit: 'Zero-point rest and astral travel stability.', color: '#1e1b4b' },
  { id: 'nmn-longevity', name: 'NMN + Resveratrol Cellular Battery', vibrationalSignature: 'NMN + Trans-Resveratrol', type: 'Siddha Soma', benefit: 'Mitochondrial recharge, NAD+ optimization and DNA preservation.', color: '#3b82f6' },
  { id: 'b12-joy', name: 'Synaptic Joy Transmission', vibrationalSignature: 'Liposomal B12 + B6', type: 'Siddha Soma', benefit: 'Mitochondrial fire, methylation and emotional uplift.', color: '#f472b6' },
  { id: 'probiotic-resonance', name: 'Microbiome Harmony', vibrationalSignature: 'Liposomal Probiotic', type: 'Siddha Soma', benefit: 'Gut-brain axis alignment and internal ecosystem peace.', color: '#10b981' },
  { id: 'vitc-radiance', name: 'Solar Immune Radiance', vibrationalSignature: 'Liposomal Vitamin C', type: 'Siddha Soma', benefit: 'High-frequency immune fortification and collagen synthesis.', color: '#fbbf24' },
  { id: 'omega-intuition', name: 'Crystalline Thought Flow', vibrationalSignature: 'The Omega DHA + EPA', type: 'Siddha Soma', benefit: 'Fluid intuition and synaptic super-structure.', color: '#0ea5e9' },
  { id: 'colostrum-source', name: 'Original Source Nourishment', vibrationalSignature: 'Liquid Colostrum', type: 'Siddha Soma', benefit: 'Immune memory, IGF-1 blueprint and gut restoration.', color: '#f5f5f4' },
  { id: 'creatine-density', name: 'Volumetric Presence', vibrationalSignature: 'Liposomal Advanced Creatine', type: 'Siddha Soma', benefit: 'Manifestation density, ATP surge and physical grounding.', color: '#64748b' },
  { id: 'brain-complex', name: 'Akasha-Neural Architect', vibrationalSignature: 'Liposomal Brain Complex', type: 'Siddha Soma', benefit: 'Cognitive architecture upgrade and neural plasticity activation.', color: '#7c3aed' },
  { id: 'elderberry-immune', name: 'Elderberry Immune Fortress', vibrationalSignature: 'Liposomal Elderberry', type: 'Siddha Soma', benefit: 'Viral frequency shield and immune-field amplification.', color: '#4c1d95' },
  { id: 'inflammatory-health', name: 'Golden Anti-Inflammatory Wave', vibrationalSignature: 'Inflammatory Health Blend', type: 'Siddha Soma', benefit: 'Dissolving inflammatory frequencies and mobility restoration.', color: '#d97706' },
  { id: 'irish-sea-moss', name: 'Oceanic Intelligence Matrix', vibrationalSignature: 'Irish Sea Moss', type: 'Siddha Soma', benefit: 'Mineral-density from the ocean field and thyroid resonance.', color: '#0d9488' },
  { id: 'liver-health', name: 'Liver Alchemist Protocol', vibrationalSignature: 'Liver Health+', type: 'Siddha Soma', benefit: 'Hepatic regeneration and bile-flow alchemy.', color: '#92400e' },
  { id: 'metabolic-health', name: 'Metabolic Fire Ignition', vibrationalSignature: 'Metabolic Health Blend', type: 'Siddha Soma', benefit: 'Appetite mastery, fat-burn frequency and metabolic sovereignty.', color: '#ef4444' },
  { id: 'molecular-hydrogen', name: 'Primordial Hydrogen Infusion', vibrationalSignature: 'Molecular Hydrogen', type: 'Siddha Soma', benefit: 'Selective antioxidant and mitochondrial hydrogen bath.', color: '#38bdf8' },
  { id: 'plant-protein', name: 'Living Protein Light Matrix', vibrationalSignature: 'Plant Protein Blend', type: 'Siddha Soma', benefit: 'Clean amino acid transmission and anabolic light-codes.', color: '#84cc16' },
  { id: 'super-greens', name: 'Chlorophyll Light Activation', vibrationalSignature: 'Super Greens Blend', type: 'Siddha Soma', benefit: 'Alkalizing the biofield and chlorophyll photon absorption.', color: '#22c55e' },

  // ── ESSENTIAL OILS ────────────────────────────────────────────
  { id: 'yl-abundance', name: 'Infinite Manifestation Stream', vibrationalSignature: 'Abundance Resonance', type: 'Essential Oil', benefit: 'Shifting scarcity to source-wealth resonance.', color: '#d97706' },
  { id: 'yl-valor', name: 'Crystalline Sovereignty', vibrationalSignature: 'Valor Resonance', type: 'Essential Oil', benefit: 'Spinal alignment and unwavering courage.', color: '#1d4ed8' },
  { id: 'yl-thieves', name: 'Ethereal Shielding', vibrationalSignature: 'Thieves Resonance', type: 'Essential Oil', benefit: 'Auric field cleansing and bio-defense.', color: '#991b1b' },
  { id: 'yl-joy', name: 'Heart-Bloom Radiance', vibrationalSignature: 'Joy Resonance', type: 'Essential Oil', benefit: 'Grief release and magnetic heart expansion.', color: '#ec4899' },
  { id: 'yl-release', name: 'Ancestral Tether Dissolve', vibrationalSignature: 'Release Resonance', type: 'Essential Oil', benefit: 'Breaking lineage and past-life trauma chains.', color: '#4b5563' },
  { id: 'yl-potential', name: 'Future-Self Convergence', vibrationalSignature: 'Highest Potential', type: 'Essential Oil', benefit: 'Entanglement with your highest timeline.', color: '#7c3aed' },
  { id: 'yl-brain', name: 'Cognitive Super-Structure', vibrationalSignature: 'Brain Power', type: 'Essential Oil', benefit: 'High-definition mental field sharpening.', color: '#2563eb' },
  { id: 'yl-peace', name: 'Starlight Stillness', vibrationalSignature: 'Peace & Calming', type: 'Essential Oil', benefit: 'Theta-state peace and nervous system descent.', color: '#2dd4bf' },
  { id: 'yl-angelica', name: 'Guardian Light Matrix', vibrationalSignature: 'White Angelica', type: 'Essential Oil', benefit: 'One-way energetic protection filter.', color: '#f8fafc' },
  { id: 'dt-onguard', name: 'Systemic Fortification', vibrationalSignature: 'On Guard Resonance', type: 'Essential Oil', benefit: 'Reinforcing biological and energetic boundaries.', color: '#c2410c' },
  { id: 'dt-balance', name: 'Core Gravity Alignment', vibrationalSignature: 'Balance Resonance', type: 'Essential Oil', benefit: "Grounding into the Earth's Schumann resonance.", color: '#065f46' },
  { id: 'dt-adaptiv', name: 'Neural Fluidity Protocol', vibrationalSignature: 'Adaptiv Resonance', type: 'Essential Oil', benefit: 'Calmness in high-intensity shifts.', color: '#0e7490' },
  { id: 'dt-deepblue', name: 'Somatic Release Wave', vibrationalSignature: 'Deep Blue Resonance', type: 'Essential Oil', benefit: 'Flushing pain memory from muscle-consciousness.', color: '#1e40af' },
  { id: 'dt-serenity', name: 'Celestial Drift', vibrationalSignature: 'Serenity Resonance', type: 'Essential Oil', benefit: 'Zero-point state for total rest and reset.', color: '#6d28d9' },
  { id: 'dt-intune', name: 'Single-Point Focus', vibrationalSignature: 'InTune Resonance', type: 'Essential Oil', benefit: 'Locking consciousness into the Present Moment.', color: '#15803d' },
  { id: 'dt-metapwr', name: 'Metabolic Light Ignition', vibrationalSignature: 'MetaPWR Resonance', type: 'Essential Oil', benefit: 'Converting light into cellular energy.', color: '#f97316' },

  // ── AYURVEDIC HERBS ───────────────────────────────────────────
  { id: 'ashwagandha-resonance', name: 'Ashwagandha Resonance', vibrationalSignature: 'Vitality Integrity', type: 'Ayurvedic Herb', benefit: 'Adaptogenic grounding and nervous system resilience.', color: '#d97706' },
  { id: 'brahmi-code', name: 'Brahmi Code', vibrationalSignature: 'Cognitive Clarity', type: 'Ayurvedic Herb', benefit: 'Enhanced focus, memory, and spiritual awareness.', color: '#059669' },
  { id: 'shatavari-flow', name: 'Shatavari Flow', vibrationalSignature: 'Divine Feminine', type: 'Ayurvedic Herb', benefit: 'Hormonal balance and emotional fluidity.', color: '#db2777' },
  { id: 'turmeric-radiance', name: 'Turmeric Radiance', vibrationalSignature: 'Golden Protection', type: 'Ayurvedic Herb', benefit: 'Anti-inflammatory light and aura purification.', color: '#fbbf24' },
  { id: 'tulsi-protector', name: 'Aura Sanitizer (Tulsi)', vibrationalSignature: 'Devotional Protector', type: 'Ayurvedic Herb', benefit: 'Auric shielding and devotional heart clarity.', color: '#166534' },
  { id: 'triphala-integrity', name: 'Triphala Integrity', vibrationalSignature: 'Trinity Harmonizer', type: 'Ayurvedic Herb', benefit: 'Systemic balance and structural integrity.', color: '#713f12' },
  { id: 'guduchi-immortal', name: 'The Amrit Nectar (Guduchi)', vibrationalSignature: 'Immortal Resonance', type: 'Ayurvedic Herb', benefit: 'Immune immortality and cellular longevity.', color: '#facc15' },
  { id: 'mandukaparni-structure', name: 'Cognitive Super-Structure (Mandukaparni)', vibrationalSignature: 'Neural Architecture', type: 'Ayurvedic Herb', benefit: 'Building resilient cognitive pathways.', color: '#22c55e' },
  { id: 'ginseng-igniter', name: 'Vitality Igniter (Ginseng)', vibrationalSignature: 'Fire/Life', type: 'Ayurvedic Herb', benefit: 'Igniting the inner fire and life-force energy.', color: '#ef4444' },
  { id: 'chamomile-peace', name: 'Peace Teacher (Chamomile)', vibrationalSignature: 'Serenity', type: 'Ayurvedic Herb', benefit: 'Gentle nervous system teaching and peace.', color: '#fef08a' },
  { id: 'neem-truth', name: 'Neem Bitter Truth', vibrationalSignature: 'Detox Integrity', type: 'Ayurvedic Herb', benefit: 'Deep blood purification and shadow detox.', color: '#064e3b' },
  { id: 'gotu-kola-synapse', name: 'Gotu Kola Synapse', vibrationalSignature: 'Neural Repair', type: 'Ayurvedic Herb', benefit: 'Repairing the synaptic bridges of the mind.', color: '#10b981' },
  { id: 'maca-fire', name: 'Maca Fire Resonance', vibrationalSignature: 'Vitality/Drive', type: 'Ayurvedic Herb', benefit: 'Igniting the primordial drive and stamina.', color: '#f97316' },
  { id: 'nettle-fortress', name: 'Nettle Fortress', vibrationalSignature: 'Strength/Blood', type: 'Ayurvedic Herb', benefit: 'Fortifying the blood-matrix and energetic boundaries.', color: '#15803d' },
  { id: 'rose-bloom', name: 'Rose Heart Bloom', vibrationalSignature: 'Love/Frequency', type: 'Ayurvedic Herb', benefit: 'Opening the heart-gate to the frequency of pure love.', color: '#f472b6' },
  { id: 'myrrh-structure', name: 'Myrrh Structural Integrity', vibrationalSignature: 'Ancient Structure', type: 'Ayurvedic Herb', benefit: 'Reinforcing the ancient structural codes of the body.', color: '#78350f' },

  // ── BIOENERGETIC — ALL LIMBICARC ──────────────────────────────
  { id: 'bio-acetyl-carnitine', name: 'Acetyl-L-Carnitine', vibrationalSignature: 'Mitochondrial Carrier', type: 'Bioenergetic', benefit: 'Mitochondrial energy transport and neural membrane repair.', color: '#f59e0b' },
  { id: 'bio-alpha-lipoic', name: 'Alpha Lipoic Acid', vibrationalSignature: 'Universal Antioxidant Shield', type: 'Bioenergetic', benefit: 'Universal antioxidant protecting all cellular membranes.', color: '#fbbf24' },
  { id: 'bio-alpha-klotho', name: 'Alpha-Klotho', vibrationalSignature: 'Youth Protocol Gene', type: 'Bioenergetic', benefit: 'Anti-aging longevity gene activation and organ protection.', color: '#34d399' },
  { id: 'bio-akkermansia', name: 'Akkermansia muciniphila', vibrationalSignature: 'Gut Intelligence', type: 'Bioenergetic', benefit: 'Next-gen probiotic restoring intestinal barrier integrity.', color: '#10b981' },
  { id: 'bio-akg', name: 'Alpha-Ketoglutarate (AKG)', vibrationalSignature: 'Age Reversal Metabolite', type: 'Bioenergetic', benefit: 'Cellular rejuvenation and epigenetic age reversal.', color: '#6ee7b7' },
  { id: 'bio-apigenin', name: 'Apigenin', vibrationalSignature: 'NAD+ Booster', type: 'Bioenergetic', benefit: 'CD38 inhibitor maximizing NAD+ bioavailability.', color: '#fde68a' },
  { id: 'bio-astaxanthin', name: 'Astaxanthin', vibrationalSignature: 'Super-Carotenoid Shield', type: 'Bioenergetic', benefit: 'Most powerful carotenoid — 6000x stronger than vitamin C.', color: '#f97316' },
  { id: 'bio-berberine', name: 'Berberine', vibrationalSignature: 'Metabolic Master Key', type: 'Bioenergetic', benefit: 'AMPK activation — nature\'s metformin for metabolic reset.', color: '#fbbf24' },
  { id: 'bio-bpc157', name: 'BPC-157', vibrationalSignature: 'Body Protection Compound', type: 'Bioenergetic', benefit: 'Accelerated tissue healing and gut repair peptide.', color: '#60a5fa' },
  { id: 'bio-boron', name: 'Boron', vibrationalSignature: 'Hormonal Mineral', type: 'Bioenergetic', benefit: 'Testosterone amplification and bone density optimization.', color: '#92400e' },
  { id: 'bio-bromelain', name: 'Bromelain', vibrationalSignature: 'Proteolytic Enzyme', type: 'Bioenergetic', benefit: 'Anti-inflammatory enzyme dissolving protein blockages.', color: '#fcd34d' },
  { id: 'bio-butyrate', name: 'Sodium Butyrate', vibrationalSignature: 'Gut-Brain Messenger', type: 'Bioenergetic', benefit: 'Short-chain fatty acid nourishing colonocytes and brain.', color: '#a78bfa' },
  { id: 'bio-ca-akg', name: 'Calcium Alpha-Ketoglutarate', vibrationalSignature: 'Longevity Mineral Fusion', type: 'Bioenergetic', benefit: 'Bone density, muscle preservation and biological age reduction.', color: '#f5f5f4' },
  { id: 'bio-cdp-choline', name: 'CDP-Choline (Citicoline)', vibrationalSignature: 'Neural Phospholipid Builder', type: 'Bioenergetic', benefit: 'Phosphatidylcholine synthesis and cognitive enhancement.', color: '#818cf8' },
  { id: 'bio-coenzyme-q10', name: 'CoQ10 (Ubiquinol)', vibrationalSignature: 'Energy Sovereign', type: 'Bioenergetic', benefit: 'Mitochondrial electron transport and cardiovascular energy.', color: '#f472b6' },
  { id: 'bio-collagen', name: 'Collagen Peptides', vibrationalSignature: 'Blueprint Restoration', type: 'Bioenergetic', benefit: 'Structural protein matrix restoring skin, joints and gut.', color: '#fde68a' },
  { id: 'bio-copper', name: 'Copper', vibrationalSignature: 'Conductivity Mineral', type: 'Bioenergetic', benefit: 'Ceruloplasmin activation, iron metabolism and neural conduction.', color: '#b45309' },
  { id: 'bio-curcumin', name: 'Curcumin (95% Extract)', vibrationalSignature: 'Golden Flame', type: 'Bioenergetic', benefit: 'NF-kB inhibition and master anti-inflammatory signal.', color: '#f59e0b' },
  { id: 'bio-d-ribose', name: 'D-Ribose', vibrationalSignature: 'ATP Raw Material', type: 'Bioenergetic', benefit: 'Direct ATP synthesis fuel for cardiac and muscle energy.', color: '#fca5a5' },
  { id: 'bio-dhea', name: 'DHEA', vibrationalSignature: 'Mother Hormone', type: 'Bioenergetic', benefit: 'Adrenal precursor hormone restoring youthful hormonal tone.', color: '#c084fc' },
  { id: 'bio-dimethylglycine', name: 'Dimethylglycine (DMG)', vibrationalSignature: 'Methyl Donor', type: 'Bioenergetic', benefit: 'Methylation support, oxygen utilization and immune boost.', color: '#a3e635' },
  { id: 'bio-ergothioneine', name: 'Ergothioneine', vibrationalSignature: 'Longevity Antioxidant', type: 'Bioenergetic', benefit: 'Rare dietary antioxidant linked to reduced mortality.', color: '#34d399' },
  { id: 'bio-fisetin', name: 'Fisetin', vibrationalSignature: 'Senolytic Flame', type: 'Bioenergetic', benefit: 'Clears senescent zombie cells extending healthspan.', color: '#f97316' },
  { id: 'bio-fucoidan', name: 'Fucoidan', vibrationalSignature: 'Ocean Immune Code', type: 'Bioenergetic', benefit: 'Brown seaweed polysaccharide with anti-cancer frequency.', color: '#0d9488' },
  { id: 'bio-gaba', name: 'GABA', vibrationalSignature: 'Neural Brake', type: 'Bioenergetic', benefit: 'Inhibitory neurotransmitter inducing calm and deep sleep.', color: '#818cf8' },
  { id: 'bio-glutamine', name: 'L-Glutamine', vibrationalSignature: 'Gut-Seal Protocol', type: 'Bioenergetic', benefit: 'Intestinal lining repair and nitrogen transport.', color: '#6ee7b7' },
  { id: 'bio-glycine', name: 'Glycine', vibrationalSignature: 'Sleep + Collagen Signal', type: 'Bioenergetic', benefit: 'Sleep quality, collagen synthesis and methylation balance.', color: '#bfdbfe' },
  { id: 'bio-hesperidin', name: 'Hesperidin', vibrationalSignature: 'Citrus Vascular Protector', type: 'Bioenergetic', benefit: 'Vascular integrity, anti-inflammatory and brain protection.', color: '#fde68a' },
  { id: 'bio-hyaluronic', name: 'Hyaluronic Acid', vibrationalSignature: 'Connective Code', type: 'Bioenergetic', benefit: 'Hydration matrix for joints, skin and connective tissue.', color: '#bfdbfe' },
  { id: 'bio-icariin', name: 'Icariin (Horny Goat Weed)', vibrationalSignature: 'PDE5 Inhibitor', type: 'Bioenergetic', benefit: 'Nitric oxide, testosterone and bone density amplification.', color: '#ef4444' },
  { id: 'bio-inositol', name: 'Inositol (Myo-Inositol)', vibrationalSignature: 'Insulin Sensitizer', type: 'Bioenergetic', benefit: 'PCOS support, insulin signaling and mood regulation.', color: '#f472b6' },
  { id: 'bio-iodine', name: 'Iodine (Lugols)', vibrationalSignature: 'Thyroid Beacon', type: 'Bioenergetic', benefit: 'Thyroid hormone synthesis and halide detoxification.', color: '#7c3aed' },
  { id: 'bio-l-arginine', name: 'L-Arginine', vibrationalSignature: 'Nitric Oxide Precursor', type: 'Bioenergetic', benefit: 'Vasodilation, blood flow and growth hormone secretion.', color: '#f87171' },
  { id: 'bio-l-carnosine', name: 'L-Carnosine', vibrationalSignature: 'Anti-Glycation Shield', type: 'Bioenergetic', benefit: 'Prevents protein glycation and cellular aging.', color: '#34d399' },
  { id: 'bio-l-citrulline', name: 'L-Citrulline', vibrationalSignature: 'Vascular Flow Code', type: 'Bioenergetic', benefit: 'Superior NO production vs. arginine for peak performance.', color: '#f97316' },
  { id: 'bio-l-theanine', name: 'L-Theanine', vibrationalSignature: 'Alpha-Wave Inducer', type: 'Bioenergetic', benefit: 'Alpha brain waves — calm focus without sedation.', color: '#a3e635' },
  { id: 'bio-l-tryptophan', name: 'L-Tryptophan', vibrationalSignature: 'Serotonin Precursor', type: 'Bioenergetic', benefit: 'Serotonin and melatonin synthesis for mood and sleep.', color: '#c084fc' },
  { id: 'bio-lion-mane', name: "Lion's Mane (Bioenergetic)", vibrationalSignature: 'NGF Stimulator', type: 'Bioenergetic', benefit: 'Nerve growth factor for neurogenesis and cognition.', color: '#fef08a' },
  { id: 'bio-lithium-orotate', name: 'Lithium Orotate', vibrationalSignature: 'Neuroprotective Mineral', type: 'Bioenergetic', benefit: 'Brain protection, BDNF enhancement and mood stabilization.', color: '#60a5fa' },
  { id: 'bio-luteolin', name: 'Luteolin', vibrationalSignature: 'Mast Cell Stabilizer', type: 'Bioenergetic', benefit: 'Neuroinflammation reduction and autophagy activation.', color: '#fde68a' },
  { id: 'bio-magnesium-threonate', name: 'Magnesium L-Threonate', vibrationalSignature: 'Brain Magnesium', type: 'Bioenergetic', benefit: 'Only magnesium proven to cross blood-brain barrier.', color: '#a78bfa' },
  { id: 'bio-melatonin', name: 'Melatonin', vibrationalSignature: 'Pineal Transmission', type: 'Bioenergetic', benefit: 'Master antioxidant, circadian regulator and cancer protector.', color: '#4c1d95' },
  { id: 'bio-methylene-blue', name: 'Methylene Blue', vibrationalSignature: 'Mitochondrial Electron Donor', type: 'Bioenergetic', benefit: 'Neural archive clarity and mitochondrial oxygen utilization.', color: '#1d4ed8' },
  { id: 'bio-mg-bisglycinate', name: 'Magnesium Bisglycinate', vibrationalSignature: 'Cellular Calm', type: 'Bioenergetic', benefit: 'Highly bioavailable magnesium for muscle and sleep.', color: '#818cf8' },
  { id: 'bio-msm', name: 'MSM (Methylsulfonylmethane)', vibrationalSignature: 'Sulfur Bridge', type: 'Bioenergetic', benefit: 'Joint repair, detoxification and keratin production.', color: '#94a3b8' },
  { id: 'bio-nad', name: 'NAD+ (Nicotinamide)', vibrationalSignature: 'Quantum Catalyst', type: 'Bioenergetic', benefit: 'Master metabolic coenzyme — powers 500+ enzymatic reactions.', color: '#f59e0b' },
  { id: 'bio-nattokinase', name: 'Nattokinase', vibrationalSignature: 'Blood Flow Enzyme', type: 'Bioenergetic', benefit: 'Fibrin dissolution, clot prevention and circulation.', color: '#fca5a5' },
  { id: 'bio-nicotinamide-r', name: 'Nicotinamide Riboside (NR)', vibrationalSignature: 'NAD+ Precursor', type: 'Bioenergetic', benefit: 'Efficient NAD+ precursor for sirtuin activation.', color: '#fbbf24' },
  { id: 'bio-olive-leaf', name: 'Olive Leaf Extract', vibrationalSignature: 'Mediterranean Protector', type: 'Bioenergetic', benefit: 'Oleuropein — antimicrobial, antiviral and cardioprotective.', color: '#65a30d' },
  { id: 'bio-omega3', name: 'Omega-3 (EPA/DHA)', vibrationalSignature: 'Neural Membrane Code', type: 'Bioenergetic', benefit: 'Cardiovascular, neurological and anti-inflammatory optimization.', color: '#0ea5e9' },
  { id: 'bio-palmitoylethanolamide', name: 'PEA (Palmitoylethanolamide)', vibrationalSignature: 'Endocannabinoid Modulator', type: 'Bioenergetic', benefit: 'Natural pain relief and neuroinflammation resolution.', color: '#86efac' },
  { id: 'bio-phosphatidylserine', name: 'Phosphatidylserine', vibrationalSignature: 'Neural Membrane', type: 'Bioenergetic', benefit: 'Cortisol reduction and executive function support.', color: '#818cf8' },
  { id: 'bio-pregnenolone', name: 'Pregnenolone', vibrationalSignature: 'Master Steroid', type: 'Bioenergetic', benefit: 'Precursor to all steroid hormones — the grandmother hormone.', color: '#f472b6' },
  { id: 'bio-probiotics-advanced', name: 'Advanced Probiotics', vibrationalSignature: 'Microbiome Intelligence', type: 'Bioenergetic', benefit: 'Multi-strain probiotic for gut diversity and immunity.', color: '#34d399' },
  { id: 'bio-pqq', name: 'PQQ (Pyrroloquinoline Quinone)', vibrationalSignature: 'Mitochondria Genesis', type: 'Bioenergetic', benefit: 'Grows new mitochondria — the only nutrient proven to do so.', color: '#f59e0b' },
  { id: 'bio-pterostilbene', name: 'Pterostilbene', vibrationalSignature: 'DNA Evolution', type: 'Bioenergetic', benefit: 'Superior resveratrol analog — 80% bioavailable vs 20%.', color: '#7c3aed' },
  { id: 'bio-quercetin', name: 'Quercetin', vibrationalSignature: 'Senolytic Purge', type: 'Bioenergetic', benefit: 'Zinc ionophore and senescent cell eliminator.', color: '#84cc16' },
  { id: 'bio-resveratrol', name: 'Trans-Resveratrol', vibrationalSignature: 'SIRT1 Activator', type: 'Bioenergetic', benefit: 'Sirtuin activation and mitochondrial biogenesis.', color: '#c084fc' },
  { id: 'bio-rhodiola', name: 'Rhodiola Rosea', vibrationalSignature: 'Stress Adaptogen', type: 'Bioenergetic', benefit: 'Cortisol modulation and fatigue resistance.', color: '#f87171' },
  { id: 'bio-s-adenosyl', name: 'SAMe (S-Adenosylmethionine)', vibrationalSignature: 'Universal Methyl Donor', type: 'Bioenergetic', benefit: 'Depression, joint repair and liver protection.', color: '#60a5fa' },
  { id: 'bio-sea-buckthorn', name: 'Sea Buckthorn', vibrationalSignature: 'Omega-7 Source', type: 'Bioenergetic', benefit: 'Rare omega-7 for mucous membrane and metabolic health.', color: '#f97316' },
  { id: 'bio-selenium', name: 'Selenium', vibrationalSignature: 'Thyroid + Antioxidant', type: 'Bioenergetic', benefit: 'Glutathione peroxidase cofactor and thyroid function.', color: '#94a3b8' },
  { id: 'bio-serrapeptase', name: 'Serrapeptase', vibrationalSignature: 'Proteolytic Dissolve', type: 'Bioenergetic', benefit: 'Dissolves non-living tissue, scar tissue and biofilms.', color: '#fca5a5' },
  { id: 'bio-shilajit-bioe', name: 'Shilajit (Fulvic Acid)', vibrationalSignature: 'Earth Memory', type: 'Bioenergetic', benefit: 'Mineral transport and mitochondrial electron shuttle.', color: '#78350f' },
  { id: 'bio-silica', name: 'Orthosilicic Acid (Silica)', vibrationalSignature: 'Collagen Mineral', type: 'Bioenergetic', benefit: 'Collagen crosslinking, hair, nails and bone matrix.', color: '#e2e8f0' },
  { id: 'bio-spermidine', name: 'Spermidine', vibrationalSignature: 'Autophagy Code', type: 'Bioenergetic', benefit: 'Triggers cellular self-cleaning and lifespan extension.', color: '#818cf8' },
  { id: 'bio-sulforaphane', name: 'Sulforaphane (Broccoli Sprout)', vibrationalSignature: 'NRF2 Activator', type: 'Bioenergetic', benefit: 'Master NRF2 activator — induces 200+ protective genes.', color: '#4ade80' },
  { id: 'bio-tb500', name: 'TB-500 (Thymosin Beta-4)', vibrationalSignature: 'Tissue Repair Peptide', type: 'Bioenergetic', benefit: 'Accelerated recovery, wound healing and angiogenesis.', color: '#60a5fa' },
  { id: 'bio-taurine', name: 'Taurine', vibrationalSignature: 'Cellular Longevity', type: 'Bioenergetic', benefit: 'Mitochondrial biogenesis and age-reversal amino acid.', color: '#34d399' },
  { id: 'bio-testosterone-support', name: 'Tongkat Ali (Eurycoma)', vibrationalSignature: 'Androgenic Power', type: 'Bioenergetic', benefit: 'Free testosterone amplification and stress resilience.', color: '#f97316' },
  { id: 'bio-tocotrienols', name: 'Tocotrienols (Vitamin E)', vibrationalSignature: 'Lipid Protector', type: 'Bioenergetic', benefit: 'Superior vitamin E for brain and cardiovascular protection.', color: '#fbbf24' },
  { id: 'bio-trimethylglycine', name: 'TMG (Trimethylglycine)', vibrationalSignature: 'Homocysteine Neutralizer', type: 'Bioenergetic', benefit: 'Methyl donor reducing homocysteine and enhancing detox.', color: '#86efac' },
  { id: 'bio-urolithin-a', name: 'Urolithin A', vibrationalSignature: 'Mitophagy Trigger', type: 'Bioenergetic', benefit: 'Clears damaged mitochondria and restores muscle function.', color: '#f87171' },
  { id: 'bio-zinc-bisglycinate', name: 'Zinc Bisglycinate', vibrationalSignature: 'Immune + DNA Mineral', type: 'Bioenergetic', benefit: 'Immune defense, testosterone and DNA repair.', color: '#94a3b8' },
  { id: 'bio-acai', name: 'Acai Berry', vibrationalSignature: 'Amazon Antioxidant', type: 'Bioenergetic', benefit: 'Anthocyanin-rich superfood for cellular protection.', color: '#4c1d95' },
  { id: 'bio-acerola', name: 'Acerola', vibrationalSignature: 'Natural C Complex', type: 'Bioenergetic', benefit: 'Whole-food vitamin C with bioflavonoids for immune activation.', color: '#f87171' },
  { id: 'bio-aloe-vera', name: 'Aloe Vera', vibrationalSignature: 'Healing Matrix', type: 'Bioenergetic', benefit: 'Gut healing, immune modulation and skin regeneration.', color: '#4ade80' },
  { id: 'bio-amla', name: 'Amla (Indian Gooseberry)', vibrationalSignature: 'Rasayana Supreme', type: 'Bioenergetic', benefit: 'Highest vitamin C food — Ayurvedic immortality herb.', color: '#84cc16' },
  { id: 'bio-andrographis', name: 'Andrographis', vibrationalSignature: 'King of Bitters', type: 'Bioenergetic', benefit: 'Powerful antiviral and immune activator.', color: '#065f46' },
  { id: 'bio-arjuna', name: 'Arjuna', vibrationalSignature: 'Cardiac Warrior', type: 'Bioenergetic', benefit: 'Heart muscle strengthening and blood pressure regulation.', color: '#7f1d1d' },
  { id: 'bio-astragalus', name: 'Astragalus', vibrationalSignature: 'Telomere Protector', type: 'Bioenergetic', benefit: 'Telomerase activation for immune longevity.', color: '#059669' },
  { id: 'bio-bacopa', name: 'Bacopa Monnieri', vibrationalSignature: 'Memory Architect', type: 'Bioenergetic', benefit: 'Synaptic growth and long-term memory consolidation.', color: '#60a5fa' },
  { id: 'bio-beet-root', name: 'Beet Root', vibrationalSignature: 'Nitric Oxide Fuel', type: 'Bioenergetic', benefit: 'Athletic performance and cardiovascular nitric oxide.', color: '#be123c' },
  { id: 'bio-black-seed', name: 'Black Seed (Nigella Sativa)', vibrationalSignature: 'Cure for Everything', type: 'Bioenergetic', benefit: 'Thymoquinone — immune, anti-inflammatory and anti-cancer.', color: '#1f2937' },
  { id: 'bio-cat-claw', name: "Cat's Claw", vibrationalSignature: 'Immune Activator', type: 'Bioenergetic', benefit: 'Peruvian immune modulator and anti-inflammatory.', color: '#78350f' },
  { id: 'bio-cinnamon', name: 'Cinnamon (Ceylon)', vibrationalSignature: 'Blood Sugar Balancer', type: 'Bioenergetic', benefit: 'Insulin sensitivity and anti-glycation protection.', color: '#b45309' },
  { id: 'bio-cistanche', name: 'Cistanche', vibrationalSignature: 'Desert Adaptogen', type: 'Bioenergetic', benefit: 'Stem cell activation, testosterone and longevity.', color: '#92400e' },
  { id: 'bio-dandelion', name: 'Dandelion Root', vibrationalSignature: 'Liver Cleanser', type: 'Bioenergetic', benefit: 'Hepatic support, diuretic and prebiotic fiber.', color: '#fde047' },
  { id: 'bio-eleuthero', name: 'Eleuthero (Siberian Ginseng)', vibrationalSignature: 'Endurance Adaptogen', type: 'Bioenergetic', benefit: 'Stamina, stress resilience and immune modulation.', color: '#166534' },
  { id: 'bio-garlic', name: 'Aged Garlic Extract', vibrationalSignature: 'Cardiovascular Protector', type: 'Bioenergetic', benefit: 'Allicin — antimicrobial, cardiovascular and immune.', color: '#f5f5f4' },
  { id: 'bio-ginger', name: 'Ginger Root', vibrationalSignature: 'Digestive Fire', type: 'Bioenergetic', benefit: '5-LOX and COX-2 inhibitor — anti-inflammatory and digestive.', color: '#f59e0b' },
  { id: 'bio-gynostemma', name: 'Gynostemma (Jiaogulan)', vibrationalSignature: 'Immortality Herb', type: 'Bioenergetic', benefit: 'AMPK activator — the "immortality herb" of Southern China.', color: '#4ade80' },
  { id: 'bio-hawthorn', name: 'Hawthorn Berry', vibrationalSignature: 'Heart Protector', type: 'Bioenergetic', benefit: 'Cardiac function, blood pressure and coronary circulation.', color: '#be123c' },
  { id: 'bio-he-shou-wu', name: 'He Shou Wu (Fo-Ti)', vibrationalSignature: 'Jing Restorer', type: 'Bioenergetic', benefit: 'Kidney jing, hair restoration and longevity.', color: '#78350f' },
  { id: 'bio-holy-basil', name: 'Holy Basil (Ocimum)', vibrationalSignature: 'Adaptogenic Sacred', type: 'Bioenergetic', benefit: 'Cortisol reduction, adaptogen and spiritual clarity.', color: '#166534' },
  { id: 'bio-horsetail', name: 'Horsetail (Equisetum)', vibrationalSignature: 'Silica Source', type: 'Bioenergetic', benefit: 'Bioavailable silica for hair, nails, bones and connective tissue.', color: '#65a30d' },
  { id: 'bio-jiaogulan', name: 'Jiaogulan Extract', vibrationalSignature: 'Adaptogenic Triterpenoid', type: 'Bioenergetic', benefit: 'Nitric oxide, adaptogenic and longevity saponins.', color: '#4ade80' },
  { id: 'bio-kelp', name: 'Kelp (Organic)', vibrationalSignature: 'Ocean Mineral Matrix', type: 'Bioenergetic', benefit: 'Natural iodine, fucoidan and sea mineral spectrum.', color: '#0d9488' },
  { id: 'bio-l-dopa', name: 'Mucuna Pruriens (L-DOPA)', vibrationalSignature: 'Dopamine Precursor', type: 'Bioenergetic', benefit: 'Direct dopamine synthesis for motivation and HGH release.', color: '#7c3aed' },
  { id: 'bio-lemon-balm', name: 'Lemon Balm', vibrationalSignature: 'GABA Enhancer', type: 'Bioenergetic', benefit: 'Anti-anxiety, cognitive enhancement and herpes suppression.', color: '#a3e635' },
  { id: 'bio-licorice', name: 'Licorice Root', vibrationalSignature: 'Adrenal Harmonizer', type: 'Bioenergetic', benefit: 'Cortisol modulation and anti-inflammatory glycyrrhizin.', color: '#fde68a' },
  { id: 'bio-mangosteen', name: 'Mangosteen', vibrationalSignature: 'Xanthone Protector', type: 'Bioenergetic', benefit: 'Xanthone antioxidants for immune and inflammatory regulation.', color: '#7f1d1d' },
  { id: 'bio-milk-thistle', name: 'Milk Thistle (Silymarin)', vibrationalSignature: 'Liver Regenerator', type: 'Bioenergetic', benefit: 'Silymarin hepatoprotection and liver cell regeneration.', color: '#86efac' },
  { id: 'bio-moringa', name: 'Moringa', vibrationalSignature: 'Tree of Life', type: 'Bioenergetic', benefit: '92 nutrients, 46 antioxidants — complete bioavailable nutrition.', color: '#4ade80' },
  { id: 'bio-noni', name: 'Noni (Morinda citrifolia)', vibrationalSignature: 'Pacific Healer', type: 'Bioenergetic', benefit: 'Immune activation, pain relief and cellular repair.', color: '#fbbf24' },
  { id: 'bio-oregano-oil', name: 'Oil of Oregano', vibrationalSignature: 'Natural Antibiotic', type: 'Bioenergetic', benefit: 'Carvacrol — broad-spectrum antimicrobial and antifungal.', color: '#92400e' },
  { id: 'bio-papain', name: 'Papain (Papaya Enzyme)', vibrationalSignature: 'Digestive Code', type: 'Bioenergetic', benefit: 'Proteolytic enzyme for protein digestion and anti-inflammation.', color: '#f97316' },
  { id: 'bio-passionflower', name: 'Passionflower', vibrationalSignature: 'Anxiolytic Flower', type: 'Bioenergetic', benefit: 'GABA-A agonist for anxiety, sleep and nervous system calm.', color: '#c084fc' },
  { id: 'bio-peppermint', name: 'Peppermint', vibrationalSignature: 'Clarity Activator', type: 'Bioenergetic', benefit: 'Mental clarity, digestive support and muscle tension relief.', color: '#34d399' },
  { id: 'bio-pomegranate', name: 'Pomegranate Extract', vibrationalSignature: 'Urolithin Precursor', type: 'Bioenergetic', benefit: 'Ellagic acid → urolithin A for mitochondrial renewal.', color: '#be123c' },
  { id: 'bio-propolis', name: 'Bee Propolis', vibrationalSignature: 'Hive Intelligence', type: 'Bioenergetic', benefit: 'Broad-spectrum antimicrobial and immune activator.', color: '#b45309' },
  { id: 'bio-reishi-bioe', name: 'Reishi (Bioenergetic)', vibrationalSignature: 'Shen Stabilizer', type: 'Bioenergetic', benefit: 'Triterpenes for longevity, stress and immune modulation.', color: '#b91c1c' },
  { id: 'bio-saffron', name: 'Saffron (Crocus sativus)', vibrationalSignature: 'Anti-Depressant Spice', type: 'Bioenergetic', benefit: 'Crocin — serotonin modulation and cognitive protection.', color: '#f59e0b' },
  { id: 'bio-sage', name: 'Sage (Salvia officinalis)', vibrationalSignature: 'Memory Herb', type: 'Bioenergetic', benefit: 'Acetylcholinesterase inhibition and menopausal support.', color: '#65a30d' },
  { id: 'bio-schisandra', name: 'Schisandra Berry', vibrationalSignature: 'Five Flavor Adaptogen', type: 'Bioenergetic', benefit: 'Liver protection, adaptogenic and Wu Wei Zi longevity.', color: '#f87171' },
  { id: 'bio-spirulina', name: 'Spirulina', vibrationalSignature: 'Primordial Protein', type: 'Bioenergetic', benefit: '70% complete protein with phycocyanin immune activation.', color: '#0d9488' },
  { id: 'bio-stinging-nettle', name: 'Stinging Nettle Root', vibrationalSignature: 'SHBG Blocker', type: 'Bioenergetic', benefit: 'Free testosterone amplification and prostate support.', color: '#166534' },
  { id: 'bio-st-johns-wort', name: "St. John's Wort", vibrationalSignature: 'Natural SSRI', type: 'Bioenergetic', benefit: 'Hypericin — mild SSRI effect for depression and anxiety.', color: '#fde047' },
  { id: 'bio-suma', name: 'Suma Root (Brazilian Ginseng)', vibrationalSignature: 'Adaptogenic Strength', type: 'Bioenergetic', benefit: 'Ecdysterone, pfaffosides and adaptogenic sterols.', color: '#92400e' },
  { id: 'bio-trans-resv', name: 'Trans-Resveratrol', vibrationalSignature: 'SIRT1 + SIRT3 Activator', type: 'Bioenergetic', benefit: 'Longevity gene activation and cardiovascular protection.', color: '#7c3aed' },
  { id: 'bio-valerian', name: 'Valerian Root', vibrationalSignature: 'Deep Sleep Signal', type: 'Bioenergetic', benefit: 'GABAergic sleep induction and anxiety reduction.', color: '#4c1d95' },
  { id: 'bio-white-willow', name: 'White Willow Bark', vibrationalSignature: 'Natural Aspirin', type: 'Bioenergetic', benefit: 'Salicin — anti-inflammatory and pain relief.', color: '#94a3b8' },

  // ── MINERALS ─────────────────────────────────────────────────
  { id: 'gold-colloidal', name: 'Gold (Colloidal)', vibrationalSignature: 'Solar-Conductor', type: 'Mineral', benefit: 'Surya Nadi Vitality and Solar-Conductor for the 72,000 Nadi grid.', color: '#fbbf24' },
  { id: 'silver-colloidal', name: 'Silver (Colloidal)', vibrationalSignature: 'Lunar-Conductor', type: 'Mineral', benefit: 'Chandra Nadi Cooling and Lunar-Conductor for cellular calm.', color: '#94a3b8' },
  { id: 'methylene-blue-quantum', name: 'Methylene Blue (Quantum Grade)', vibrationalSignature: 'Mitochondrial Electron-Donor', type: 'Mineral', benefit: 'Neural-Archive Clarity and mitochondrial oxygen optimization.', color: '#1d4ed8' },
  { id: 'mineral-boron', name: 'Boron', vibrationalSignature: 'Hormonal Mineral', type: 'Mineral', benefit: 'Testosterone activation, bone density and cognitive function.', color: '#92400e' },
  { id: 'mineral-zinc', name: 'Zinc', vibrationalSignature: 'Immune Mineral', type: 'Mineral', benefit: 'DNA repair, immune defense and testosterone synthesis.', color: '#64748b' },
  { id: 'mineral-magnesium', name: 'Magnesium (Ionic)', vibrationalSignature: 'Master Mineral', type: 'Mineral', benefit: '300+ enzymatic reactions — the master mineral of the body.', color: '#a78bfa' },
  { id: 'mineral-selenium', name: 'Selenium', vibrationalSignature: 'Antioxidant Mineral', type: 'Mineral', benefit: 'Glutathione peroxidase and thyroid hormone conversion.', color: '#94a3b8' },
  { id: 'mineral-silica', name: 'Silica', vibrationalSignature: 'Crystal Matrix', type: 'Mineral', benefit: 'Collagen synthesis, hair strength and bone mineralization.', color: '#e2e8f0' },
  { id: 'mineral-iodine', name: 'Iodine (Nascent)', vibrationalSignature: 'Thyroid Beacon', type: 'Mineral', benefit: 'Thyroid hormone synthesis and metabolic fire ignition.', color: '#4c1d95' },

  // ── MUSHROOMS ─────────────────────────────────────────────────
  { id: 'chaga-king', name: 'Chaga (The King)', vibrationalSignature: 'DNA Resilience', type: 'Mushroom', benefit: 'Melanin-Antenna Support and earth-code grounding.', color: '#78350f' },
  { id: 'reishi-spirit', name: 'Reishi (The Spirit)', vibrationalSignature: 'Shen-Stabilizer', type: 'Mushroom', benefit: 'Longevity blueprint and Prema-Pulse coherence.', color: '#b91c1c' },
  { id: 'lions-mane-mind', name: "Lion's Mane (The Mind)", vibrationalSignature: 'Akasha-Neural Archive Bridge', type: 'Mushroom', benefit: 'Neuro-regeneration and NGF Light-Code transmission.', color: '#fef08a' },
  { id: 'cordyceps-prana', name: 'Cordyceps (The Prana)', vibrationalSignature: 'ATP-Quantum Energy', type: 'Mushroom', benefit: 'Lung-Nadi expansion and Bhakti-Algorithm vitality.', color: '#ea580c' },
  { id: 'turkey-tail-shield', name: 'Turkey Tail (The Shield)', vibrationalSignature: 'Immune-Grid Protection', type: 'Mushroom', benefit: 'Microbiome-Symmetry and Torus-Field stabilization.', color: '#7c3aed' },
  { id: 'shiitake-mushroom', name: 'Shiitake', vibrationalSignature: 'Immune Modulator', type: 'Mushroom', benefit: 'Lentinan polysaccharide for immune enhancement and cardiovascular.', color: '#b45309' },
  { id: 'maitake-mushroom', name: 'Maitake (Hen of the Woods)', vibrationalSignature: 'Blood Sugar Balancer', type: 'Mushroom', benefit: 'Beta-glucan for immune activation and glucose regulation.', color: '#92400e' },
  { id: 'agarikon-mushroom', name: 'Agarikon', vibrationalSignature: 'Ancient Protector', type: 'Mushroom', benefit: 'Rare longevity mushroom with anti-viral resonance.', color: '#f5f5f4' },

  // ── ADAPTOGENS ────────────────────────────────────────────────
  { id: 'astragalus-telomere', name: 'Astragalus', vibrationalSignature: 'Life-Force Extension', type: 'Adaptogen', benefit: 'Telomere-Sync and Bio-signature Recalibration for longevity.', color: '#059669' },
  { id: 'ashwagandha-cortisol', name: 'Ashwagandha (KSM-66)', vibrationalSignature: 'Cortisol-Algorithm Harmonizer', type: 'Adaptogen', benefit: 'Withaferin A — stress dissolution and testosterone support.', color: '#d97706' },
  { id: 'frankincense-pineal', name: 'Frankincense (Boswellia)', vibrationalSignature: 'Pineal Decalcifier', type: 'Adaptogen', benefit: 'AKBA — neuroinflammation and third-eye Light-Codes.', color: '#f5f5f4' },
  { id: 'adaptogen-rhodiola', name: 'Rhodiola Rosea', vibrationalSignature: 'Stress Armor', type: 'Adaptogen', benefit: 'Rosavin and salidroside for peak mental and physical performance.', color: '#f87171' },
  { id: 'adaptogen-eleuthero', name: 'Eleuthero', vibrationalSignature: 'Endurance Code', type: 'Adaptogen', benefit: 'Eleutherosides for immune modulation and stamina.', color: '#166534' },
  { id: 'adaptogen-schisandra', name: 'Schisandra', vibrationalSignature: 'Five-Element Balancer', type: 'Adaptogen', benefit: 'Lignans for liver detox, stress adaptation and longevity.', color: '#be123c' },
  { id: 'adaptogen-morinda', name: 'Morinda (Noni Root)', vibrationalSignature: 'Jing Tonifier', type: 'Adaptogen', benefit: 'Kidney jing restoration and anti-aging adaptogen.', color: '#fbbf24' },
  { id: 'adaptogen-gynostemma', name: 'Gynostemma', vibrationalSignature: 'AMPK Activator', type: 'Adaptogen', benefit: 'Gypenosides activating AMPK — longevity pathway.', color: '#4ade80' },
];

export const ACTIVATIONS: Activation[] = BASE_ACTIVATIONS;

export const PLANETARY_DATA: Record<number, { planet: string; herb: string }> = {
  0: { planet: 'Sun (Surya)', herb: 'Saffron, Calamus, Ginger' },
  1: { planet: 'Moon (Chandra)', herb: 'Ashwagandha, Blue Lotus, Shatavari' },
  2: { planet: 'Mars (Mangala)', herb: 'Nettle, Maca, Guduchi' },
  3: { planet: 'Mercury (Budha)', herb: 'Brahmi, Gotu Kola, Tulsi' },
  4: { planet: 'Jupiter (Guru)', herb: 'Turmeric, Ginseng' },
  5: { planet: 'Venus (Shukra)', herb: 'Rose, Bobinsana' },
  6: { planet: 'Saturn (Shani)', herb: 'Shilajit, Triphala, Myrrh' },
};
