import { Activation } from './types';

export const ACTIVATIONS: Activation[] = [
  // Sacred Plants (Trip-less)
  { id: 'ayahuasca-essence', name: 'The Grandmother Presence', vibrationalSignature: 'Heart/Ancestral', type: 'Sacred Plant', benefit: 'Ancestral healing and deep heart-opening.', color: '#4ade80' },
  { id: 'psilocybin-frequency', name: 'The Neural Teacher', vibrationalSignature: 'Mind/Plasticity', type: 'Sacred Plant', benefit: 'Dissolving ego-walls and creative neural rewiring.', color: '#60a5fa' },
  { id: 'sativa-spark', name: 'The Sativa Spark', vibrationalSignature: 'Vision/Creativity', type: 'Sacred Plant', benefit: 'High-vibe focus and 3rd eye activation.', color: '#facc15' },
  { id: 'blue-lotus-weaver', name: 'Third-Eye Decalcifier (Blue Lotus)', vibrationalSignature: 'The Dream Weaver / Intuition', type: 'Sacred Plant', benefit: 'Lucid intuition and spiritual serenity.', color: '#818cf8' },
  { id: 'mugwort-navigator', name: 'Astral Navigator (Mugwort)', vibrationalSignature: 'Astral Travel', type: 'Sacred Plant', benefit: 'Lucid dreaming and astral navigation.', color: '#94a3b8' },
  { id: 'eyebright-spark', name: 'Clairvoyant Spark (Eyebright)', vibrationalSignature: 'Clairvoyance', type: 'Sacred Plant', benefit: 'Sharpening spiritual sight and inner vision.', color: '#fef08a' },
  { id: 'calea-oracle', name: 'Dream Oracle (Calea Zacatechichi)', vibrationalSignature: 'Dream State', type: 'Sacred Plant', benefit: 'Intensifying dream recall and prophetic clarity.', color: '#c084fc' },
  { id: 'dream-root-channel', name: 'Ancestral Channel (African Dream Root)', vibrationalSignature: 'Ancestral Link', type: 'Sacred Plant', benefit: 'Connecting with lineage through the dream-field.', color: '#fb923c' },
  { id: 'star-anise-divination', name: 'Divination Resonance (Star Anise)', vibrationalSignature: 'Divination', type: 'Sacred Plant', benefit: 'Opening the gates of prophecy and foresight.', color: '#fde047' },
  { id: 'wormwood-mirror', name: 'The Spirit Mirror (Wormwood)', vibrationalSignature: 'Psychic Shield', type: 'Sacred Plant', benefit: 'Reflecting low-vibrational static and psychic shielding.', color: '#4d7c0f' },
  { id: 'bobinsana-heart', name: 'Mermaid Heart (Bobinsana)', vibrationalSignature: 'Water/Heart', type: 'Sacred Plant', benefit: 'Softening the heart-matrix and emotional healing.', color: '#f472b6' },
  { id: 'san-pedro-resonance', name: 'San Pedro Resonance', vibrationalSignature: 'The Sky Father / Sky', type: 'Sacred Plant', benefit: 'Masculine stability and expansive perspective.', color: '#fb923c' },
  { id: 'iboga-protocol', name: 'Iboga Protocol', vibrationalSignature: 'The Truth Mirror / Soul', type: 'Sacred Plant', benefit: 'Subconscious de-fragmentation and pattern clearing.', color: '#f87171' },
  { id: 'peyote-spirit', name: 'Peyote Spirit', vibrationalSignature: 'The Earth Spirit / Earth', type: 'Sacred Plant', benefit: 'Ancient grounding and desert heartbeat connection.', color: '#b45309' },
  { id: 'amanita-bridge', name: 'Amanita Bridge', vibrationalSignature: 'The Cosmic Bridge / Cosmos', type: 'Sacred Plant', benefit: 'Balancing dream and waking worlds.', color: '#fca5a5' },

  // Siddha Soma Quantum-Coded
  { id: 'shilajit-grounding', name: 'Primordial Earth Grounding', vibrationalSignature: 'Shilajit Resonance', type: 'Siddha Soma', benefit: 'Deep cellular grounding and fulvic integrity.', color: '#451a03' },
  { id: 'magnesium-sync', name: 'Neural Calm Sync', vibrationalSignature: 'Magnesium L-Threonate', type: 'Siddha Soma', benefit: 'Synaptic coolant and nervous system rest.', color: '#a78bfa' },
  { id: 'glutathione-purity', name: 'Biofield Purification', vibrationalSignature: 'Glutathione', type: 'Siddha Soma', benefit: 'Biofield purification and detox resonance.', color: '#ccfbf1' },
  { id: 'd3k2-integrity', name: 'Structural Light Integrity', vibrationalSignature: 'D3 + K2 + CoQ10', type: 'Siddha Soma', benefit: 'Bone-light density and solar resonance.', color: '#fef3c7' },
  { id: 'parax-flush', name: 'Parasitic Frequency Eraser', vibrationalSignature: 'ParaX Code', type: 'Siddha Soma', benefit: 'Erasing parasitic energetic signatures.', color: '#b91c1c' },
  { id: 'sleep-harmonic', name: 'Deep Sleep Harmonic', vibrationalSignature: 'Sleep Blend', type: 'Siddha Soma', benefit: 'Zero-point rest and astral travel stability.', color: '#1e1b4b' },
  { id: 'nmn-longevity', name: 'NMN Cellular Battery', vibrationalSignature: 'NMN Resonance', type: 'Siddha Soma', benefit: 'Mitochondrial recharge and NAD+ optimization.', color: '#3b82f6' },
  { id: 'b12-joy', name: 'Synaptic Joy Transmission', vibrationalSignature: 'B12 + B6', type: 'Siddha Soma', benefit: 'Mitochondrial fire and emotional uplift.', color: '#f472b6' },
  { id: 'zinc-defense', name: 'Zinc Shielding', vibrationalSignature: 'Zinc Resonance', type: 'Siddha Soma', benefit: 'Systemic defense and DNA integrity.', color: '#94a3b8' },
  { id: 'probiotic-resonance', name: 'Microbiome Harmony', vibrationalSignature: 'Probiotic Code', type: 'Siddha Soma', benefit: 'Gut-brain axis alignment and internal peace.', color: '#10b981' },
  { id: 'longevity-matrix', name: 'Longevity Matrix', vibrationalSignature: 'Longevity Blend', type: 'Siddha Soma', benefit: 'Telomere protection and biological age reversal.', color: '#8b5cf6' },
  { id: 'vitc-radiance', name: 'Solar Immune Radiance', vibrationalSignature: 'Vitamin C', type: 'Siddha Soma', benefit: 'High-frequency immune fortification.', color: '#fbbf24' },
  { id: 'charcoal-detox', name: 'Shadow Detox Matrix', vibrationalSignature: 'Activated Charcoal', type: 'Siddha Soma', benefit: 'Vacuuming low-vibrational environmental static.', color: '#1f2937' },
  { id: 'adrenal-equilibrium', name: 'Equilibrium Mastery', vibrationalSignature: 'Adrenal Tonic', type: 'Siddha Soma', benefit: 'Stress-field stabilization and flux control.', color: '#84cc16' },
  { id: 'omega-intuition', name: 'Crystalline Thought Flow', vibrationalSignature: 'Omega DHA + EPA', type: 'Siddha Soma', benefit: 'Fluid intuition and synaptic super-structure.', color: '#0ea5e9' },
  { id: 'colostrum-source', name: 'Original Source Nourishment', vibrationalSignature: 'Colostrum', type: 'Siddha Soma', benefit: 'Immune memory and blueprint restoration.', color: '#f5f5f4' },
  { id: 'creatine-density', name: 'Volumetric Presence', vibrationalSignature: 'Creatine', type: 'Siddha Soma', benefit: 'Manifestation density and physical grounding.', color: '#64748b' },
  { id: 'iodine-beacon', name: 'Thyroid Resonance Beacon', vibrationalSignature: 'Liquid Iodine', type: 'Siddha Soma', benefit: 'Metabolic fire and glandular clarity.', color: '#4c1d95' },
  { id: 'hydration-memory', name: 'Molecular Hydration Lock', vibrationalSignature: 'Pure Hydration', type: 'Siddha Soma', benefit: 'Crystalline water memory and cellular flow.', color: '#38bdf8' },
  { id: 'focus-fire', name: 'Cognitive Fire', vibrationalSignature: 'Focus Blend', type: 'Siddha Soma', benefit: 'Laser-point consciousness and mental drive.', color: '#ea580c' },

  // Young Living (Ethereal Blends)
  { id: 'yl-abundance', name: 'Infinite Manifestation Stream', vibrationalSignature: 'Abundance Resonance', type: 'Essential Oil', benefit: 'Shifting scarcity to source-wealth resonance.', color: '#d97706' },
  { id: 'yl-valor', name: 'Crystalline Sovereignty', vibrationalSignature: 'Valor Resonance', type: 'Essential Oil', benefit: 'Spinal alignment and unwavering courage.', color: '#1d4ed8' },
  { id: 'yl-thieves', name: 'Ethereal Shielding', vibrationalSignature: 'Thieves Resonance', type: 'Essential Oil', benefit: 'Auric field cleansing and bio-defense.', color: '#991b1b' },
  { id: 'yl-joy', name: 'Heart-Bloom Radiance', vibrationalSignature: 'Joy Resonance', type: 'Essential Oil', benefit: 'Grief release and magnetic heart expansion.', color: '#ec4899' },
  { id: 'yl-release', name: 'Ancestral Tether Dissolve', vibrationalSignature: 'Release Resonance', type: 'Essential Oil', benefit: 'Breaking lineage and past-life trauma chains.', color: '#4b5563' },
  { id: 'yl-potential', name: 'Future-Self Convergence', vibrationalSignature: 'Highest Potential', type: 'Essential Oil', benefit: 'Entanglement with your highest timeline.', color: '#7c3aed' },
  { id: 'yl-brain', name: 'Cognitive Super-Structure', vibrationalSignature: 'Brain Power', type: 'Essential Oil', benefit: 'High-definition mental field sharpening.', color: '#2563eb' },
  { id: 'yl-peace', name: 'Starlight Stillness', vibrationalSignature: 'Peace & Calming', type: 'Essential Oil', benefit: 'Theta-state peace and nervous system descent.', color: '#2dd4bf' },
  { id: 'yl-angelica', name: 'Guardian Light Matrix', vibrationalSignature: 'White Angelica', type: 'Essential Oil', benefit: 'One-way energetic protection filter.', color: '#f8fafc' },

  // doTERRA (Bio-Symphonies)
  { id: 'dt-onguard', name: 'Systemic Fortification', vibrationalSignature: 'On Guard Resonance', type: 'Essential Oil', benefit: 'Reinforcing biological and energetic boundaries.', color: '#c2410c' },
  { id: 'dt-balance', name: 'Core Gravity Alignment', vibrationalSignature: 'Balance Resonance', type: 'Essential Oil', benefit: "Grounding into the Earth's Schumann resonance.", color: '#065f46' },
  { id: 'dt-adaptiv', name: 'Neural Fluidity Protocol', vibrationalSignature: 'Adaptiv Resonance', type: 'Essential Oil', benefit: 'Calmness in high-intensity shifts.', color: '#0e7490' },
  { id: 'dt-deepblue', name: 'Somatic Release Wave', vibrationalSignature: 'Deep Blue Resonance', type: 'Essential Oil', benefit: 'Flushing pain memory from muscle-consciousness.', color: '#1e40af' },
  { id: 'dt-serenity', name: 'Celestial Drift', vibrationalSignature: 'Serenity Resonance', type: 'Essential Oil', benefit: 'Zero-point state for total rest and reset.', color: '#6d28d9' },
  { id: 'dt-pasttense', name: 'Temporal Ease', vibrationalSignature: 'PastTense Resonance', type: 'Essential Oil', benefit: 'Dissolving the pressure of time and tension.', color: '#0369a1' },
  { id: 'dt-intune', name: 'Single-Point Focus', vibrationalSignature: 'InTune Resonance', type: 'Essential Oil', benefit: 'Locking consciousness into the Present Moment.', color: '#15803d' },
  { id: 'dt-metapwr', name: 'Metabolic Light Ignition', vibrationalSignature: 'MetaPWR Resonance', type: 'Essential Oil', benefit: 'Converting light into cellular energy.', color: '#f97316' },

  // Ayurvedic Herbs & Global Healing
  { id: 'ashwagandha-resonance', name: 'Ashwagandha Resonance', vibrationalSignature: 'Vitality Integrity', type: 'Ayurvedic Herb', benefit: 'Adaptogenic grounding and nervous system resilience.', color: '#d97706' },
  { id: 'brahmi-code', name: 'Brahmi Code', vibrationalSignature: 'Cognitive Clarity', type: 'Ayurvedic Herb', benefit: 'Enhanced focus, memory, and spiritual awareness.', color: '#059669' },
  { id: 'shatavari-flow', name: 'Shatavari Flow', vibrationalSignature: 'Divine Feminine', type: 'Ayurvedic Herb', benefit: 'Hormonal balance and emotional fluidity.', color: '#db2777' },
  { id: 'turmeric-radiance', name: 'Turmeric Radiance', vibrationalSignature: 'Golden Protection', type: 'Ayurvedic Herb', benefit: 'Anti-inflammatory light and aura purification.', color: '#fbbf24' },
  { id: 'tulsi-protector', name: 'Aura Sanitizer (Tulsi)', vibrationalSignature: 'Devotional Protector', type: 'Ayurvedic Herb', benefit: 'Auric shielding and devotional heart clarity.', color: '#166534' },
  { id: 'triphala-integrity', name: 'Triphala Integrity', vibrationalSignature: 'Trinity Harmonizer', type: 'Ayurvedic Herb', benefit: 'Systemic balance and structural integrity.', color: '#713f12' },
  { id: 'guduchi-immortal', name: 'The Amrit Nectar (Guduchi)', vibrationalSignature: 'Immortal Resonance', type: 'Ayurvedic Herb', benefit: 'Immune immortality and cellular longevity.', color: '#facc15' },
  { id: 'uva-ursi-anchor', name: 'The Earth Anchor (Uva Ursi)', vibrationalSignature: 'Stabilization', type: 'Ayurvedic Herb', benefit: 'Deep stabilization and energetic anchoring.', color: '#166534' },
  { id: 'mandukaparni-structure', name: 'Cognitive Super-Structure (Mandukaparni)', vibrationalSignature: 'Neural Architecture', type: 'Ayurvedic Herb', benefit: 'Building resilient cognitive pathways.', color: '#22c55e' },
  { id: 'ginseng-igniter', name: 'Vitality Igniter (Ginseng)', vibrationalSignature: 'Fire/Life', type: 'Ayurvedic Herb', benefit: 'Igniting the inner fire and life-force energy.', color: '#ef4444' },
  { id: 'elderberry-guardian', name: 'Guardian of Thresholds (Elderberry)', vibrationalSignature: 'Immune Shield', type: 'Ayurvedic Herb', benefit: 'Protecting the gates of the biological temple.', color: '#4c1d95' },
  { id: 'chamomile-peace', name: 'Peace Teacher (Chamomile)', vibrationalSignature: 'Serenity', type: 'Ayurvedic Herb', benefit: 'Gentle nervous system teaching and peace.', color: '#fef08a' },
  { id: 'neem-truth', name: 'Neem Bitter Truth', vibrationalSignature: 'Detox Integrity', type: 'Ayurvedic Herb', benefit: 'Deep blood purification and shadow detox.', color: '#064e3b' },
  { id: 'gotu-kola-synapse', name: 'Gotu Kola Synapse', vibrationalSignature: 'Neural Repair', type: 'Ayurvedic Herb', benefit: 'Repairing the synaptic bridges of the mind.', color: '#10b981' },
  { id: 'maca-fire', name: 'Maca Fire Resonance', vibrationalSignature: 'Vitality/Drive', type: 'Ayurvedic Herb', benefit: 'Igniting the primordial drive and stamina.', color: '#f97316' },
  { id: 'nettle-fortress', name: 'Nettle Fortress', vibrationalSignature: 'Strength/Blood', type: 'Ayurvedic Herb', benefit: 'Fortifying the blood-matrix and energetic boundaries.', color: '#15803d' },
  { id: 'rose-bloom', name: 'Rose Heart Bloom', vibrationalSignature: 'Love/Frequency', type: 'Ayurvedic Herb', benefit: 'Opening the heart-gate to the frequency of pure love.', color: '#f472b6' },
  { id: 'myrrh-structure', name: 'Myrrh Structural Integrity', vibrationalSignature: 'Ancient Structure', type: 'Ayurvedic Herb', benefit: 'Reinforcing the ancient structural codes of the body.', color: '#78350f' },
];

export const PLANETARY_DATA: Record<number, { planet: string; herb: string }> = {
  0: { planet: 'Sun (Surya)', herb: 'Saffron, Calamus, Ginger' },
  1: { planet: 'Moon (Chandra)', herb: 'Ashwagandha, Blue Lotus, Shatavari' },
  2: { planet: 'Mars (Mangala)', herb: 'Nettle, Maca, Guduchi' },
  3: { planet: 'Mercury (Budha)', herb: 'Brahmi, Gotu Kola, Tulsi' },
  4: { planet: 'Jupiter (Guru)', herb: 'Turmeric, Ginseng' },
  5: { planet: 'Venus (Shukra)', herb: 'Rose, Bobinsana' },
  6: { planet: 'Saturn (Shani)', herb: 'Shilajit, Triphala, Myrrh' },
};
