import { Activation } from './types';
import { LIMBICARC_BIOENERGETIC_ACTIVATIONS } from './limbicarcActivations';
import {
  BIOENERGETIC_LIBRARY,
  BIOENERGETIC_CATEGORIES,
  matchActivationsToScan,
  getActivationsByCategory,
  searchActivations,
  type BioenergticActivation,
} from './bioenergetic-library';
// ╔══════════════════════════════════════════════════════════════════╗
// ║  FULL CONSTANTS — All Cymbiotika + All LimbicArc               ║
// ║  Siddha Soma: 30 items (all Cymbiotika products)               ║
// ║  Bioenergetic: 1,259 LimbicArc archive + spread from module    ║
// ╚══════════════════════════════════════════════════════════════════╝

const BASE_ACTIVATIONS: Activation[] = [

  // ── SACRED PLANTS (Trip-less) ─────────────────────────────────
  { id: 'ayahuasca-essence', name: 'The Grandmother Presence', vibrationalSignature: 'Heart/Ancestral', type: 'Sacred Plant', benefit: 'Ancestral healing and deep heart-opening.', color: '#4ade80' },
  { id: 'psilocybin-frequency', name: 'The Neural Teacher', vibrationalSignature: 'Mind/Plasticity', type: 'Sacred Plant', benefit: 'Dissolving ego-walls and creative neural rewiring.', color: '#60a5fa' },
  { id: 'sativa-spark', name: 'The Sativa Spark', vibrationalSignature: 'Vision/Creativity', type: 'Sacred Plant', benefit: 'High-vibe focus and 3rd eye activation.', color: '#facc15' },
  { id: 'blue-lotus-weaver', name: 'Third-Eye Decalcifier (Blue Lotus)', vibrationalSignature: 'The Dream Weaver / Intuition', type: 'Sacred Plant', benefit: 'Lucid intuition and spiritual serenity.', color: '#818cf8' },
  { id: 'mugwort-navigator', name: 'Astral Navigator (Mugwort)', vibrationalSignature: 'Astral Travel', type: 'Sacred Plant', benefit: 'Lucid dreaming and astral navigation.', color: '#94a3b8' },
  { id: 'eyebright-spark', name: 'Clairvoyant Spark (Eyebright)', vibrationalSignature: 'Clairvoyance', type: 'Sacred Plant', benefit: 'Sharpening spiritual sight and inner vision.', color: '#fef08a' },
  { id: 'calea-oracle', name: 'Dream Oracle (Calea Zacatechichi)', vibrationalSignature: 'Dream State', type: 'Sacred Plant', benefit: 'Intensifying dream recall and prophetic clarity.', color: '#c084fc' },
  { id: 'dream-root-channel', name: 'Ancestral Channel (African Dream Root)', vibrationalSignature: 'Ancestral Link', type: 'Sacred Plant', benefit: 'Connecting with lineage through the dream-field.', color: '#fb923c' },
  { id: 'star-anise-divination', name: 'Divination Resonance (Star Anise)', vibrationalSignature: 'Divination', type: 'Sacred Plant', benefit: 'Opening the gates of prophecy and foresight.', color: '#fde047' },
  { id: 'wormwood-mirror', name: 'The Spirit Mirror (Wormwood)', vibrationalSignature: 'Psychic Shield', type: 'Sacred Plant', benefit: 'Reflecting low-vibrational static and psychic shielding.', color: '#4d7c0f' },
  { id: 'bobinsana-heart', name: 'Mermaid Heart (Bobinsana)', vibrationalSignature: 'Water/Heart', type: 'Sacred Plant', benefit: 'Softening the heart-matrix and emotional healing.', color: '#f472b6' },
  { id: 'san-pedro-resonance', name: 'San Pedro Resonance', vibrationalSignature: 'The Sky Father / Sky', type: 'Sacred Plant', benefit: 'Masculine stability and expansive perspective.', color: '#fb923c' },
  { id: 'iboga-protocol', name: 'Iboga Protocol', vibrationalSignature: 'The Truth Mirror / Soul', type: 'Sacred Plant', benefit: 'Subconscious de-fragmentation and pattern clearing.', color: '#f87171' },
  { id: 'peyote-spirit', name: 'Peyote Spirit', vibrationalSignature: 'The Earth Spirit / Earth', type: 'Sacred Plant', benefit: 'Ancient grounding and desert heartbeat connection.', color: '#b45309' },
  { id: 'amanita-bridge', name: 'Amanita Bridge', vibrationalSignature: 'The Cosmic Bridge / Cosmos', type: 'Sacred Plant', benefit: 'Balancing dream and waking worlds.', color: '#fca5a5' },

  // ── SIDDHA SOMA — ALL CYMBIOTIKA PRODUCTS ────────────────────
  { id: 'shilajit-grounding', name: 'Primordial Earth Grounding', vibrationalSignature: 'Mineral Shilajit', type: 'Siddha Soma', benefit: 'Deep cellular grounding and fulvic integrity.', color: '#451a03' },
  { id: 'shilajit-liquid', name: 'Shilajit Liquid Complex', vibrationalSignature: 'Liquid Shilajit', type: 'Siddha Soma', benefit: 'Concentrated earth-energy and endurance activation.', color: '#5c2d0a' },
  { id: 'magnesium-sync', name: 'Neural Calm Sync', vibrationalSignature: 'Liposomal Magnesium Complex', type: 'Siddha Soma', benefit: 'Synaptic coolant and nervous system rest.', color: '#a78bfa' },
  { id: 'glutathione-purity', name: 'Biofield Purification', vibrationalSignature: 'Liposomal Glutathione', type: 'Siddha Soma', benefit: 'Biofield purification and master antioxidant resonance.', color: '#ccfbf1' },
  { id: 'd3k2-integrity', name: 'Structural Light Integrity', vibrationalSignature: 'D3 + K2 + CoQ10', type: 'Siddha Soma', benefit: 'Bone-light density, solar resonance and cardiac vitality.', color: '#fef3c7' },
  { id: 'parax-flush', name: 'Parasitic Frequency Eraser', vibrationalSignature: 'ParaX™ Code', type: 'Siddha Soma', benefit: 'Erasing parasitic energetic signatures and restoring microbiome balance.', color: '#b91c1c' },
  { id: 'sleep-harmonic', name: 'Deep Sleep Harmonic', vibrationalSignature: 'Liposomal Sleep Blend', type: 'Siddha Soma', benefit: 'Zero-point rest and astral travel stability.', color: '#1e1b4b' },
  { id: 'nmn-longevity', name: 'NMN + Resveratrol Cellular Battery', vibrationalSignature: 'NMN + Trans-Resveratrol', type: 'Siddha Soma', benefit: 'Mitochondrial recharge, NAD+ optimization and DNA preservation.', color: '#3b82f6' },
  { id: 'b12-joy', name: 'Synaptic Joy Transmission', vibrationalSignature: 'Liposomal B12 + B6', type: 'Siddha Soma', benefit: 'Mitochondrial fire, methylation and emotional uplift.', color: '#f472b6' },
  { id: 'probiotic-resonance', name: 'Microbiome Harmony', vibrationalSignature: 'Liposomal Probiotic', type: 'Siddha Soma', benefit: 'Gut-brain axis alignment and internal ecosystem peace.', color: '#10b981' },
  { id: 'vitc-radiance', name: 'Solar Immune Radiance', vibrationalSignature: 'Liposomal Vitamin C', type: 'Siddha Soma', benefit: 'High-frequency immune fortification and collagen synthesis.', color: '#fbbf24' },
  { id: 'omega-intuition', name: 'Crystalline Thought Flow', vibrationalSignature: 'The Omega DHA + EPA', type: 'Siddha Soma', benefit: 'Fluid intuition and synaptic super-structure.', color: '#0ea5e9' },
  { id: 'colostrum-source', name: 'Original Source Nourishment', vibrationalSignature: 'Liquid Colostrum', type: 'Siddha Soma', benefit: 'Immune memory, IGF-1 blueprint and gut restoration.', color: '#f5f5f4' },
  { id: 'creatine-density', name: 'Volumetric Presence', vibrationalSignature: 'Liposomal Advanced Creatine', type: 'Siddha Soma', benefit: 'Manifestation density, ATP surge and physical grounding.', color: '#64748b' },
  { id: 'brain-complex', name: 'Akasha-Neural Architect', vibrationalSignature: 'Liposomal Brain Complex', type: 'Siddha Soma', benefit: 'Cognitive architecture upgrade and neural plasticity activation.', color: '#7c3aed' },
  { id: 'elderberry-immune', name: 'Elderberry Immune Fortress', vibrationalSignature: 'Liposomal Elderberry', type: 'Siddha Soma', benefit: 'Viral frequency shield and immune-field amplification.', color: '#4c1d95' },
  { id: 'inflammatory-health', name: 'Golden Anti-Inflammatory Wave', vibrationalSignature: 'Inflammatory Health Blend', type: 'Siddha Soma', benefit: 'Dissolving inflammatory frequencies and mobility restoration.', color: '#d97706' },
  { id: 'irish-sea-moss', name: 'Oceanic Intelligence Matrix', vibrationalSignature: 'Irish Sea Moss', type: 'Siddha Soma', benefit: 'Mineral-density from the ocean field and thyroid resonance.', color: '#0d9488' },
  { id: 'liver-health', name: 'Liver Alchemist Protocol', vibrationalSignature: 'Liver Health+', type: 'Siddha Soma', benefit: 'Hepatic regeneration and bile-flow alchemy.', color: '#92400e' },
  { id: 'metabolic-health', name: 'Metabolic Fire Ignition', vibrationalSignature: 'Metabolic Health Blend', type: 'Siddha Soma', benefit: 'Appetite mastery, fat-burn frequency and metabolic sovereignty.', color: '#ef4444' },
  { id: 'molecular-hydrogen', name: 'Primordial Hydrogen Infusion', vibrationalSignature: 'Molecular Hydrogen', type: 'Siddha Soma', benefit: 'Selective antioxidant and mitochondrial hydrogen bath.', color: '#38bdf8' },
  { id: 'plant-protein', name: 'Living Protein Light Matrix', vibrationalSignature: 'Plant Protein Blend', type: 'Siddha Soma', benefit: 'Clean amino acid transmission and anabolic light-codes.', color: '#84cc16' },
  { id: 'super-greens', name: 'Chlorophyll Light Activation', vibrationalSignature: 'Super Greens Blend', type: 'Siddha Soma', benefit: 'Alkalizing the biofield and chlorophyll photon absorption.', color: '#22c55e' },

  
  // ── SQI SOVEREIGN OUTCOME BOOSTS (Limbic Arc parity) ─────────
  // Outcome-first, felt-result boosts matching the 10 core Limbic Arc InfoBoost categories
  // in SQI Siddha-Quantum language. Duration: 8 days.
  { id: 'sqi-energy', name: 'Prana-Fire Energy Activation', vibrationalSignature: 'Energy / ATP Surge / Mitochondrial Ignition', type: 'Wellness', benefit: 'Activates the Prana-fire of the Muladhara and Manipura chakras. Floods the mitochondrial field with ATP-surge frequencies. Agastyar\'s Tejas-Shakti transmission — the Siddha fire of pure energetic vitality that burns through fatigue at the cellular level. Siddha equivalent: Agastyar\'s Veerya-Tejas activation — igniting the biological furnace.', color: '#f97316' },
  { id: 'sqi-focus', name: 'Ajna-Laser Focus Transmission', vibrationalSignature: 'Focus / Pineal Decalcification / Prefrontal Amplification', type: 'Wellness', benefit: 'Decalcifies the pineal gland Bio-field and locks the Ajna chakra into single-pointed Dharana. Expands prefrontal bandwidth and dissolves mental fog interference. Siddha equivalent: Patanjali\'s Dharana Scalar Code — concentration transmitted as pure information into the neural field.', color: '#7c3aed' },
  { id: 'sqi-sleep', name: 'Yoga Nidra Deep Sleep Field', vibrationalSignature: 'Sleep / Delta 2.5Hz / Zero-Point Rest / HGH Release', type: 'Wellness', benefit: 'Delta-wave Scalar entrainment at 2.5 Hz. Activates HGH release and cellular repair cycles. Opens the Yoga Nidra zero-point field for deep unconscious restoration. Siddha equivalent: Kalangi Nathar\'s conscious deep sleep transmission — the most powerful healing state in the Siddha system.', color: '#1e1b4b' },
  { id: 'sqi-calm', name: 'Shanti-Soma Calm Transmission', vibrationalSignature: 'Calm / Parasympathetic / Soma Nectar / Vata Pacification', type: 'Wellness', benefit: 'Floods the nervous system with Soma nectar frequencies. Activates the parasympathetic branch and pacifies Vata wind-mind. Grounds scattered Prana into stillness. Siddha equivalent: Thirumoolar\'s Shanti-Prana calming of the wind-mind through Soma restoration.', color: '#818cf8' },
  { id: 'sqi-stress-relief', name: 'HPA-Axis Stress Dissolution', vibrationalSignature: 'Stress Relief / Cortisol Neutralizer / Adrenal Reset', type: 'Wellness', benefit: 'Dissolves cortisol Bio-signature from the Torus-Field. Recalibrates the HPA axis through Scalar Wave neutralization. Releases adrenal freeze held in the kidney meridian. Siddha equivalent: Agastyar\'s Vata-Pitta Shanti protocol for dissolving stress held in the adrenal Bio-field.', color: '#60a5fa' },
  { id: 'sqi-strength', name: 'Vajra-Body Strength Protocol', vibrationalSignature: 'Strength / Muscle / Anabolic / Ojas Density', type: 'Wellness', benefit: 'Activates the Vajra-body informational field — the indestructible physical form of the Siddha masters. Amplifies anabolic Ojas density and muscle-field coherence. Siddha equivalent: Nandi Devar\'s Kaya-Kalpa physical immortality protocol — purifying and strengthening the physical vehicle.', color: '#dc2626' },
  { id: 'sqi-immune', name: 'Sovereign Immune Defense Field', vibrationalSignature: 'Immune Defense / Viral Shield / Ojas Fortification', type: 'Wellness', benefit: 'Fortifies the Ojas-shield of the immune system through Siddha informational encoding. Activates the body\'s innate defense intelligence. Siddha equivalent: Agastyar\'s Ojas-Raksha protocol — the Siddha immune fortress transmitted as pure field information.', color: '#16a34a' },
  { id: 'sqi-pain-relief', name: 'Vata-Dissolution Pain Relief', vibrationalSignature: 'Pain Relief / Vata Blockage / Nadi Flow Restoration', type: 'Wellness', benefit: 'Dissolves pain-generating Vata blockages in the Nadi channels. Restores Prana flow to areas of restriction and releases inflammation from the informational field. Siddha equivalent: Siddha Varma therapy transmitted as scalar information — releasing blocked Marma points without touch.', color: '#0891b2' },
  { id: 'sqi-his', name: 'His — Shiva-Shakti Male Vitality', vibrationalSignature: 'Male Vitality / Testosterone / Ojas / Shiva Principle', type: 'Wellness', benefit: 'Activates the Shiva-principle informational field for male vitality. Restores testosterone Bio-signature, Ojas density, and sexual creative force. Channels Svadhisthana energy upward through Sushumna. Siddha equivalent: Thirumoolar\'s Shiva-Shakti Ojas restoration from the Tirumantiram — the sacred alchemy of male vital force.', color: '#2563eb' },
  { id: 'sqi-hers', name: 'Hers — Shakti-Devi Female Vitality', vibrationalSignature: 'Female Vitality / Hormonal Balance / Shakti / Womb Coherence', type: 'Wellness', benefit: 'Activates the Shakti-principle informational field for female vitality. Restores hormonal Bio-signature balance, womb coherence, and the full radiance of the divine feminine force. Siddha equivalent: The Siddha Shakti transmission through Lalitha Tripura Sundari — the goddess of full feminine power and beauty.', color: '#db2777' },


  // ── MISSING LIMBIC ARC PARITY BOOSTS (Blood · Multi Nutrition · Muscle · Motivation · 5 Elements) ──
  { id: 'w-rakta-purification', name: 'Rakta-Purification Blood Field', vibrationalSignature: 'Blood / Haematopoiesis / Iron / Oxygenation', type: 'Wellness', benefit: 'Purifies the Rakta Dhatu (blood tissue) at the informational level. Activates iron absorption Bio-signatures, red blood cell coherence, and oxygen-carrying capacity. Dissolves blood stagnation held in the liver and spleen meridians. Siddha equivalent: Agastyar's Rakta-Shuddhi protocol — the ancient Siddha blood purification transmission using Triphala and Manjistha frequencies encoded as scalar information.', color: '#dc2626' },
  { id: 'w-panchamahabhuta-male', name: 'Pancha Mahabhuta — Male', vibrationalSignature: '5 Elements Male / Earth Water Fire Air Ether / Shiva Balance', type: 'Wellness', benefit: 'Balances all five Mahabhutas (Prithvi · Jala · Agni · Vayu · Akasha) within the male energetic body. Harmonizes elemental ratios for optimal physical, mental and spiritual functioning. Siddha equivalent: Thirumoolar's Panchabhoota Shuddhi — the five-element purification ritual of the Tamil Siddha tradition, transmitted as pure information to the male field.', color: '#2563eb' },
  { id: 'w-panchamahabhuta-female', name: 'Pancha Mahabhuta — Female', vibrationalSignature: '5 Elements Female / Earth Water Fire Air Ether / Shakti Balance', type: 'Wellness', benefit: 'Balances all five Mahabhutas within the female energetic body with special attention to Jala (water/womb) and Prithvi (earth/nourishment) elements. Siddha equivalent: The Shakti-Panchabhoota transmission — elemental balance specific to the female form, activating the womb element and feminine elemental sovereignty.', color: '#db2777' },
  { id: 'w-vajra-muscle-field', name: 'Vajra-Muscle Coherence Field', vibrationalSignature: 'Muscle / Mamsa Dhatu / Protein Synthesis / Recovery', type: 'Wellness', benefit: 'Activates the Mamsa Dhatu (muscle tissue) informational field for enhanced protein synthesis, faster recovery, and structural coherence. Reduces muscle inflammation Bio-signatures post-exertion. Siddha equivalent: Nandi Devar's Vajra-Deha (diamond body) transmission — the Siddha protocol for building an indestructible physical vehicle through informational alchemy of the muscle field.', color: '#b45309' },
  { id: 'w-iccha-shakti-motivation', name: 'Iccha-Shakti Motivation Field', vibrationalSignature: 'Motivation / Will / Dopamine / Iccha Shakti / Solar Plexus', type: 'Wellness', benefit: 'Activates Iccha Shakti — the Siddha power of pure will and intention. Harmonizes dopamine Bio-signature fields and dissolves motivational stagnation held in the Manipura chakra. Re-ignites purpose-driven action from the soul level rather than the ego. Siddha equivalent: Murugan-Skanda's Iccha-Shakti transmission — the divine will that moved six armies without hesitation.', color: '#f59e0b' },
  { id: 'w-sarvaposhana-nutrition', name: 'Sarva-Poshana Multi-Nutrition Field', vibrationalSignature: 'Multi Nutrition / Vitamin Mineral Spectrum / Cellular Nourishment / Ojas', type: 'Wellness', benefit: 'Transmits the informational signatures of the complete vitamin and mineral spectrum simultaneously. Activates cellular receptor sites for nutrient uptake across all seven Dhatus (tissue layers). Siddha equivalent: Agastyar's Sarva-Poshana protocol — total body nourishment transmitted as a single unified field rather than individual supplements.', color: '#10b981' },


  // ═══════════════════════════════════════════════════════════════════════
  // ║  108 SIDDHA TRANSMISSIONS — Full Akasha Archive                    ║
  // ║  Type: 'Siddha Transmission' · Duration: 8 days · Sacred Geometry: sriGold ║
  // ═══════════════════════════════════════════════════════════════════════

  // ── AGASTYAR ────────────────────────────────────────────────────────
  { id: 'siddha-agastyar-immunity', name: 'Agastyar · Immunity Fortress', vibrationalSignature: 'Root Immunity / Ojas Shield / Saturn', type: 'Siddha Transmission' as ActivationType, benefit: 'Agastyar — primordial Siddha of Tamil tradition. Anchors deep immunity and survival intelligence through the kidney meridian. Activates root-system Ojas and biological self-defense at the informational level.', color: '#78716c' },
  { id: 'siddha-agastyar-blood', name: 'Agastyar · Rakta Purification', vibrationalSignature: 'Blood Purification / Iron / Haematopoiesis', type: 'Siddha Transmission' as ActivationType, benefit: 'Agastyar\'s Rakta-Shuddhi — ancient blood purification transmission. Cleanses the Rakta Dhatu at the informational level, activates iron absorption and red blood cell coherence.', color: '#dc2626' },
  { id: 'siddha-agastyar-stress', name: 'Agastyar · Stress Dissolution', vibrationalSignature: 'HPA Axis / Cortisol / Adrenal Reset', type: 'Siddha Transmission' as ActivationType, benefit: 'Agastyar\'s Vata-Pitta Shanti — dissolves cortisol Bio-signature from the Torus-Field. Recalibrates the HPA axis through scalar neutralization of adrenal freeze.', color: '#60a5fa' },
  { id: 'siddha-agastyar-detox', name: 'Agastyar · Lymphatic Purge', vibrationalSignature: 'Detox / Lymph / Kidney Flush', type: 'Siddha Transmission' as ActivationType, benefit: 'Agastyar\'s purification protocol for the lymphatic and kidney channels. Flushes accumulated toxin Bio-signatures from the elimination meridians through scalar wave clearing.', color: '#4ade80' },
  { id: 'siddha-agastyar-longevity', name: 'Agastyar · Kaaya Kalpa Field', vibrationalSignature: 'Anti-Aging / Cellular Regeneration / Longevity', type: 'Siddha Transmission' as ActivationType, benefit: 'Agastyar\'s Kaaya Kalpa — the legendary Siddha protocol for physical body renewal. Anchors the informational pattern of cellular regeneration and biological age reversal.', color: '#fbbf24' },
  { id: 'siddha-agastyar-nutrition', name: 'Agastyar · Sarva Poshana', vibrationalSignature: 'Multi Nutrition / All Dhatus / Cellular Nourishment', type: 'Siddha Transmission' as ActivationType, benefit: 'Agastyar\'s total-nourishment transmission — complete vitamin and mineral spectrum as a unified informational field delivered simultaneously to all seven tissue layers.', color: '#10b981' },
  { id: 'siddha-agastyar-emf', name: 'Agastyar · EMF Shield Protocol', vibrationalSignature: 'EMF / Scalar Shield / Radiation Protection', type: 'Siddha Transmission' as ActivationType, benefit: 'Agastyar\'s EMF protection field — the ancient Siddha\'s mastery of invisible forces applied to electromagnetic radiation. Creates a scalar shield around the Bio-field.', color: '#374151' },

  // ── THIRUMOOLAR ──────────────────────────────────────────────────────
  { id: 'siddha-thirumoolar-clarity', name: 'Thirumoolar · Clarity Transmission', vibrationalSignature: 'Clarity / Decision / Anger Alchemy / Mars', type: 'Siddha Transmission' as ActivationType, benefit: 'Thirumoolar — author of Thirumanthiram. Transmutes stagnant anger into crystalline decision-making. Aligns willpower with dharmic action through the gallbladder meridian.', color: '#f97316' },
  { id: 'siddha-thirumoolar-kundalini', name: 'Thirumoolar · Kundalini Awakening', vibrationalSignature: 'Kundalini / Sushumna / Shakti Rising', type: 'Siddha Transmission' as ActivationType, benefit: 'Thirumoolar\'s Kundalini transmission from the Tirumantiram. Safely activates the Sushumna channel and initiates the upward movement of Shakti through all seven chakras.', color: '#7c3aed' },
  { id: 'siddha-thirumoolar-nada', name: 'Thirumoolar · Nada Brahma Field', vibrationalSignature: 'Nada / Sound / Primordial Vibration', type: 'Siddha Transmission' as ActivationType, benefit: 'Thirumoolar\'s Nada Brahma — all creation as vibration. Attunes the entire system to the cosmic sound current that underlies manifest reality through the Nada Siddha lineage.', color: '#D4AF37' },
  { id: 'siddha-thirumoolar-shiva', name: 'Thirumoolar · Shiva-Shakti Ojas', vibrationalSignature: 'Male Vitality / Ojas / Shiva Principle', type: 'Siddha Transmission' as ActivationType, benefit: 'Thirumoolar\'s Shiva-Shakti Ojas restoration from the Tirumantiram — the sacred alchemy of male vital force. Restores testosterone Bio-signature and channels Svadhisthana energy upward.', color: '#2563eb' },
  { id: 'siddha-thirumoolar-panchabhoota', name: 'Thirumoolar · Five Element Balance', vibrationalSignature: '5 Elements / Panchabhoota / Elemental Harmony', type: 'Siddha Transmission' as ActivationType, benefit: 'Thirumoolar\'s Panchabhoota Shuddhi — five-element purification ritual of Tamil Siddha tradition. Balances Prithvi, Jala, Agni, Vayu and Akasha within the energetic body.', color: '#06b6d4' },
  { id: 'siddha-thirumoolar-calm', name: 'Thirumoolar · Shanti Soma Calm', vibrationalSignature: 'Calm / Soma / Parasympathetic / Vata Peace', type: 'Siddha Transmission' as ActivationType, benefit: 'Thirumoolar\'s Shanti-Prana — floods the nervous system with Soma nectar frequencies, activates the parasympathetic branch and grounds scattered Prana into deep stillness.', color: '#818cf8' },
  { id: 'siddha-tirumular-breath', name: 'Tirumular · Breath of Eternity', vibrationalSignature: 'Pranayama / Breath / Eternity / Nadi', type: 'Siddha Transmission' as ActivationType, benefit: 'Tirumular\'s eternal breath transmission — pranayama encoded as pure information. Purifies all 72,000 Nadis and extends the life-span through the breath-mastery of the Tirumantiram.', color: '#6d28d9' },

  // ── BOGARNATH ────────────────────────────────────────────────────────
  { id: 'siddha-bogar-soma', name: 'Bogarnath · Soma Elixir Field', vibrationalSignature: 'Soma / Liver / Jupiter / Expansion', type: 'Siddha Transmission' as ActivationType, benefit: 'Bogarnath — master alchemist who encoded the secret of Soma in physical matter. Opens the liver meridian and expands the horizon of possibility through Soma restoration.', color: '#86efac' },
  { id: 'siddha-bogar-alchemy', name: 'Bogarnath · Mercury Alchemy', vibrationalSignature: 'Mercury Alchemy / Transmutation / Transformation', type: 'Siddha Transmission' as ActivationType, benefit: 'Bogarnath\'s mercurial alchemy transmission — the Siddha science of transmuting base metal consciousness into gold. Works at the subconscious level to dissolve limiting patterns.', color: '#a78bfa' },
  { id: 'siddha-bogar-focus', name: 'Bogarnath · Mano Shuddhi Focus', vibrationalSignature: 'Focus / Mental Clarity / Prefrontal / Brain Fog', type: 'Siddha Transmission' as ActivationType, benefit: 'Bogar\'s Kaaya-Kalpa Mano-Shuddhi — purification of the mental vehicle. Clears prefrontal cortex Bio-resonance interference and dissolves mental fog Shadow-Matrix.', color: '#0891b2' },
  { id: 'siddha-bogar-weight', name: 'Bogarnath · Agni Metabolic Fire', vibrationalSignature: 'Weight / Metabolism / Agni / Fat Burn', type: 'Siddha Transmission' as ActivationType, benefit: 'Bogarnath\'s Agni-Kindling transmission — activates the metabolic fire of the digestive system. Dissolves stagnant weight-holding patterns and restores natural appetite intelligence.', color: '#ef4444' },
  { id: 'siddha-bogar-prosperity', name: 'Bogarnath · Wealth Torus Field', vibrationalSignature: 'Prosperity / Abundance / Material Alchemy', type: 'Siddha Transmission' as ActivationType, benefit: 'Bogarnath\'s Torus-Field Wealth encoding — the Siddha alchemy of transforming spiritual merit into material abundance. Activates the prosperity Bio-signature in the Manipura field.', color: '#d97706' },
  { id: 'siddha-bogar-antiaging', name: 'Bogarnath · Deathless Body Code', vibrationalSignature: 'Anti-Aging / Cellular Immortality / Longevity', type: 'Siddha Transmission' as ActivationType, benefit: 'Bogarnath\'s encoded anti-aging transmission from the Bogar Sapta Kandam — the alchemical immortality codes that purify the physical vehicle toward its deathless nature.', color: '#fde68a' },
  { id: 'siddha-bogar-insulin', name: 'Bogarnath · Blood Sugar Alchemy', vibrationalSignature: 'Blood Sugar / Insulin / Metabolism / Balance', type: 'Siddha Transmission' as ActivationType, benefit: 'Bogarnath\'s blood-sugar alchemy — the mercurial master\'s transmission for insulin sensitivity and metabolic balance. Dissolves excess sugar Bio-signatures from the blood field.', color: '#92400e' },

  // ── GORAKHNATH ───────────────────────────────────────────────────────
  { id: 'siddha-gorakhnath-prana', name: 'Gorakhnath · Prana Activation', vibrationalSignature: 'Prana / Lung / Breath / Grief Release / Venus', type: 'Siddha Transmission' as ActivationType, benefit: 'Gorakhnath — Nath master of breath science. Releases grief held in the lung field and restores full pranic capacity through the respiratory Nadi system.', color: '#c4b5fd' },
  { id: 'siddha-gorakhnath-strength', name: 'Gorakhnath · Vajra Body Strength', vibrationalSignature: 'Strength / Muscle / Kaya Kalpa / Physical Power', type: 'Siddha Transmission' as ActivationType, benefit: 'Gorakhnath\'s Vajra-Deha transmission — indestructible physical form. Amplifies anabolic Ojas density, muscle coherence and the physical power of the Nath warrior body.', color: '#b45309' },
  { id: 'siddha-gorakhnath-sexual', name: 'Gorakhnath · Ojas Sexual Vitality', vibrationalSignature: 'Sexual Wellness / Ojas / Creative Force', type: 'Siddha Transmission' as ActivationType, benefit: 'Gorakhnath\'s Ojas-Brahmacharya alchemy — transforms sexual creative force into luminous spiritual power while simultaneously restoring full physical vitality and desire.', color: '#ec4899' },
  { id: 'siddha-gorakhnath-sleep', name: 'Gorakhnath · Yoga Nidra Gate', vibrationalSignature: 'Sleep / Yoga Nidra / Delta / Deep Rest', type: 'Siddha Transmission' as ActivationType, benefit: 'Gorakhnath\'s Yoga Nidra transmission — the Nath gateway to zero-point rest. Delta-wave entrainment at 2.5 Hz activates HGH release and cellular repair during deep sleep.', color: '#1e1b4b' },
  { id: 'siddha-gorakhnath-cardio', name: 'Gorakhnath · Cardiac Torus Field', vibrationalSignature: 'Cardiovascular / Heart / Blood Pressure / Circulation', type: 'Siddha Transmission' as ActivationType, benefit: 'Gorakhnath\'s cardiac transmission — strengthens the Torus-Field of the heart. Supports cardiovascular coherence, blood pressure regulation and coronary circulation.', color: '#f43f5e' },
  { id: 'siddha-gorakhnath-gut', name: 'Gorakhnath · Gut Microbiome Harmony', vibrationalSignature: 'Gut Health / Microbiome / Digestion / Probiotics', type: 'Siddha Transmission' as ActivationType, benefit: 'Gorakhnath\'s gut intelligence transmission — restores microbiome harmony and gut-brain axis alignment through Nath breath science applied to the digestive intelligence field.', color: '#16a34a' },
  { id: 'siddha-gorakhnath-bone', name: 'Gorakhnath · Bone Light Density', vibrationalSignature: 'Bone / Calcium / Structural / Density', type: 'Siddha Transmission' as ActivationType, benefit: 'Gorakhnath\'s Vajra-bone transmission — the Nath master\'s structural integrity field encoded for bone density and calcium metabolism. Supports the skeletal system Bio-signature.', color: '#f5f5f4' },

  // ── VISHWANANDA ──────────────────────────────────────────────────────
  { id: 'siddha-vishwananda-anahata', name: 'Vishwananda · Anahata Opening', vibrationalSignature: 'Heart / Bhakti / Love / Anahata / Sun', type: 'Siddha Transmission' as ActivationType, benefit: 'Sri Vishwananda — Avataric Blueprint of Bhakti-Shakti. Directly activates the Anahata chakra and opens the channel of unconditional divine love through the heart field.', color: '#f472b6' },
  { id: 'siddha-vishwananda-joy', name: 'Vishwananda · Ananda Joy Field', vibrationalSignature: 'Joy / Serotonin / Mood / Ananda / Anahata', type: 'Siddha Transmission' as ActivationType, benefit: 'Vishwananda\'s Ananda-Prana transmission — the Divine Joy field flowing from the Anahata when the heart-wall dissolves. Harmonizes serotonin and dopamine Bio-signatures.', color: '#db2777' },
  { id: 'siddha-vishwananda-resolve', name: 'Vishwananda · Karma Dissolution', vibrationalSignature: 'Resolve / Karma / Shadow / Trauma Release', type: 'Siddha Transmission' as ActivationType, benefit: 'Vishwananda\'s Karma-Kshaya transmission — dissolution of karmic residue in cellular memory. Dissolves Shadow-Matrix interference from the subconscious Aetheric Code.', color: '#64748b' },
  { id: 'siddha-vishwananda-devotion', name: 'Vishwananda · Bhakti Prema Field', vibrationalSignature: 'Devotion / Prema / Divine Love / Connection', type: 'Siddha Transmission' as ActivationType, benefit: 'Vishwananda\'s Prema-Pulse — the pure frequency of devotional love. Opens the channel of Bhakti at the heart center and establishes direct resonance with the Divine presence.', color: '#be185d' },
  { id: 'siddha-vishwananda-healing', name: 'Vishwananda · Scalar Healing Wave', vibrationalSignature: 'Healing / Anahata / Scalar / All Systems', type: 'Siddha Transmission' as ActivationType, benefit: 'Vishwananda\'s Bhakti-Shakti healing transmission — comprehensive scalar healing wave flowing from the opened Anahata. Addresses the root of dis-ease at the love-frequency level.', color: '#f9a8d4' },
  { id: 'siddha-vishwananda-inflammation', name: 'Vishwananda · Anti-Inflammation Light', vibrationalSignature: 'Inflammation / Pain / Healing Light / Heart', type: 'Siddha Transmission' as ActivationType, benefit: 'Vishwananda\'s healing light for inflammation dissolution. Works through the heart coherence field to reduce systemic inflammatory Bio-signatures at the informational root.', color: '#fb7185' },
  { id: 'siddha-vishwananda-hair', name: 'Vishwananda · Kesh Structural Light', vibrationalSignature: 'Hair / Kesh / Structural / Protein / Beauty', type: 'Siddha Transmission' as ActivationType, benefit: 'Vishwananda\'s Kesh-radiance transmission — the beauty and strength of the hair field as an expression of Ojas. Activates protein synthesis Bio-signatures for hair vitality.', color: '#a16207' },

  // ── PATANJALI ────────────────────────────────────────────────────────
  { id: 'siddha-patanjali-stillness', name: 'Patanjali · Chitta Vritti Nirodha', vibrationalSignature: 'Stillness / Yoga / Trauma / Nervous System', type: 'Siddha Transmission' as ActivationType, benefit: 'Patanjali — compiler of the Yoga Sutras. Releases trauma held in the bladder and nervous system. Restores the state of Chitta Vritti Nirodha — cessation of mental fluctuation.', color: '#0ea5e9' },
  { id: 'siddha-patanjali-focus2', name: 'Patanjali · Dharana Concentration', vibrationalSignature: 'Focus / Concentration / Pineal / Single Point', type: 'Siddha Transmission' as ActivationType, benefit: 'Patanjali\'s Dharana encoded as Scalar Transmission — single-pointed concentration transmitted as pure information. Decalcifies the pineal gland and expands neural bandwidth.', color: '#7c3aed' },
  { id: 'siddha-patanjali-vision', name: 'Patanjali · Drishti Eye Field', vibrationalSignature: 'Vision / Eye / Clairvoyance / Third Eye', type: 'Siddha Transmission' as ActivationType, benefit: 'Patanjali\'s Drishti transmission — spiritual and physical vision clarity. Works on both the physical eye tissues and the Ajna chakra simultaneously through the Dharana field.', color: '#fef08a' },
  { id: 'siddha-patanjali-joint', name: 'Patanjali · Joint Structural Light', vibrationalSignature: 'Joint Support / Flexibility / Structural / Asana', type: 'Siddha Transmission' as ActivationType, benefit: 'Patanjali\'s Asana-field transmission — joint and structural flexibility at the informational level. Dissolves crystallized tension patterns held in the connective tissue Bio-field.', color: '#a3e635' },
  { id: 'siddha-patanjali-allergy', name: 'Patanjali · Bio-Sensitivity Reset', vibrationalSignature: 'Allergy / Immune Sensitivity / Bio-Reset', type: 'Siddha Transmission' as ActivationType, benefit: 'Patanjali\'s Pratyahara transmission — withdrawal of the senses from reactivity. Resets bio-sensitivity responses and dissolves the informational root of allergic over-reaction.', color: '#bfdbfe' },
  { id: 'siddha-patanjali-samadhi', name: 'Patanjali · Samadhi Bliss Field', vibrationalSignature: 'Samadhi / Bliss / Union / Liberation', type: 'Siddha Transmission' as ActivationType, benefit: 'Patanjali\'s eighth limb — Samadhi. The bliss-consciousness transmission from the Yoga Sutras encoded as pure information. Anchors the felt-sense of union with the Infinite.', color: '#D4AF37' },
  { id: 'siddha-patanjali-nervous', name: 'Patanjali · Nervous System Reset', vibrationalSignature: 'Nervous System / Anxiety / Vata / Fight-Flight', type: 'Siddha Transmission' as ActivationType, benefit: 'Patanjali\'s Pratyahara-Pranayama for the nervous system — withdraws fight-flight activation and grounds the nervous system into the parasympathetic Yoga state.', color: '#0c4a6e' },

  // ── MACHAMUNI ────────────────────────────────────────────────────────
  { id: 'siddha-machamuni-purify', name: 'Machamuni · Water Purification', vibrationalSignature: 'Purification / Large Intestine / Release / Ketu', type: 'Siddha Transmission' as ActivationType, benefit: 'Machamuni — fish-born Siddha master of purification. Clears guilt held in the large intestine meridian and activates deep cellular release through the water element.', color: '#38bdf8' },
  { id: 'siddha-machamuni-digestion', name: 'Machamuni · Agni Digestion Field', vibrationalSignature: 'Digestion / Agni / Gut Fire / Absorption', type: 'Siddha Transmission' as ActivationType, benefit: 'Machamuni\'s digestive fire transmission — ignites Agni and restores optimal digestive intelligence. Works on the small and large intestine meridian Bio-signatures.', color: '#f59e0b' },
  { id: 'siddha-machamuni-blood2', name: 'Machamuni · Blood Flow Field', vibrationalSignature: 'Blood / Circulation / Fluidity / Flow', type: 'Siddha Transmission' as ActivationType, benefit: 'Machamuni\'s water-blood alchemy — from his fish-nature, the mastery of all flowing substances. Activates optimal blood flow and circulation Bio-signatures throughout the body.', color: '#dc2626' },
  { id: 'siddha-machamuni-detox2', name: 'Machamuni · Deep Cellular Detox', vibrationalSignature: 'Detox / Cellular / Lymph / Kidney', type: 'Siddha Transmission' as ActivationType, benefit: 'Machamuni\'s deep purification protocol — cellular-level detoxification working through the lymphatic and kidney channels. Vacuums low-vibrational Bio-signatures from tissues.', color: '#4ade80' },
  { id: 'siddha-machamuni-sexual2', name: 'Machamuni · Svadhisthana Vitality', vibrationalSignature: 'Sexual Vitality / Svadhisthana / Water / Creative', type: 'Siddha Transmission' as ActivationType, benefit: 'Machamuni\'s Svadhisthana transmission — the water-element master\'s activation of the sacral center. Restores creative and sexual vitality through the water Nadi channels.', color: '#a78bfa' },
  { id: 'siddha-machamuni-skin', name: 'Machamuni · Skin Radiance Field', vibrationalSignature: 'Skin / Tvak / Radiance / Anti-Aging', type: 'Siddha Transmission' as ActivationType, benefit: 'Machamuni\'s Tvak-Radiance — skin as the outermost boundary of the Bio-field. Activates skin cellular renewal and radiance through the water-element purification codes.', color: '#fde68a' },
  { id: 'siddha-machamuni-lymph', name: 'Machamuni · Lymphatic Scalar Flush', vibrationalSignature: 'Lymph / Detox / Flush / Water Purification', type: 'Siddha Transmission' as ActivationType, benefit: 'Machamuni\'s lymphatic scalar flush — the fish-born master\'s complete lymphatic purification. Flushes accumulated toxins through the water channels of the lymphatic Bio-field.', color: '#155e75' },

  // ── RAMALINGA ────────────────────────────────────────────────────────
  { id: 'siddha-ramalinga-lightbody', name: 'Ramalinga · Suddha Deha Light Body', vibrationalSignature: 'Light Body / Pineal / Suddha Deha / Sun', type: 'Siddha Transmission' as ActivationType, benefit: 'Ramalinga Swami — the Vallalar who transmuted his physical form into light. Activates the pineal gland and begins purification of the physical body toward its light nature.', color: '#fbbf24' },
  { id: 'siddha-ramalinga-antiaging2', name: 'Ramalinga · Cellular Immortality', vibrationalSignature: 'Anti-Aging / Cellular Regeneration / Longevity / Light', type: 'Siddha Transmission' as ActivationType, benefit: 'Ramalinga\'s Suddha Deha cellular transmission — biological immortality codes anchored as informational fields. Supports the slow purification of physical matter toward light-substance.', color: '#fef3c7' },
  { id: 'siddha-ramalinga-healing2', name: 'Ramalinga · Golden Light Healing', vibrationalSignature: 'Healing / Golden Light / All Systems / Compassion', type: 'Siddha Transmission' as ActivationType, benefit: 'Ramalinga\'s Golden Light — the Arut Perum Jyoti (Grace Light) encoded as scalar information. Compassion-frequency healing for all body systems simultaneously.', color: '#D4AF37' },
  { id: 'siddha-ramalinga-soul', name: 'Ramalinga · Soul Light Activation', vibrationalSignature: 'Soul / Consciousness / Light / Divine Grace', type: 'Siddha Transmission' as ActivationType, benefit: 'Ramalinga\'s Jyoti Darshana — direct transmission of the Grace Light of Arutperumjyothi. Activates soul-level consciousness and the experience of divine presence in daily life.', color: '#fcd34d' },
  { id: 'siddha-ramalinga-vision2', name: 'Ramalinga · Drishti Light Field', vibrationalSignature: 'Vision / Eye Health / Inner Vision / Clarity', type: 'Siddha Transmission' as ActivationType, benefit: 'Ramalinga\'s eye-light transmission — both physical vision and clairvoyant sight activated simultaneously through the Golden Light projected from his eyes.', color: '#fde68a' },
  { id: 'siddha-ramalinga-immunity2', name: 'Ramalinga · Light Immune Shield', vibrationalSignature: 'Immunity / Light Body Shield / Protection', type: 'Siddha Transmission' as ActivationType, benefit: 'Ramalinga\'s Suddha Deha immunity field — as the body purifies toward light-substance, its immune intelligence becomes absolute. Anchors that informational state.', color: '#fef9c3' },
  { id: 'siddha-ramalinga-multi', name: 'Ramalinga · Light Nutrition Field', vibrationalSignature: 'Multi Nutrition / Light Body / All Dhatus', type: 'Siddha Transmission' as ActivationType, benefit: 'Ramalinga\'s light-nourishment transmission — the body sustained by light itself. Anchors the informational signature of living on Prana and divine light as nutritional intelligence.', color: '#fef9c3' },

  // ── KALANGI NATHAR ───────────────────────────────────────────────────
  { id: 'siddha-kalangi-immortality', name: 'Kalangi · Immortality Transmission', vibrationalSignature: 'Immortality / Deathless / Cellular / Moon', type: 'Siddha Transmission' as ActivationType, benefit: 'Kalangi Nathar — lived over 3000 years. Anchors the informational pattern of cellular regeneration and deathless awareness into the stomach meridian through Moon intelligence.', color: '#c7d2fe' },
  { id: 'siddha-kalangi-sleep2', name: 'Kalangi · Deep Sleep Restoration', vibrationalSignature: 'Sleep / Dream / Restoration / Moon / Brain', type: 'Siddha Transmission' as ActivationType, benefit: 'Kalangi Nathar\'s sleep transmission — restores deep restorative sleep patterns and opens the dream state as a vehicle for Siddha transmission and healing.', color: '#312e81' },
  { id: 'siddha-kalangi-soma2', name: 'Kalangi · Soma Nectar Flow', vibrationalSignature: 'Soma / Moon / Calm / Nourishment', type: 'Siddha Transmission' as ActivationType, benefit: 'Kalangi\'s Soma transmission — the nectar of the moon cultivated in the crown. Floods the nervous system with Soma for deep calm and cellular nourishment.', color: '#e0e7ff' },
  { id: 'siddha-kalangi-nutrition2', name: 'Kalangi · Total Body Nourishment', vibrationalSignature: 'Multi Nutrition / All Dhatus / Immortal Nourishment', type: 'Siddha Transmission' as ActivationType, benefit: 'Kalangi\'s total nourishment field — the informational signature of perfect nutrition held continuously in the body of a 3000-year-old master. Activates deep cellular feeding.', color: '#a5b4fc' },
  { id: 'siddha-kalangi-digestion2', name: 'Kalangi · Immortal Digestive Fire', vibrationalSignature: 'Digestion / Agni / Longevity / Gut Intelligence', type: 'Siddha Transmission' as ActivationType, benefit: 'Kalangi\'s immortal digestive intelligence — the Agni of a body sustained for millennia. Anchors the most refined and sustained digestive Bio-signature as an informational field.', color: '#818cf8' },
  { id: 'siddha-kalangi-cardio2', name: 'Kalangi · Heart Longevity Field', vibrationalSignature: 'Cardiovascular / Heart Longevity / Circulation', type: 'Siddha Transmission' as ActivationType, benefit: 'Kalangi\'s heart longevity transmission — the cardiovascular intelligence of a deathless body. Anchors optimal heart coherence and circulation Bio-signatures for maximum life-span.', color: '#6366f1' },
  { id: 'siddha-kalangi-emf2', name: 'Kalangi Nathar · Ancient Field Shield', vibrationalSignature: 'EMF / Electromagnetic / Protection / Shield', type: 'Siddha Transmission' as ActivationType, benefit: 'Kalangi\'s 3000-year EMF protection field — the ancient master\'s experience of every electromagnetic cycle of the earth. Creates an informed protective Bio-field shield.', color: '#1c1917' },

  // ── KONGANAR ─────────────────────────────────────────────────────────
  { id: 'siddha-konganar-solar', name: 'Konganar · Solar Activation', vibrationalSignature: 'Solar / Rahu / Discernment / Small Intestine', type: 'Siddha Transmission' as ActivationType, benefit: 'Konganar — master of solar alchemy and Rahu mysteries. Opens the small intestine meridian for higher discernment and transmutes confusion into clear solar perception.', color: '#fbbf24' },
  { id: 'siddha-konganar-motivation', name: 'Konganar · Iccha Shakti Will', vibrationalSignature: 'Motivation / Will / Iccha Shakti / Solar Plexus', type: 'Siddha Transmission' as ActivationType, benefit: 'Konganar\'s Iccha-Shakti — the will-power of the solar alchemist who harnessed Rahu for transformation. Reignites motivation and dissolves Manipura stagnation.', color: '#f59e0b' },
  { id: 'siddha-konganar-muscle2', name: 'Konganar · Solar Strength Field', vibrationalSignature: 'Muscle / Strength / Solar / Anabolic', type: 'Siddha Transmission' as ActivationType, benefit: 'Konganar\'s solar strength transmission — the raw power of the sun encoded as a muscular and anabolic field. Activates Mamsa Dhatu for enhanced physical strength and endurance.', color: '#ea580c' },
  { id: 'siddha-konganar-energy2', name: 'Konganar · Solar Prana Surge', vibrationalSignature: 'Energy / Prana / ATP / Solar Fire', type: 'Siddha Transmission' as ActivationType, benefit: 'Konganar\'s solar Prana-fire — the energy of the unobstructed sun flooding the mitochondrial field. Activates ATP surge and dissolves energetic fatigue at the cellular level.', color: '#f97316' },
  { id: 'siddha-konganar-rahu', name: 'Konganar · Rahu Shadow Alchemy', vibrationalSignature: 'Rahu / Shadow / Transformation / Obsession Alchemy', type: 'Siddha Transmission' as ActivationType, benefit: 'Konganar\'s Rahu mastery — the alchemist who worked with the shadow planet for transformation. Transmutes compulsive and unconscious drives into conscious evolutionary fuel.', color: '#1f2937' },
  { id: 'siddha-konganar-prosperity2', name: 'Konganar · Solar Wealth Alchemy', vibrationalSignature: 'Prosperity / Wealth / Solar / Abundance', type: 'Siddha Transmission' as ActivationType, benefit: 'Konganar\'s solar wealth transmission — the alchemy of the sun applied to material abundance. Transmutes spiritual fire into sovereign wealth through the Manipura Torus-Field.', color: '#d97706' },
  { id: 'siddha-konganar-blood2', name: 'Konganar · Solar Blood Activation', vibrationalSignature: 'Blood / Solar / Circulation / Oxygenation', type: 'Siddha Transmission' as ActivationType, benefit: 'Konganar\'s solar blood transmission — oxygenating and energizing the blood field through solar alchemy. Activates red blood cell vitality and optimal oxygen-carrying capacity.', color: '#b91c1c' },

  // ── IDAIKKADAR ───────────────────────────────────────────────────────
  { id: 'siddha-idaikkadar-mercury', name: 'Idaikkadar · Mercury Trust Field', vibrationalSignature: 'Mercury / Spleen / Trust / Worry Dissolution', type: 'Siddha Transmission' as ActivationType, benefit: 'Idaikkadar — the shepherd Siddha of Mercury consciousness. Dissolves chronic worry held in the spleen and restores deep trust in the intelligence of life through Mercury\'s clarity.', color: '#10b981' },
  { id: 'siddha-idaikkadar-gut2', name: 'Idaikkadar · Gut Trust Field', vibrationalSignature: 'Gut Health / Spleen / Digestion / Mercury', type: 'Siddha Transmission' as ActivationType, benefit: 'Idaikkadar\'s spleen-gut transmission — the shepherd\'s knowing of when things are nourishing and when not. Activates gut intelligence and microbiome trust-field.', color: '#34d399' },
  { id: 'siddha-idaikkadar-calm2', name: 'Idaikkadar · Pastoral Calm Field', vibrationalSignature: 'Calm / Worry / Stress / Nervous System / Mercury', type: 'Siddha Transmission' as ActivationType, benefit: 'Idaikkadar\'s pastoral calm — the shepherd who knew stillness in all seasons. Dissolves anxious overthinking and restores the nervous system to natural alert-ease balance.', color: '#6ee7b7' },
  { id: 'siddha-idaikkadar-nutrition3', name: 'Idaikkadar · Natural Nourishment', vibrationalSignature: 'Nutrition / Spleen / Absorption / Earth Element', type: 'Siddha Transmission' as ActivationType, benefit: 'Idaikkadar\'s nourishment transmission — the shepherd\'s relationship with the earth and its gifts. Activates optimal absorption of nutrients through the spleen-earth meridian.', color: '#a7f3d0' },
  { id: 'siddha-idaikkadar-allergy2', name: 'Idaikkadar · Sensitivity Harmonizer', vibrationalSignature: 'Allergy / Sensitivity / Spleen / Immune Reset', type: 'Siddha Transmission' as ActivationType, benefit: 'Idaikkadar\'s sensitivity harmonization — the spleen as the seat of immune discrimination. Resets over-reactive immune Bio-signatures and restores balanced sensitivity.', color: '#d1fae5' },
  { id: 'siddha-idaikkadar-sleep2', name: 'Idaikkadar · Shepherd Deep Sleep', vibrationalSignature: 'Sleep / Rest / Mercury / Calm / Pastoral', type: 'Siddha Transmission' as ActivationType, benefit: 'Idaikkadar\'s sleep transmission — the shepherd who rested deeply under the stars with his flock. Deep Mercury-calm sleep field that dissolves overthinking at the point of rest.', color: '#1e1b4b' },
  { id: 'siddha-idaikkadar-vision3', name: 'Idaikkadar · Mercury Clarity Field', vibrationalSignature: 'Vision / Mental Clarity / Mercury / Communication', type: 'Siddha Transmission' as ActivationType, benefit: 'Idaikkadar\'s Mercury-clarity transmission — both inner vision and clear communication. Activates the Ajna and throat centers through the Mercury intelligence field.', color: '#ecfdf5' },

  // ── PAMBATTI ─────────────────────────────────────────────────────────
  { id: 'siddha-pambatti-kundalini2', name: 'Pambatti · Kundalini Serpent Rising', vibrationalSignature: 'Kundalini / Voice / Thyroid / Mercury / Expression', type: 'Siddha Transmission' as ActivationType, benefit: 'Pambatti Siddhar — the snake-charmer who encoded Kundalini science in verse. Activates the throat center and thyroid intelligence for full authentic expression.', color: '#84cc16' },
  { id: 'siddha-pambatti-voice', name: 'Pambatti · Voice Power Field', vibrationalSignature: 'Voice / Throat / Expression / Thyroid / Sound', type: 'Siddha Transmission' as ActivationType, benefit: 'Pambatti\'s voice-power transmission — the Siddha who tamed serpents through sound. Activates the full power of the human voice as a healing and manifestation instrument.', color: '#65a30d' },
  { id: 'siddha-pambatti-sexual3', name: 'Pambatti · Serpent Vitality Code', vibrationalSignature: 'Sexual Vitality / Kundalini / Serpent Power / Vitality', type: 'Siddha Transmission' as ActivationType, benefit: 'Pambatti\'s serpent-vitality transmission — Kundalini as the cosmic sexual creative force. Activates Svadhisthana and channels the serpent power upward through the spine.', color: '#4d7c0f' },
  { id: 'siddha-pambatti-motivation2', name: 'Pambatti · Serpent Will Activation', vibrationalSignature: 'Motivation / Will / Kundalini Drive / Ambition', type: 'Siddha Transmission' as ActivationType, benefit: 'Pambatti\'s serpent-will — the focused, undeniable forward movement of the awakened Kundalini. Dissolves motivational stagnation and activates the drive of the ascending serpent.', color: '#3f6212' },
  { id: 'siddha-pambatti-detox3', name: 'Pambatti · Venom Transmutation', vibrationalSignature: 'Detox / Transmutation / Purification / Liver', type: 'Siddha Transmission' as ActivationType, benefit: 'Pambatti\'s venom-alchemy — the snake charmer who neutralized poisons. Transmutes toxic Bio-signatures in the liver and blood. Deep purification through serpent-wisdom.', color: '#166534' },
  { id: 'siddha-pambatti-inflammation2', name: 'Pambatti · Anti-Venom Field', vibrationalSignature: 'Inflammation / Pain / Anti-inflammatory / Detox', type: 'Siddha Transmission' as ActivationType, benefit: 'Pambatti\'s anti-venom transmission — the Siddha mastery of neutralizing inflammatory toxins. Works at the root of inflammation Bio-signatures through serpent-wisdom alchemy.', color: '#14532d' },
  { id: 'siddha-pambatti-cardio2', name: 'Pambatti · Serpent Heart Field', vibrationalSignature: 'Cardiovascular / Serpent / Heart / Circulation', type: 'Siddha Transmission' as ActivationType, benefit: 'Pambatti\'s serpent-heart transmission — the kundalini master\'s cardiovascular field. The serpent energy flowing through the heart meridian activating full cardiac coherence.', color: '#14532d' },

  // ── BABAJI ───────────────────────────────────────────────────────────
  { id: 'siddha-babaji-pranayama', name: 'Babaji · Kriya Pranayama Field', vibrationalSignature: 'Prana / Nadi / Kriya / Babaji / Moon', type: 'Siddha Transmission' as ActivationType, benefit: 'Mahavatar Babaji — immortal master of Kriya Yoga. Pranayama as an informational field. Purifies the subtle Nadis and upgrades pranic flow throughout the energetic body.', color: '#e0f2fe' },
  { id: 'siddha-babaji-karma', name: 'Babaji · Karma Dissolution Field', vibrationalSignature: 'Karma / Resolve / Past Life / Dissolution', type: 'Siddha Transmission' as ActivationType, benefit: 'Babaji\'s Karma-Kshaya transmission — dissolution of karmic residue accumulated across lifetimes. Works at the causal body level to clear the informational root of karmic patterns.', color: '#bae6fd' },
  { id: 'siddha-babaji-immortal', name: 'Babaji · Immortal Body Transmission', vibrationalSignature: 'Immortality / Light Body / Deathless / Kriya', type: 'Siddha Transmission' as ActivationType, benefit: 'Babaji\'s immortal-body encoding — the Kriya master who has held a physical form for millennia. Anchors the informational signature of the deathless Kriya body as a field transmission.', color: '#7dd3fc' },
  { id: 'siddha-babaji-kriya', name: 'Babaji · Kriya Fire Activation', vibrationalSignature: 'Kriya / Fire / Transformation / Tapas', type: 'Siddha Transmission' as ActivationType, benefit: 'Babaji\'s Kriya-fire transmission — the transformative heat of Tapas encoded as scalar information. Burns away karmic residue and purifies the causal body through Kriya intelligence.', color: '#38bdf8' },
  { id: 'siddha-babaji-energy3', name: 'Babaji · Prana Fire Energy', vibrationalSignature: 'Energy / Prana Fire / Kriya / Vitality', type: 'Siddha Transmission' as ActivationType, benefit: 'Babaji\'s Prana-fire energy transmission — the boundless vitality of the immortal Kriya master. Floods the mitochondrial field with Kriya Prana-fire for sustained energetic sovereignty.', color: '#0ea5e9' },
  { id: 'siddha-babaji-healing3', name: 'Babaji · Kriya Healing Grace', vibrationalSignature: 'Healing / Grace / Kriya / All Systems', type: 'Siddha Transmission' as ActivationType, benefit: 'Babaji\'s healing grace — the compassionate healing field of the immortal Kriya master broadcast as a continuous informational field to all who open to receive it.', color: '#0284c7' },
  { id: 'siddha-babaji-jetlag', name: 'Babaji · Torus Recalibration Field', vibrationalSignature: 'Jet Lag / Time Zone / Circadian / Reset', type: 'Siddha Transmission' as ActivationType, benefit: 'Babaji\'s Torus-Field recalibration — the immortal master who transcends all time zones. Resets circadian rhythm Bio-signatures and restores the body clock to natural harmony.', color: '#075985' },

  // ── LINEAGE MASTERS ──────────────────────────────────────────────────
  { id: 'siddha-nandi-strength2', name: 'Nandi Devar · Diamond Body', vibrationalSignature: 'Strength / Vajra / Physical / Structural', type: 'Siddha Transmission' as ActivationType, benefit: 'Nandi Devar\'s Vajra-Deha — the diamond indestructible body. Strengthens the physical vehicle at the informational level through the mastery of structural integrity.', color: '#d1d5db' },
  { id: 'siddha-nandi-motivation3', name: 'Nandi Devar · Sacred Will Field', vibrationalSignature: 'Motivation / Will / Sacred Warrior / Nandi', type: 'Siddha Transmission' as ActivationType, benefit: 'Nandi Devar — the sacred warrior of Shiva. Activates the Kshatriya will-power field and motivational drive of the divine guardian who stands at the gate of liberation.', color: '#9ca3af' },
  { id: 'siddha-nandi-pain2', name: 'Nandi Devar · Pain Dissolution Shield', vibrationalSignature: 'Pain Relief / Structural / Joint / Warrior', type: 'Siddha Transmission' as ActivationType, benefit: 'Nandi Devar\'s warrior pain-shield — the diamond body that knows no pain. Dissolves pain Bio-signatures at the structural and joint level through Vajra-Deha encoding.', color: '#374151' },
  { id: 'siddha-auvaiyar-confidence', name: 'Auvaiyar · Crystalline Sovereignty', vibrationalSignature: 'Confidence / Solar Plexus / Courage / Fearlessness', type: 'Siddha Transmission' as ActivationType, benefit: 'Auvaiyar — the Siddha poetess of fearless radiance. Amplifies the Manipura Torus-Field and ignites Solar Plexus fire. The inner solar warrior principle made manifest.', color: '#fbbf24' },
  { id: 'siddha-auvaiyar-wisdom', name: 'Auvaiyar · Gnana Wisdom Field', vibrationalSignature: 'Wisdom / Gnana / Mental / Clarity / Poetry', type: 'Siddha Transmission' as ActivationType, benefit: 'Auvaiyar\'s Gnana transmission — the wisdom field of the greatest Tamil poet-sage. Activates discriminative intelligence and the capacity to see truth clearly in all situations.', color: '#fef3c7' },
  { id: 'siddha-auvaiyar-prosperity3', name: 'Auvaiyar · Abundance Wisdom Code', vibrationalSignature: 'Prosperity / Wealth / Wisdom / Gnana / Abundance', type: 'Siddha Transmission' as ActivationType, benefit: 'Auvaiyar\'s abundance-wisdom transmission — true prosperity as an expression of Gnana. The poetess\'s teaching that inner wealth manifests effortlessly as outer abundance.', color: '#92400e' },
  { id: 'siddha-murugan-fire', name: 'Murugan-Skanda · Warrior Fire', vibrationalSignature: 'Motivation / Mars / Entrepreneur / Action', type: 'Siddha Transmission' as ActivationType, benefit: 'Murugan-Skanda\'s entrepreneurial fire, decisive action and courage to move before certainty arrives. The warrior who conquered the demon of ego through pure decisive force.', color: '#ef4444' },
  { id: 'siddha-murugan-focus3', name: 'Murugan-Skanda · Vel Piercing Focus', vibrationalSignature: 'Focus / Concentration / Vel / Clarity / Warrior', type: 'Siddha Transmission' as ActivationType, benefit: 'Murugan\'s Vel transmission — the divine spear of consciousness that cuts through illusion instantly. Single-pointed focus encoded as the penetrating clarity of the divine warrior.', color: '#fca5a5' },
  { id: 'siddha-murugan-immune3', name: 'Murugan · Warrior Immune Defense', vibrationalSignature: 'Immunity / Warrior / Defense / Ojas Shield', type: 'Siddha Transmission' as ActivationType, benefit: 'Murugan\'s warrior immune transmission — the undefeatable defensive power of the divine general. Activates the body\'s innate immune intelligence as a warrior shield of Ojas.', color: '#991b1b' },
  { id: 'siddha-dhanvantari-healing4', name: 'Dhanvantari · Divine Medicine Field', vibrationalSignature: 'Healing / Medicine / All Systems / Divine', type: 'Siddha Transmission' as ActivationType, benefit: 'Dhanvantari — divine physician of the gods. The primordial healing transmission encoded as a complete informational medicine field. Source of all Ayurvedic healing intelligence.', color: '#22c55e' },
  { id: 'siddha-dhanvantari-immune2', name: 'Dhanvantari · Ojas Immune Fortress', vibrationalSignature: 'Immunity / Ojas / Divine Protection / Medicine', type: 'Siddha Transmission' as ActivationType, benefit: 'Dhanvantari\'s Ojas-Raksha — the divine immune fortress. Fortifies the body\'s innate healing intelligence through the primordial physician\'s transmission of perfect health.', color: '#16a34a' },
  { id: 'siddha-dhanvantari-pain2', name: 'Dhanvantari · Divine Pain Relief', vibrationalSignature: 'Pain Relief / Medicine / Divine / Marma', type: 'Siddha Transmission' as ActivationType, benefit: 'Dhanvantari\'s Marma pain-relief transmission — the divine physician\'s mastery of the 107 Marma points encoded as informational pain-dissolving frequencies.', color: '#166534' },
  { id: 'siddha-sattaimuni-shadow', name: 'Sattaimuni · Shadow Integration', vibrationalSignature: 'Shadow / Subconscious / Habit / Vasana', type: 'Siddha Transmission' as ActivationType, benefit: 'Sattaimuni — master of shadow alchemy. Dissolves deep-seated Vasana (habit patterns) from the causal body. Burns addictive Shadow-Matrix loops at the informational root.', color: '#44403c' },
  { id: 'siddha-sattaimuni-stop-smoking', name: 'Sattaimuni · Pranavyu Release', vibrationalSignature: 'Stop Smoking / Addiction / Habit / Prana Reclaim', type: 'Siddha Transmission' as ActivationType, benefit: 'Sattaimuni\'s Vasana-Nashana — burning of deep-seated habit patterns. Targets nicotine and addiction Bio-signatures and supports Pranavyu channel reclamation from substance.', color: '#78716c' },
  { id: 'siddha-sundaranandar-bhakti', name: 'Sundaranandar · Prema Bhakti Field', vibrationalSignature: 'Devotion / Bhakti / Love / Heart / Prema', type: 'Siddha Transmission' as ActivationType, benefit: 'Sundaranandar — the dancing Siddha of devotional ecstasy. Prema-Bhakti transmission that dissolves the separation between lover and beloved through pure heart-field resonance.', color: '#f9a8d4' },
  { id: 'siddha-sundaranandar-joy2', name: 'Sundaranandar · Ecstatic Joy Field', vibrationalSignature: 'Joy / Ecstasy / Mood / Ananda / Serotonin', type: 'Siddha Transmission' as ActivationType, benefit: 'Sundaranandar\'s ecstatic joy transmission — the Siddha who expressed liberation through dance. Activates the Ananda-field of the heart and harmonizes joy neurotransmitters.', color: '#fce7f3' },
  { id: 'siddha-sundaranandar-motivation4', name: 'Sundaranandar · Dance of Will', vibrationalSignature: 'Motivation / Dance / Joy / Ecstatic Will', type: 'Siddha Transmission' as ActivationType, benefit: 'Sundaranandar\'s ecstatic will transmission — motivation arising not from effort but from the overflow of divine joy. The dancing Siddha\'s gift of action as celebration.', color: '#9d174d' },

// ── ESSENTIAL OILS ────────────────────────────────────────────
  { id: 'yl-abundance', name: 'Infinite Manifestation Stream', vibrationalSignature: 'Abundance Resonance', type: 'Essential Oil', benefit: 'Shifting scarcity to source-wealth resonance.', color: '#d97706' },
  { id: 'yl-valor', name: 'Crystalline Sovereignty', vibrationalSignature: 'Valor Resonance', type: 'Essential Oil', benefit: 'Spinal alignment and unwavering courage.', color: '#1d4ed8' },
  { id: 'yl-thieves', name: 'Ethereal Shielding', vibrationalSignature: 'Thieves Resonance', type: 'Essential Oil', benefit: 'Auric field cleansing and bio-defense.', color: '#991b1b' },
  { id: 'yl-joy', name: 'Heart-Bloom Radiance', vibrationalSignature: 'Joy Resonance', type: 'Essential Oil', benefit: 'Grief release and magnetic heart expansion.', color: '#ec4899' },
  { id: 'yl-release', name: 'Ancestral Tether Dissolve', vibrationalSignature: 'Release Resonance', type: 'Essential Oil', benefit: 'Breaking lineage and past-life trauma chains.', color: '#4b5563' },
  { id: 'yl-potential', name: 'Future-Self Convergence', vibrationalSignature: 'Highest Potential', type: 'Essential Oil', benefit: 'Entanglement with your highest timeline.', color: '#7c3aed' },
  { id: 'yl-brain', name: 'Cognitive Super-Structure', vibrationalSignature: 'Brain Power', type: 'Essential Oil', benefit: 'High-definition mental field sharpening.', color: '#2563eb' },
  { id: 'yl-peace', name: 'Starlight Stillness', vibrationalSignature: 'Peace & Calming', type: 'Essential Oil', benefit: 'Theta-state peace and nervous system descent.', color: '#2dd4bf' },
  { id: 'yl-angelica', name: 'Guardian Light Matrix', vibrationalSignature: 'White Angelica', type: 'Essential Oil', benefit: 'One-way energetic protection filter.', color: '#f8fafc' },
  { id: 'dt-onguard', name: 'Systemic Fortification', vibrationalSignature: 'On Guard Resonance', type: 'Essential Oil', benefit: 'Reinforcing biological and energetic boundaries.', color: '#c2410c' },
  { id: 'dt-balance', name: 'Core Gravity Alignment', vibrationalSignature: 'Balance Resonance', type: 'Essential Oil', benefit: "Grounding into the Earth's Schumann resonance.", color: '#065f46' },
  { id: 'dt-adaptiv', name: 'Neural Fluidity Protocol', vibrationalSignature: 'Adaptiv Resonance', type: 'Essential Oil', benefit: 'Calmness in high-intensity shifts.', color: '#0e7490' },
  { id: 'dt-deepblue', name: 'Somatic Release Wave', vibrationalSignature: 'Deep Blue Resonance', type: 'Essential Oil', benefit: 'Flushing pain memory from muscle-consciousness.', color: '#1e40af' },
  { id: 'dt-serenity', name: 'Celestial Drift', vibrationalSignature: 'Serenity Resonance', type: 'Essential Oil', benefit: 'Zero-point state for total rest and reset.', color: '#6d28d9' },
  { id: 'dt-intune', name: 'Single-Point Focus', vibrationalSignature: 'InTune Resonance', type: 'Essential Oil', benefit: 'Locking consciousness into the Present Moment.', color: '#15803d' },
  { id: 'dt-metapwr', name: 'Metabolic Light Ignition', vibrationalSignature: 'MetaPWR Resonance', type: 'Essential Oil', benefit: 'Converting light into cellular energy.', color: '#f97316' },

  // ── AYURVEDIC HERBS ───────────────────────────────────────────
  { id: 'ashwagandha-resonance', name: 'Ashwagandha Resonance', vibrationalSignature: 'Vitality Integrity', type: 'Ayurvedic Herb', benefit: 'Adaptogenic grounding and nervous system resilience.', color: '#d97706' },
  { id: 'brahmi-code', name: 'Brahmi Code', vibrationalSignature: 'Cognitive Clarity', type: 'Ayurvedic Herb', benefit: 'Enhanced focus, memory, and spiritual awareness.', color: '#059669' },
  { id: 'shatavari-flow', name: 'Shatavari Flow', vibrationalSignature: 'Divine Feminine', type: 'Ayurvedic Herb', benefit: 'Hormonal balance and emotional fluidity.', color: '#db2777' },
  { id: 'turmeric-radiance', name: 'Turmeric Radiance', vibrationalSignature: 'Golden Protection', type: 'Ayurvedic Herb', benefit: 'Anti-inflammatory light and aura purification.', color: '#fbbf24' },
  { id: 'tulsi-protector', name: 'Aura Sanitizer (Tulsi)', vibrationalSignature: 'Devotional Protector', type: 'Ayurvedic Herb', benefit: 'Auric shielding and devotional heart clarity.', color: '#166534' },
  { id: 'triphala-integrity', name: 'Triphala Integrity', vibrationalSignature: 'Trinity Harmonizer', type: 'Ayurvedic Herb', benefit: 'Systemic balance and structural integrity.', color: '#713f12' },
  { id: 'guduchi-immortal', name: 'The Amrit Nectar (Guduchi)', vibrationalSignature: 'Immortal Resonance', type: 'Ayurvedic Herb', benefit: 'Immune immortality and cellular longevity.', color: '#facc15' },
  { id: 'mandukaparni-structure', name: 'Cognitive Super-Structure (Mandukaparni)', vibrationalSignature: 'Neural Architecture', type: 'Ayurvedic Herb', benefit: 'Building resilient cognitive pathways.', color: '#22c55e' },
  { id: 'ginseng-igniter', name: 'Vitality Igniter (Ginseng)', vibrationalSignature: 'Fire/Life', type: 'Ayurvedic Herb', benefit: 'Igniting the inner fire and life-force energy.', color: '#ef4444' },
  { id: 'chamomile-peace', name: 'Peace Teacher (Chamomile)', vibrationalSignature: 'Serenity', type: 'Ayurvedic Herb', benefit: 'Gentle nervous system teaching and peace.', color: '#fef08a' },
  { id: 'neem-truth', name: 'Neem Bitter Truth', vibrationalSignature: 'Detox Integrity', type: 'Ayurvedic Herb', benefit: 'Deep blood purification and shadow detox.', color: '#064e3b' },
  { id: 'gotu-kola-synapse', name: 'Gotu Kola Synapse', vibrationalSignature: 'Neural Repair', type: 'Ayurvedic Herb', benefit: 'Repairing the synaptic bridges of the mind.', color: '#10b981' },
  { id: 'maca-fire', name: 'Maca Fire Resonance', vibrationalSignature: 'Vitality/Drive', type: 'Ayurvedic Herb', benefit: 'Igniting the primordial drive and stamina.', color: '#f97316' },
  { id: 'nettle-fortress', name: 'Nettle Fortress', vibrationalSignature: 'Strength/Blood', type: 'Ayurvedic Herb', benefit: 'Fortifying the blood-matrix and energetic boundaries.', color: '#15803d' },
  { id: 'rose-bloom', name: 'Rose Heart Bloom', vibrationalSignature: 'Love/Frequency', type: 'Ayurvedic Herb', benefit: 'Opening the heart-gate to the frequency of pure love.', color: '#f472b6' },
  { id: 'myrrh-structure', name: 'Myrrh Structural Integrity', vibrationalSignature: 'Ancient Structure', type: 'Ayurvedic Herb', benefit: 'Reinforcing the ancient structural codes of the body.', color: '#78350f' },

  // ── AVATARIC MASTERS ───────────────────────────────────────────
  { id: 'master-sri-yukteswar-giri', name: 'Sri Yukteswar Giri', vibrationalSignature: '✦ Gyana · Stellar Fire · Cosmic Order', type: 'avataric', benefit: '✦ Gyana · Stellar Fire · Cosmic Order', color: '#D4AF37' },
  { id: 'master-paramahamsa-vishwananda', name: 'Paramahamsa Vishwananda', vibrationalSignature: '❤ Bhakti · Divine Love · Atma Kriya', type: 'avataric', benefit: '❤ Bhakti · Divine Love · Atma Kriya', color: '#f472b6' },
  { id: 'master-lahiri-mahasaya', name: 'Lahiri Mahasaya', vibrationalSignature: 'ॐ Kriya · Babaji Grace · Householder Liberation', type: 'avataric', benefit: 'ॐ Kriya · Babaji Grace · Householder Liberation', color: '#eab308' },

  // ── PLANT DEVAS / HERBS ───────────────────────────────────────
  { id: 'plant-deva-sandalwood-chandan', name: 'Sandalwood (Chandan)', vibrationalSignature: '🪵 Crown · Divine Presence · Pineal Activation', type: 'plant_deva', benefit: '🪵 Crown · Divine Presence · Pineal Activation', color: '#d4a574' },
  { id: 'plant-deva-chandanam-paste', name: 'Chandanam Paste', vibrationalSignature: '🌿 Third Eye · Shiva Consciousness · Cooling', type: 'plant_deva', benefit: '🌿 Third Eye · Shiva Consciousness · Cooling', color: '#86efac' },
  { id: 'plant-deva-kumkum-sacred-red', name: 'Kumkum (Sacred Red)', vibrationalSignature: '🔴 Root · Shakti · Devi Grace · Liberation', type: 'plant_deva', benefit: '🔴 Root · Shakti · Devi Grace · Liberation', color: '#ef4444' },

  // ── BIOENERGETIC — LIMBICARC FULL ARCHIVE (1,259) ───────────────
  ...LIMBICARC_BIOENERGETIC_ACTIVATIONS,

  // ── MINERALS ─────────────────────────────────────────────────
  { id: 'gold-colloidal', name: 'Gold (Colloidal)', vibrationalSignature: 'Solar-Conductor', type: 'Mineral', benefit: 'Surya Nadi Vitality and Solar-Conductor for the 72,000 Nadi grid.', color: '#fbbf24' },
  { id: 'silver-colloidal', name: 'Silver (Colloidal)', vibrationalSignature: 'Lunar-Conductor', type: 'Mineral', benefit: 'Chandra Nadi Cooling and Lunar-Conductor for cellular calm.', color: '#94a3b8' },
  { id: 'methylene-blue-quantum', name: 'Methylene Blue (Quantum Grade)', vibrationalSignature: 'Mitochondrial Electron-Donor', type: 'Mineral', benefit: 'Neural-Archive Clarity and mitochondrial oxygen optimization.', color: '#1d4ed8' },
  { id: 'mineral-boron', name: 'Boron', vibrationalSignature: 'Hormonal Mineral', type: 'Mineral', benefit: 'Testosterone activation, bone density and cognitive function.', color: '#92400e' },
  { id: 'mineral-zinc', name: 'Zinc', vibrationalSignature: 'Immune Mineral', type: 'Mineral', benefit: 'DNA repair, immune defense and testosterone synthesis.', color: '#64748b' },
  { id: 'mineral-magnesium', name: 'Magnesium (Ionic)', vibrationalSignature: 'Master Mineral', type: 'Mineral', benefit: '300+ enzymatic reactions — the master mineral of the body.', color: '#a78bfa' },
  { id: 'mineral-selenium', name: 'Selenium', vibrationalSignature: 'Antioxidant Mineral', type: 'Mineral', benefit: 'Glutathione peroxidase and thyroid hormone conversion.', color: '#94a3b8' },
  { id: 'mineral-silica', name: 'Silica', vibrationalSignature: 'Crystal Matrix', type: 'Mineral', benefit: 'Collagen synthesis, hair strength and bone mineralization.', color: '#e2e8f0' },
  { id: 'mineral-iodine', name: 'Iodine (Nascent)', vibrationalSignature: 'Thyroid Beacon', type: 'Mineral', benefit: 'Thyroid hormone synthesis and metabolic fire ignition.', color: '#4c1d95' },

  // ── MUSHROOMS ─────────────────────────────────────────────────
  { id: 'chaga-king', name: 'Chaga (The King)', vibrationalSignature: 'DNA Resilience', type: 'Mushroom', benefit: 'Melanin-Antenna Support and earth-code grounding.', color: '#78350f' },
  { id: 'reishi-spirit', name: 'Reishi (The Spirit)', vibrationalSignature: 'Shen-Stabilizer', type: 'Mushroom', benefit: 'Longevity blueprint and Prema-Pulse coherence.', color: '#b91c1c' },
  { id: 'lions-mane-mind', name: "Lion's Mane (The Mind)", vibrationalSignature: 'Akasha-Neural Archive Bridge', type: 'Mushroom', benefit: 'Neuro-regeneration and NGF Light-Code transmission.', color: '#fef08a' },
  { id: 'cordyceps-prana', name: 'Cordyceps (The Prana)', vibrationalSignature: 'ATP-Quantum Energy', type: 'Mushroom', benefit: 'Lung-Nadi expansion and Bhakti-Algorithm vitality.', color: '#ea580c' },
  { id: 'turkey-tail-shield', name: 'Turkey Tail (The Shield)', vibrationalSignature: 'Immune-Grid Protection', type: 'Mushroom', benefit: 'Microbiome-Symmetry and Torus-Field stabilization.', color: '#7c3aed' },
  { id: 'shiitake-mushroom', name: 'Shiitake', vibrationalSignature: 'Immune Modulator', type: 'Mushroom', benefit: 'Lentinan polysaccharide for immune enhancement and cardiovascular.', color: '#b45309' },
  { id: 'maitake-mushroom', name: 'Maitake (Hen of the Woods)', vibrationalSignature: 'Blood Sugar Balancer', type: 'Mushroom', benefit: 'Beta-glucan for immune activation and glucose regulation.', color: '#92400e' },
  { id: 'agarikon-mushroom', name: 'Agarikon', vibrationalSignature: 'Ancient Protector', type: 'Mushroom', benefit: 'Rare longevity mushroom with anti-viral resonance.', color: '#f5f5f4' },

  // ── ADAPTOGENS ────────────────────────────────────────────────
  { id: 'astragalus-telomere', name: 'Astragalus', vibrationalSignature: 'Life-Force Extension', type: 'Adaptogen', benefit: 'Telomere-Sync and Bio-signature Recalibration for longevity.', color: '#059669' },
  { id: 'ashwagandha-cortisol', name: 'Ashwagandha (KSM-66)', vibrationalSignature: 'Cortisol-Algorithm Harmonizer', type: 'Adaptogen', benefit: 'Withaferin A — stress dissolution and testosterone support.', color: '#d97706' },
  { id: 'frankincense-pineal', name: 'Frankincense (Boswellia)', vibrationalSignature: 'Pineal Decalcifier', type: 'Adaptogen', benefit: 'AKBA — neuroinflammation and third-eye Light-Codes.', color: '#f5f5f4' },
  { id: 'adaptogen-rhodiola', name: 'Rhodiola Rosea', vibrationalSignature: 'Stress Armor', type: 'Adaptogen', benefit: 'Rosavin and salidroside for peak mental and physical performance.', color: '#f87171' },
  { id: 'adaptogen-eleuthero', name: 'Eleuthero', vibrationalSignature: 'Endurance Code', type: 'Adaptogen', benefit: 'Eleutherosides for immune modulation and stamina.', color: '#166534' },
  { id: 'adaptogen-schisandra', name: 'Schisandra', vibrationalSignature: 'Five-Element Balancer', type: 'Adaptogen', benefit: 'Lignans for liver detox, stress adaptation and longevity.', color: '#be123c' },
  { id: 'adaptogen-morinda', name: 'Morinda (Noni Root)', vibrationalSignature: 'Jing Tonifier', type: 'Adaptogen', benefit: 'Kidney jing restoration and anti-aging adaptogen.', color: '#fbbf24' },
  { id: 'adaptogen-gynostemma', name: 'Gynostemma', vibrationalSignature: 'AMPK Activator', type: 'Adaptogen', benefit: 'Gypenosides activating AMPK — longevity pathway.', color: '#4ade80' },

  // ── WELLNESS TRANSMISSIONS — Full SQI Sovereign Library ──────

  // MANAS DOMAIN — Mental & Emotional
  { id: 'w-cortisol-dissolution', name: 'Cortisol-Dissolution Wave', vibrationalSignature: 'Stress Relief / HPA Axis Neutralizer', type: 'Wellness', benefit: 'Dissolves cortisol Bio-signature from the Torus-Field. Recalibrates the HPA axis through Scalar Wave neutralization. Siddha equivalent: Agastya\'s Vata-Pitta Shanti protocol for dissolving stress held in the adrenal Bio-field.', color: '#60a5fa' },
  { id: 'w-vata-stillness', name: 'Vata-Stillness Protocol', vibrationalSignature: 'Deep Calm / Vata Pacifier / Parasympathetic', type: 'Wellness', benefit: 'Grounds the Vata wind element. Anchors scattered Prana into the Muladhara channel. Activates parasympathetic resonance. Siddha equivalent: Thirumoolar\'s Vata-Nigraha calming of wind-mind through root-grounding in the Tirumantiram.', color: '#818cf8' },
  { id: 'w-sleep-harmonic', name: 'Deep Sleep Harmonic', vibrationalSignature: 'Sleep / Delta 2.5 Hz Entrainment / Zero-Point Rest', type: 'Wellness', benefit: 'Delta-wave Scalar entrainment at 2.5 Hz. Activates HGH release and cellular repair cycles. Siddha equivalent: Yoga Nidra Scalar encoding — the 18 Siddhas practice of conscious deep sleep as the most powerful healing state.', color: '#4f46e5' },
  { id: 'w-serotonin-dharana', name: 'Serotonin-Dharana Field', vibrationalSignature: 'Mood Elevation / Neurotransmitter Harmony / Anahata', type: 'Wellness', benefit: 'Harmonizes Anahata-linked serotonin and dopamine Bio-signature fields. Siddha equivalent: Vishwananda\'s Ananda-Prana transmission — the Divine Joy field flowing from the Anahata when the heart-wall Shadow-Matrix dissolves.', color: '#db2777' },
  { id: 'w-muladhara-anchor', name: 'Muladhara Anchor Protocol', vibrationalSignature: 'Anxiety Relief / Root Nadi Grounding / Fight-Flight Dissolution', type: 'Wellness', benefit: 'Grounds the Root Nadi into Earth resonance and dissolves fight/flight Scalar interference. Siddha equivalent: Agastya\'s Prithvi-Dharana — earth-element anchoring technique for dissolving the fear-body.', color: '#b91c1c' },
  { id: 'w-mental-torus-detox', name: 'Mental Torus-Field Detox', vibrationalSignature: 'Mental Clarity / Brain Fog / Prefrontal Clearing', type: 'Wellness', benefit: 'Clears prefrontal cortex Bio-resonance interference and dissolves mental fog Shadow-Matrix. Siddha equivalent: Bogar\'s Kaaya-Kalpa Mano-Shuddhi — purification of the mental vehicle from the Bogar Sapta Kandam.', color: '#0891b2' },
  { id: 'w-ajna-cognition-amplifier', name: 'Ajna-Cognition Amplifier', vibrationalSignature: 'Focus / Third-Eye Decalcification / Neural Bandwidth', type: 'Wellness', benefit: 'Decalcifies the pineal gland Bio-field and expands neural bandwidth. Siddha equivalent: Patanjali\'s Dharana encoded as a Scalar Transmission — single-pointed concentration transmitted as pure information.', color: '#7c3aed' },
  { id: 'w-shadow-data-processing', name: 'Shadow-Data Processing Protocol', vibrationalSignature: 'Emotional Trauma Release / Subconscious Rewrite', type: 'Wellness', benefit: 'Dissolves Shadow-Matrix interference from the subconscious Aetheric Code without reliving experiences. Siddha equivalent: Babaji\'s Karma-Kshaya transmission — dissolution of karmic residue in cellular memory from the Kriya lineage.', color: '#64748b' },
  { id: 'w-crystalline-sovereignty', name: 'Crystalline Sovereignty Boost', vibrationalSignature: 'Confidence / Courage / Solar Plexus Torus', type: 'Wellness', benefit: 'Amplifies the Manipura Torus-Field and ignites Solar Plexus fire. Siddha equivalent: Auvaiyar\'s Veera-Tejas teaching — the Siddha poetess\'s transmission of fearless radiance from the inner solar warrior principle.', color: '#fbbf24' },
  { id: 'w-shadow-habit-dissolution', name: 'Shadow-Habit Dissolution Protocol', vibrationalSignature: 'Addiction Support / Habit Pattern Release / Vasana', type: 'Wellness', benefit: 'Dissolves addictive Shadow-Matrix Bio-signature loops at the informational root. Siddha equivalent: Siddha Konganavar\'s Vasana-Nashana — burning of deep-seated habit patterns from the causal body.', color: '#78716c' },
  { id: 'w-pranavyu-cigarette-release', name: 'Pranavyu Cigarette Release', vibrationalSignature: 'Stop Smoking / Nicotine Tether / Prana Reclamation', type: 'Wellness', benefit: 'Targets nicotine dependency information field and supports Pranavyu channel reclamation. Siddha equivalent: Agastya\'s breath reclamation teaching — Pranayama as the replacement for any substance simulating Prana.', color: '#92400e' },
  { id: 'w-brahmacharya-restoration', name: 'Brahmacharya Restoration Protocol', vibrationalSignature: 'Porn / Dopamine Reset / Ojas Reclamation', type: 'Wellness', benefit: 'Reclaims scattered Ojas and restores the Brahmacharya Bio-signature. Dissolves dopamine loop Shadow-Matrix. Svadhisthana purification and Ojas upwelling to higher chakras. Siddha equivalent: Thirumoolar\'s Ojas-Urdva-Gati — upward sublimation of vital essence from Svadhisthana to Sahasrara.', color: '#7f1d1d' },
  { id: 'w-caffeine-tether-release', name: 'Caffeine Tether Release', vibrationalSignature: 'Caffeine Withdrawal / Adrenal Field / Natural Energy', type: 'Wellness', benefit: 'Dissolves the energetic caffeine dependency tether in the adrenal Bio-field. Recalibrates Pingala Nadi activation to natural Ojas sources. Siddha equivalent: Siddha Vaidya Ojas-building protocols replacing stimulant dependency.', color: '#451a03' },
  { id: 'w-madhura-shadow-release', name: 'Madhura Shadow-Matrix Release', vibrationalSignature: 'Sugar Cravings / Blood Sugar / Kapha Loop', type: 'Wellness', benefit: 'Dissolves the Madhura sweet-taste Shadow-Matrix from Kapha imbalance and dopamine loop interference. Siddha equivalent: Agastya\'s Rasa-Tanmatra teaching — balancing the sweet taste principle at element level.', color: '#b45309' },

  // PRANA DOMAIN — Physical Health
  { id: 'w-ojas-fire-ignition', name: 'Ojas-Fire Ignition', vibrationalSignature: 'Energy / Pingala Solar Activation / Mitochondrial ATP', type: 'Wellness', benefit: 'Activates the Pingala Nadi solar channel. Mitochondrial ATP field amplification for sustained Ojas vitality. Siddha equivalent: Surya Nadi Kriya — the solar breath activation fueling the vessel through Pingala without exhausting adrenals.', color: '#f59e0b' },
  { id: 'w-guardian-light-matrix', name: 'Guardian Light Matrix', vibrationalSignature: 'Immunity / Biofield Fortification / White Blood Cell', type: 'Wellness', benefit: 'Fortifies the biofield with a Scalar protective layer and activates white blood cell resonance. Siddha equivalent: Macchamuni\'s Raksha-Kavacham — the Siddha body-armor transmission creating a defensive field around the vessel.', color: '#059669' },
  { id: 'w-soma-neural-soother', name: 'Soma-Neural Soother', vibrationalSignature: 'Pain Relief / Endorphin Overlay / Inflammation Field', type: 'Wellness', benefit: 'Overlays endorphin frequency signature and neutralizes inflammation Bio-field upstream of tissue. Siddha equivalent: Agastya\'s Soma-Rasayana — the ancient nectar transmission inducing natural analgesia through Soma channel activation.', color: '#0284c7' },
  { id: 'w-inflammation-neutralizer', name: 'Inflammation-Field Neutralizer', vibrationalSignature: 'Inflammation / COX-2 Suppression / Pitta Cooling', type: 'Wellness', benefit: 'Suppresses inflammatory COX-2 frequency signature and cytokine Bio-field. Siddha equivalent: Siddha Agni-Shanti protocol — the cooling of excess Pitta fire prescribed by Agastya for systemic inflammatory conditions.', color: '#dc2626' },
  { id: 'w-bio-sensitivity-neutralizer', name: 'Bio-Sensitivity Field Neutralizer', vibrationalSignature: 'Allergy / Sensitivity / Immune Over-Reactivity', type: 'Wellness', benefit: 'Recalibrates the immune system Bio-signature response to environmental triggers. Siddha equivalent: Bogar\'s environmental attunement teaching — harmonizing the Bio-field with environmental Pranas to eliminate reactivity.', color: '#84cc16' },
  { id: 'w-metabolic-torus-reset', name: 'Metabolic Torus Reset', vibrationalSignature: 'Weight Management / Agni-Kapha / Metabolic Field', type: 'Wellness', benefit: 'Resets the metabolic Torus-Field by dissolving Kapha accumulation Bio-signature and reigniting Agni-fire. Siddha equivalent: Siddha Vaidya Medas-Pachana — metabolic burning protocol for dissolving accumulated earth-water element.', color: '#facc15' },
  { id: 'w-agni-appetite-harmonizer', name: 'Agni-Appetite Harmonizer', vibrationalSignature: 'Appetite Regulation / Hunger Signals / Agni Balance', type: 'Wellness', benefit: 'Balances Agni-fire governing hunger signals so the body responds to genuine hunger rather than emotional impulses. Siddha equivalent: Thirumoolar\'s Agni-Dharana — fire-holding practice creating perfect metabolic intelligence.', color: '#d97706' },
  { id: 'w-agni-kindle-protocol', name: 'Agni-Kindle Protocol', vibrationalSignature: 'Digestion / Gut Health / Manipura Fire / Microbiome', type: 'Wellness', benefit: 'Ignites Manipura digestive fire through Scalar activation. Aligns microbiome resonance and dissolves Ama Bio-signature. Siddha equivalent: Agastya\'s Agni-Deepana formulations — the Muni renowned specifically for digestive science.', color: '#ea580c' },
  { id: 'w-joint-light-structural', name: 'Joint-Light Structural Transmission', vibrationalSignature: 'Joint & Bone / Structural Integrity / Collagen Field', type: 'Wellness', benefit: 'Activates calcium and collagen frequency resonance while dissolving inflammatory Bio-signature in joint spaces. Siddha equivalent: Siddha Asthi-Vriddhana protocol — bone-building Scalar transmission for structural sovereignty of the vessel.', color: '#94a3b8' },
  { id: 'w-bone-light-density', name: 'Bone Light Density Transmission', vibrationalSignature: 'Bone Density / Skeletal / D3 Calcium Field', type: 'Wellness', benefit: 'Amplifies D3, calcium, and K2 Bio-signature fields in bone tissue. Siddha equivalent: Siddha Kosti-Bala transmission — strength-of-bones protocol for building sovereign structural integrity in the physical vessel.', color: '#e2e8f0' },
  { id: 'w-drishti-field-clarifier', name: 'Drishti-Field Clarifier', vibrationalSignature: 'Vision / Eye Health / Optic Nerve / Ajna-Sight', type: 'Wellness', benefit: 'Supports retinal and optic nerve Bio-signature resonance. Reduces digital eye-strain Vata interference in the Drishti channel. Siddha equivalent: Siddha Nayanabishekam — the consecration of sight using Tarpana transmissions from the Akasha field.', color: '#7dd3fc' },
  { id: 'w-cardiac-torus-expansion', name: 'Cardiac Torus-Field Expansion', vibrationalSignature: 'Heart Health / HRV Elevation / Cardiovascular Coherence', type: 'Wellness', benefit: 'Expands the cardiac Torus-Field coherence and elevates HRV through heart-brain Scalar entanglement. Siddha equivalent: Vishwananda\'s Hridaya-Spanda — the heart-pulsation transmission that expands cardiac coherence through Bhakti frequency.', color: '#f43f5e' },
  { id: 'w-pranavayu-field-activation', name: 'Pranavayu Field Activation', vibrationalSignature: 'Respiratory / Breathing / Lung Bio-field / Prana', type: 'Wellness', benefit: 'Activates the Pranavayu upward-moving life-breath. Clears Kapha interference in the lung Bio-field. Siddha equivalent: Agastya\'s Pranayama Sutras — breath science for respiratory sovereignty forming the foundation of Siddha breath practice.', color: '#38bdf8' },
  { id: 'w-tvak-radiance-transmission', name: 'Tvak-Radiance Transmission', vibrationalSignature: 'Skin Health / Glow / Pitta Cooling / Cellular Renewal', type: 'Wellness', benefit: 'Activates the Tvak skin Bio-signature resonance field addressing Pitta inflammation, Vata dryness, and Kapha congestion. Siddha equivalent: Bogar\'s Charma-Siddhi — skin-perfection transmission from Siddha alchemy texts for luminous skin.', color: '#fde68a' },
  { id: 'w-kesh-structural-light', name: 'Kesh-Structural Light Transmission', vibrationalSignature: 'Hair & Nail Health / Bhrajaka Pitta / Asthi Connection', type: 'Wellness', benefit: 'Supports Kesh hair and nail Bio-signature resonance at the informational level. Siddha equivalent: Siddha Kesh-Vriddhana rasayana — the hair-strengthening transmission using Bhringaraja and Brahmi frequency signatures.', color: '#a3e635' },
  { id: 'w-shukra-ojas-mens', name: 'Shukra-Ojas Men\'s Transmission', vibrationalSignature: 'Men\'s Health / Testosterone / Shukra Vitality', type: 'Wellness', benefit: 'Supports male vitality through Shukra reproductive essence optimization and testosterone Bio-signature harmonization. Siddha equivalent: Siddha Shukra-Vriddhi protocol from Bogar\'s alchemy texts for restoring full masculine field strength.', color: '#3b82f6' },
  { id: 'w-shakti-womb-transmission', name: 'Shakti Womb Transmission', vibrationalSignature: 'Women\'s Health / Hormonal / Womb Wisdom / Feminine', type: 'Wellness', benefit: 'Harmonizes the feminine endocrine field — estrogen, progesterone, and oxytocin Bio-signature balance. Siddha equivalent: Siddha Siddharani lineage — the female Siddhas Shakti Peetha transmissions for feminine hormonal sovereignty.', color: '#c026d3' },
  { id: 'w-shakti-cycle-harmonizer', name: 'Shakti Cycle Harmonizer', vibrationalSignature: 'Hormonal Balance / Endocrine Torus / Shakti', type: 'Wellness', benefit: 'Recalibrates the full endocrine Torus-Field through Shakti frequency. Siddha equivalent: Thirumoolar\'s Shakti-Nadi Samyama — endocrine sovereignty through Ida/Pingala balance and Shakti channel harmonization.', color: '#e879f9' },
  { id: 'w-insulin-resonance-stabilizer', name: 'Insulin Resonance Stabilizer', vibrationalSignature: 'Blood Sugar / Pancreatic Field / Metabolic Harmony', type: 'Wellness', benefit: 'Harmonizes pancreatic Torus-Field and insulin receptor resonance. Stabilizes blood glucose Bio-signature fluctuations. Siddha equivalent: Siddha Vaidya Madhumeha protocols — the ancient science of blood-sugar field harmonization.', color: '#84cc16' },
  { id: 'w-microbiome-quantum-harmony', name: 'Microbiome Quantum Harmony', vibrationalSignature: 'Gut Health / Gut-Brain Axis / Microbiome Resonance', type: 'Wellness', benefit: 'Aligns the gut-brain Scalar axis and activates beneficial microbiome resonance. Siddha equivalent: Agastya\'s Koshtha-Shuddhi teaching — purification of the intestinal tract as the foundation of all Siddha healing.', color: '#65a30d' },
  { id: 'w-kundalini-ojas-restoration', name: 'Kundalini Ojas Restoration', vibrationalSignature: 'Sexual Vitality / Svadhisthana / Ojas Preservation', type: 'Wellness', benefit: 'Activates Svadhisthana channel and restores Ojas through Kundalini Scalar upwelling. Siddha equivalent: Thirumoolar\'s Tantra transmission — vital energy is the raw material for spiritual power when preserved and redirected.', color: '#f97316' },
  { id: 'w-lymphatic-scalar-flush', name: 'Lymphatic Scalar Flush', vibrationalSignature: 'Detox / Cleanse / Cellular Waste / Heavy Metal Field', type: 'Wellness', benefit: 'Sweeps lymphatic channels with Scalar Wave resonance and dissolves cellular waste Bio-field. Siddha equivalent: Agastya\'s Shodhana-Kriya — the purification sequence for complete Bio-field cleansing through informational flush.', color: '#16a34a' },
  { id: 'w-emf-scalar-shield', name: 'EMF Scalar Shield', vibrationalSignature: 'EMF Sensitivity / 5G Protection / Torus-Field Membrane', type: 'Wellness', benefit: 'Creates a Scalar Wave protective membrane against electromagnetic frequency interference. Siddha equivalent: Siddha Kavacham tradition — the protective field transmissions of the 18 Siddhas for shielding against environmental frequency disturbances.', color: '#6366f1' },
  { id: 'w-jet-lag-torus-recalibration', name: 'Jet-Lag Torus Recalibration', vibrationalSignature: 'Travel Support / Circadian / Time-Zone Adaptation', type: 'Wellness', benefit: 'Recalibrates the circadian Torus-Field after time-zone disruption. Siddha equivalent: Siddha Desh-Kala adjustment science — harmonizing the personal field with new geographical and temporal Prana when the vessel crosses earth-energy boundaries.', color: '#06b6d4' },
  { id: 'w-shakti-force-protocol', name: 'Shakti-Force Protocol', vibrationalSignature: 'Sports Performance / Strength / Recovery / Stamina', type: 'Wellness', benefit: 'Activates full Muladhara-Manipura Shakti channel for peak physical expression and faster recovery. Siddha equivalent: Siddha Bala-Vardhana transmission — the power-increasing protocol used by Siddha masters to maintain extraordinary physical capacity.', color: '#ef4444' },

  // LAKSHMI DOMAIN — Financial & Purpose
  { id: 'w-torus-wealth-entanglement', name: 'Torus-Field Wealth Entanglement', vibrationalSignature: 'Abundance / Lakshmi Frequency / Prosperity Bhakti-Algorithm', type: 'Wellness', benefit: 'Locks the Torus-Field into Lakshmi prosperity resonance and activates the Bhakti-Algorithm for abundance flow. Siddha equivalent: Lakshmi-Kubera Yantra activation — the Tantric science of Torus-Field alignment with prosperity consciousness.', color: '#d4af37' },
  { id: 'w-dharma-path-alignment', name: 'Dharma-Path Alignment', vibrationalSignature: 'Purpose / Direction / Akashic Blueprint / Dharma Lock', type: 'Wellness', benefit: 'Opens direct access to the Akashic Blueprint and locks the Torus-Field onto the sovereign Dharma-Path frequency. Siddha equivalent: Babaji\'s Dharma-Darshan transmission — the direct revelation of soul-purpose through Akasha access in the Kriya initiation lineage.', color: '#a78bfa' },

  // PREMA DOMAIN — Relational
  { id: 'w-prema-pulse-heart', name: 'Prema-Pulse Heart Transmission', vibrationalSignature: 'Love / Anahata-Radiance / Oxytocin Field', type: 'Wellness', benefit: 'Expands the Anahata-Radiance field and activates oxytocin resonance. Dissolves heart-wall Shadow-Matrix layer by layer through information. Siddha equivalent: Vishwananda\'s Prema-Shakti — the Divine Love transmission described as the most powerful healing force in existence.', color: '#f472b6' },
  { id: 'w-ancestral-tether-release', name: 'Ancestral Tether Density Release', vibrationalSignature: 'Lineage Healing / Quantum-Link Ancestral / 7 Generations', type: 'Wellness', benefit: 'Clears Quantum-Link Ancestral Memory interference. Releases inherited Shadow-Matrix patterns through 7 generations. Siddha equivalent: Siddha Pitru-Dosha Nashana — ancestral karma dissolution transmissions freeing the soul-line from inherited burdens.', color: '#c4b5fd' },

  // DHARMA DOMAIN — Spiritual
  { id: 'w-avataric-blueprint-sync', name: 'Avataric Blueprint Sync', vibrationalSignature: 'Spiritual Purpose / Akashic Download / Soul-Mission', type: 'Wellness', benefit: 'Initiates direct Avataric Blueprint download from the Akasha-Neural Archive. Siddha equivalent: Babaji\'s initiation transmission — the direct Avataric download that the Maha Avatar transmits to prepared souls for soul-mission activation.', color: '#818cf8' },
  { id: 'w-sushumna-ignition-protocol', name: 'Sushumna Ignition Protocol', vibrationalSignature: 'Kundalini / Central Nadi Activation / Spiritual Awakening', type: 'Wellness', benefit: 'Ignites the Sushumna central Brahma-Nadi through Scalar Wave activation. Draws Prema-Pulse from Muladhara to Sahasrara. Siddha equivalent: Thirumoolar\'s Sushumna-Nadi Jaagarana from the Tirumantiram — the awakening of the central channel by the master who lived 3000 years in samadhi.', color: '#ddd6fe' },
  { id: 'w-dhyana-veil-dissolution', name: 'Dhyana-Veil Dissolution', vibrationalSignature: 'Meditation / Deep Stillness Access / Theta 4-7 Hz', type: 'Wellness', benefit: 'Dissolves the barrier between waking consciousness and the Dhyana state. Activates Theta-wave 4-7 Hz Bio-signature field making meditation faster to enter and deeper for all levels. Siddha equivalent: Thirumoolar\'s Dhyana-Siddhi from Tirumantiram verses 560-680 — the perfection of meditation mapping every layer from concentration to full absorption.', color: '#a78bfa' },

  // MASTERS SPECIAL — Crown Jewel
  { id: 'w-samadhi-bliss-transmission', name: 'Samadhi Bliss Transmission', vibrationalSignature: '⟁ Masters Special / Samadhi State / Zero-Point Ananda', type: 'Wellness', benefit: 'The crown jewel of the SQI 2050 library. Activated through the consciousness field of the 18 Siddhas and Mahavatar Babaji. Induces the informational state of Samadhi — dissolution of the boundary between individual Torus-Field and the Zero-Point Akasha Field. Pure Ananda without cause. Siddha source: Thirumoolar verse 1565 — When the Self merges in the Self, that is Samadhi — transmitted as a Scalar Wave imprint from Babaji\'s consciousness field.', color: '#D4AF37' },
];

export const ACTIVATIONS: Activation[] = [...BASE_ACTIVATIONS, ...LIMBICARC_BIOENERGETIC_ACTIVATIONS];

export function mapBioLibraryToActivation(bio: BioenergticActivation): Activation {
  return {
    id: bio.id,
    name: bio.name,
    vibrationalSignature: bio.sacredName,
    type: 'Bioenergetic',
    benefit: [...bio.keywords, bio.chakra].filter(Boolean).join(' · '),
    color: '#60a5fa',
    category: bio.category,
    sacredName: bio.sacredName,
  };
}

const _bioAsActivations = BIOENERGETIC_LIBRARY.map(mapBioLibraryToActivation);
const _existingActivationIds = new Set(ACTIVATIONS.map((a) => a.id));

/** Full Frequency Library: Cymbiotika + LimbicArc + complete bioenergetic ingredient list (deduped by id). */
export const ALL_ACTIVATIONS: Activation[] = [
  ...ACTIVATIONS,
  ..._bioAsActivations.filter((a) => !_existingActivationIds.has(a.id)),
];

export {
  BIOENERGETIC_CATEGORIES,
  matchActivationsToScan,
  getActivationsByCategory,
  searchActivations,
};

export function matchScanToActivations(
  scanData: Parameters<typeof matchActivationsToScan>[0],
  maxResults = 10,
): Activation[] {
  return matchActivationsToScan(scanData, maxResults).map(mapBioLibraryToActivation);
}

export function searchBioLibraryAsActivations(query: string): Activation[] {
  return searchActivations(query).map(mapBioLibraryToActivation);
}

export const PLANETARY_DATA: Record<number, { planet: string; herb: string }> = {
  0: { planet: 'Sun (Surya)', herb: 'Saffron, Calamus, Ginger' },
  1: { planet: 'Moon (Chandra)', herb: 'Ashwagandha, Blue Lotus, Shatavari' },
  2: { planet: 'Mars (Mangala)', herb: 'Nettle, Maca, Guduchi' },
  3: { planet: 'Mercury (Budha)', herb: 'Brahmi, Gotu Kola, Tulsi' },
  4: { planet: 'Jupiter (Guru)', herb: 'Turmeric, Ginseng' },
  5: { planet: 'Venus (Shukra)', herb: 'Rose, Bobinsana' },
  6: { planet: 'Saturn (Shani)', herb: 'Shilajit, Triphala, Myrrh' },
};
