ALTER TABLE public.email_teachings DROP CONSTRAINT IF EXISTS email_teachings_theme_check;
ALTER TABLE public.email_teachings ADD CONSTRAINT email_teachings_theme_check CHECK (theme IN (
  'abundance','ayurveda','jyotish','mantra_practice',
  'bhakti_devotion','protection','pranayama','general',
  'mudra','sacred_geometry','kriya_yoga','water_alchemy','brahmacharya',
  'longevity','mediumship'
));

INSERT INTO public.email_teachings (theme, title, body_text, source_note) VALUES
('bhakti_devotion', 'Initiation Before Birth', 'Paramahansa Yogananda''s tradition holds that his spiritual initiation quietly began before he could even understand it — a sound sealed within an amulet by his mother, only recognized years later when his own teacher gave him the same syllable. Some transmissions, this story suggests, are planted long before we''re ready to receive them consciously.', 'My Parents and Early Life — Yogananda Codex'),
('bhakti_devotion', 'Recognizing What Was Already There', 'A defining moment across many Bhakti lineages, including Yogananda''s, is the instant of recognizing a teaching you didn''t consciously know you already carried. If something in this app ever feels oddly familiar rather than new, the tradition would say: trust that.', 'Guru lineage recognition — Yogananda Codex'),
('mantra_practice', 'A Name That Is Also a Breath Practice', 'The name of Rama, chanted in the traditional way, is held by some Siddha teachers to function as a complete Pranayama circuit in itself — the sound structure naturally regulating breath as it''s repeated. This is one reason Rama Nama japa is considered accessible even to those who''ve never formally studied breathwork.', 'Rāma''s Name is a Complete Prāṇāyāma Circuit — Ramayana Codex'),
('bhakti_devotion', 'The Curse That Became Scripture', 'The Ramayana itself, in its origin story, begins with a moment of spontaneous grief transforming into the first verse of Sanskrit poetry ever composed — sorrow becoming, quite literally, the birth of a sacred form. The tradition holds that even our hardest moments can become something that outlasts the pain that created them.', 'The Curse That Became Scripture — Ramayana Codex, Bāla Kāṇḍa'),
('bhakti_devotion', 'The Hidden Curriculum', 'Sage Vasishtha''s teachings to young Rama, woven through the Ramayana''s early chapters, are read by some scholars as a complete yogic curriculum disguised inside a devotional epic. Sacred stories, in this tradition, are rarely just stories — they''re teaching structures wearing narrative clothing.', 'Vasiṣṭha''s Yoga — Ramayana Codex'),
('longevity', 'The Science of Renewal', 'Kayakalpa, the Siddha science of bodily renewal attributed to the sage Bogar, holds that aging is not a fixed, unavoidable process but a rate that can be genuinely slowed through specific practice. This is a considerably older and more precise claim than most modern longevity trends realize.', 'Bogar''s Revelation — Kayakalpa Academy'),
('longevity', 'The 7,000-Verse Code', 'The Bogar Sapta Kandam, a 7,000-verse text, is one of the primary sources for Kayakalpa practice — a body of knowledge dense enough that most practitioners spend years, not weeks, working through even its foundational layer. Depth, in this tradition, was never meant to be rushed.', 'Bogar Sapta Kandam — Kayakalpa Academy'),
('ayurveda', 'What Modern Science Is Still Catching Up To', 'The Ojas Prakarana teachings hold that vital essence — Ojas — was mapped by the Siddhas with a precision Western physiology is only beginning to approach through concepts like immune reserve and stress resilience. What''s taught here as ancient is, in several respects, ahead of where conventional science currently stands.', 'Ojas Prakarana: The Foundation Teachings — Ojas Rasayana Academy'),
('pranayama', 'The Vedic Anatomy of Life Force', 'Breatharian teaching in this tradition maps the Five Pranas as a complete internal anatomy of life force, distinct from and more subtle than the physical organs modern medicine studies. Understanding even one of the five — which governs which function — changes how you read your own energy day to day.', 'The Five Pranas — Breatharian Academy'),
('pranayama', 'Preparing the Body, Not Forcing It', 'The Siddha Diet Bridge teaches that any advanced breath or fasting practice requires the body be prepared first — attempting depth before foundation is considered a common and avoidable mistake. Patience with sequence, this tradition insists, is itself part of the practice.', 'The Siddha Diet Bridge — Breatharian Academy'),
('ayurveda', 'Beyond Hunger', 'Upavasa, the Siddha science of fasting, defines the practice as something considerably deeper than simply not eating — the Vedic definition centers on drawing closer to one''s own true nature, with the digestive rest as a side effect rather than the point. The reframe matters: this was never primarily about restriction.', 'Upavasa — The Sacred Science of Siddha Fasting'),
('pranayama', 'The Living Intelligence', 'Thirumoolar, in the Thirumantiram, describes Prana not as mere air but as a living intelligence moving through the body with its own awareness — verses 700 through 720 dedicate themselves entirely to this teaching. It''s a genuinely different way of relating to your own breath than most people were ever taught.', 'Prana — The Living Intelligence, Thirumantiram Verses 700–720'),
('mediumship', 'A Technology, Not a Gift', 'Siddha teaching on mediumship makes a deliberate distinction: this is framed as a learnable technology available to trained practitioners, not a rare gift only some people are born with. That reframing changes what''s possible for someone willing to actually study it.', 'Mediumship Is Not a Gift — It Is a Technology, Siddha Mediumship Academy'),
('mediumship', 'The Built-In Receiver', 'The Antahkarana, the subtle inner instrument of mind in Vedic philosophy, is described in this tradition as functioning like a built-in receiver for communication beyond the ordinary senses — already present in everyone, mostly unused. The practice, in this view, is less about acquiring an ability and more about learning to use equipment you already have.', 'The Antahkarana Antenna — Siddha Mediumship Academy');