ALTER TABLE public.email_teachings DROP CONSTRAINT IF EXISTS email_teachings_theme_check;
ALTER TABLE public.email_teachings ADD CONSTRAINT email_teachings_theme_check CHECK (theme IN (
  'abundance','ayurveda','jyotish','mantra_practice',
  'bhakti_devotion','protection','pranayama','general',
  'mudra','sacred_geometry','kriya_yoga','water_alchemy','brahmacharya'
));

INSERT INTO public.email_teachings (theme, title, body_text, source_note) VALUES
('mudra', 'The Seal of Supreme Wisdom', 'Gyan Mudra — thumb and index finger touching, the most recognized hand seal in the yogic world — is held to redirect the body''s subtle current back toward the mind, sharpening concentration. It costs nothing and takes one second to form; try it for the next minute you spend reading anything today.', 'Gyan Mudra — Pancha Tattva Mudras, Mudra Academy'),
('mudra', 'The Seal of Life Force', 'Prana Mudra activates what the tradition calls the life-force current, said to reduce fatigue and sharpen the senses within minutes. Thumb touches ring and little finger — a shape simple enough to hold discreetly in any meeting or quiet moment.', 'Prana Mudra — Pancha Tattva Mudras, Mudra Academy'),
('mudra', 'The Heart Rescue Seal', 'Apan Vayu Mudra, sometimes called Mritasanjivani — literally "life-restoring" — is traditionally used the moment someone feels heart-area tightness or panic rising. It is one of the few mudras taught specifically as an emergency tool, not just a meditative one.', 'Apan Vayu Mudra — Nadi Awakening Mudras, Mudra Academy'),
('mudra', 'The Third Eye Power Seal', 'Hakini Mudra — fingertips of both hands touching, forming a small dome — is used before study or decision-making, said to bridge the two hemispheres of the brain into clearer, more integrated thought. Teachers in this tradition often hold it silently before speaking.', 'Hakini Mudra — Nadi Awakening Mudras, Mudra Academy'),
('sacred_geometry', 'The Blueprint of the Universe', 'The Flower of Life — a pattern of overlapping circles found carved into temples across multiple ancient civilizations independently — is considered a geometric record of how creation itself unfolds, circle by circle. Its recurrence across unconnected cultures is part of why it''s taken so seriously.', 'The Flower of Life — Sacred Geometry Academy'),
('sacred_geometry', 'Five Perfect Forms', 'The Platonic Solids — five three-dimensional shapes where every face, angle, and edge is identical — were mapped by the ancients onto the five elements themselves: earth, water, fire, air, and ether. Plato held that these shapes were the literal architecture beneath physical matter.', 'The Platonic Solids — Sacred Geometry Academy'),
('sacred_geometry', 'The Architecture of All Matter', 'Metatron''s Cube, built from thirteen circles connected by straight lines, is said to contain all five Platonic Solids within it — a kind of master key underlying the other sacred forms. Practitioners often use it as a visual anchor during protection or clearing work.', 'Metatron''s Cube — Sacred Geometry Academy'),
('sacred_geometry', 'The Number Nature Keeps Choosing', 'The Golden Ratio and the Fibonacci sequence appear in nautilus shells, flower petals, and galaxy spirals with a consistency that has fascinated mathematicians and mystics alike. The Siddhas held this recurrence as evidence of a single underlying intelligence behind all form.', 'The Golden Ratio & Fibonacci — Sacred Geometry Academy'),
('kriya_yoga', 'The Sound Before Kriya Had a Name', 'Paranada Meditation is held as the original practice underlying Kriya Yoga — attention placed not on breath or mantra but on the subtlest inner sound, said to exist before any technique was ever formalized. It is considered less a technique than a return to something already present.', 'The Primordial Sound — Kriya Yoga Mastery'),
('kriya_yoga', 'The Guardian Across the Ages', 'Mahavatar Babaji is held in this lineage as an immortal presence who has preserved and transmitted the Kriya Yoga teaching across centuries, appearing to different masters at different times rather than teaching publicly. His presence is invoked, not historically documented — a distinction the tradition holds consciously.', 'Mahavatar Babaji — Kriya Yoga Mastery'),
('kriya_yoga', 'One Continuous Transmission', 'The 18 Siddhas are held to have carried the Kriya transmission forward not as eighteen separate teachings but as one continuous current passed hand to hand, generation to generation. When you practice within this lineage, the tradition holds you are receiving something considerably older than any single teacher.', 'The 18 Siddhas and the Kriya Transmission — Kriya Yoga Mastery'),
('water_alchemy', 'Drinking Starlight', 'The Siddhas taught that the water in your body traces its origin to cosmic sources predating the Earth itself — a claim modern astrophysics has, remarkably, come to confirm about water''s cosmic origins. The water you drink tonight has, in some literal sense, an ancient story behind it.', 'The Cosmic Birth of Water — Siddha Water Alchemy'),
('water_alchemy', 'The Moon Governs More Than Tides', 'Chandra, the moon, is held in this tradition to govern not just ocean tides but every fluid system in your own body — a connection Ayurveda and Siddha medicine both take seriously in timing practices and treatments. Notice, over a full lunar cycle, whether your own energy and fluid retention shift with it.', 'Chandra — The Moon''s Governance of Your Water Body, Siddha Water Alchemy'),
('water_alchemy', 'Three Levels of Thirst', 'Siddha teaching distinguishes three levels of dehydration, the deepest of which produces no obvious physical thirst signal at all — meaning by the time you feel thirsty, an earlier stage has often already passed unnoticed. Drinking on a rhythm, not only on sensation, is the practice this teaching points toward.', 'Siddha Water Timing — Siddha Water Alchemy'),
('water_alchemy', 'Living Water', 'Certain rivers in the Vedic tradition are held not merely as sacred symbols but as carrying an active healing intelligence in the water itself — a claim tied to specific mineral compositions, flow patterns, and centuries of ritual use converging on the same sites. The reverence for these rivers was never only symbolic.', 'Sacred Rivers — Siddha Water Alchemy'),
('brahmacharya', 'Beyond Celibacy', 'Brahmacharya in the Siddha understanding is not primarily about abstinence — it is about the conscious direction of a specific energy, one that can be channeled toward creation or toward depletion depending entirely on awareness. The Western conflation with simple repression misses what the tradition actually teaches.', 'The Siddha Definition of Brahmacharya — Brahmacharya Academy'),
('brahmacharya', 'The Energy Trinity', 'Ojas, Tejas, and Prana are held as three interconnected fires within the body — vitality, radiance, and life force — and Brahmacharya practice is understood as the art of tending all three together, not restricting any one of them in isolation. Depletion in one tends to show up eventually in the others.', 'The 3 Fires — Brahmacharya Academy'),
('brahmacharya', 'Thirumoolar''s Teaching', 'The Siddha sage Thirumoolar taught that creative energy, rightly understood, is a unified expression of Shiva-Shakti consciousness rather than something to be merely suppressed or merely spent. This reframing — from restriction to right relationship — sits at the center of the whole Brahmacharya teaching.', 'Thirumoolar''s Revelation — Brahmacharya Academy');