ALTER TABLE public.announcements
ADD COLUMN IF NOT EXISTS title_sv TEXT,
ADD COLUMN IF NOT EXISTS title_no TEXT,
ADD COLUMN IF NOT EXISTS title_es TEXT,
ADD COLUMN IF NOT EXISTS content_sv TEXT,
ADD COLUMN IF NOT EXISTS content_no TEXT,
ADD COLUMN IF NOT EXISTS content_es TEXT;