-- ============================================
-- MQL Trading Bot System for Supabase
-- ============================================
-- This system manages MetaTrader Query Language (MQL) strategies,
-- signals, trades, and bot connections for the Shreem Brzee Freedom Bot

-- ============================================
-- 1. MQL Strategies Table
-- ============================================
-- Stores MQL4/MQL5 Expert Advisor (EA) strategies
CREATE TABLE IF NOT EXISTS public.mql_strategies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Strategy identification
  name TEXT NOT NULL,
  description TEXT,
  version TEXT NOT NULL DEFAULT '1.0',
  mql_version TEXT NOT NULL DEFAULT 'MQL5' CHECK (mql_version IN ('MQL4', 'MQL5')),
  
  -- Strategy code (stored as text for version control)
  mql_code TEXT, -- Full MQL source code
  mql_file_url TEXT, -- URL to .mq4/.mq5 file if stored externally
  
  -- Strategy parameters (JSONB for flexible configuration)
  default_parameters JSONB DEFAULT '{}'::jsonb,
  
  -- Strategy metadata
  author TEXT,
  category TEXT CHECK (category IN ('scalping', 'swing', 'trend_following', 'mean_reversion', 'arbitrage', 'copy_trading', 'custom')),
  risk_level TEXT NOT NULL DEFAULT 'medium' CHECK (risk_level IN ('low', 'medium', 'high', 'very_high')),
  
  -- Performance metrics (historical)
  total_trades INTEGER DEFAULT 0,
  win_rate DECIMAL(5, 2) DEFAULT 0, -- Percentage
  profit_factor DECIMAL(10, 2) DEFAULT 0,
  max_drawdown DECIMAL(10, 2) DEFAULT 0, -- Percentage
  average_win DECIMAL(18, 8) DEFAULT 0,
  average_loss DECIMAL(18, 8) DEFAULT 0,
  
  -- Status and visibility
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_public BOOLEAN NOT NULL DEFAULT false, -- Public strategies can be copied by other users
  is_premium BOOLEAN NOT NULL DEFAULT false, -- Premium strategies require subscription
  
  -- Pricing (if premium)
  price_usd DECIMAL(10, 2) DEFAULT 0,
  subscription_price_usd DECIMAL(10, 2) DEFAULT 0, -- Monthly subscription
  
  -- Metadata
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================
-- 2. MQL Signals Table
-- ============================================
-- Stores trading signals generated by MQL strategies
CREATE TABLE IF NOT EXISTS public.mql_signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Strategy reference
  strategy_id UUID NOT NULL REFERENCES public.mql_strategies(id) ON DELETE CASCADE,
  
  -- Signal identification
  signal_type TEXT NOT NULL CHECK (signal_type IN ('buy', 'sell', 'close', 'modify')),
  symbol TEXT NOT NULL, -- Trading pair (e.g., 'EURUSD', 'BTCUSDT')
  timeframe TEXT, -- MQL timeframe (e.g., 'M1', 'M5', 'H1', 'D1')
  
  -- Signal details
  entry_price DECIMAL(18, 8),
  stop_loss DECIMAL(18, 8),
  take_profit DECIMAL(18, 8),
  lot_size DECIMAL(10, 2), -- Position size
  leverage INTEGER DEFAULT 1,
  
  -- Signal metadata
  signal_strength DECIMAL(5, 2) DEFAULT 0, -- 0-100 confidence score
  reason TEXT, -- Why this signal was generated
  indicators_data JSONB DEFAULT '{}'::jsonb, -- Technical indicator values at signal time
  
  -- Status
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'executed', 'rejected', 'expired', 'cancelled')),
  
  -- Execution tracking
  executed_at TIMESTAMPTZ,
  executed_price DECIMAL(18, 8),
  execution_trade_id UUID, -- References mql_trades.id
  
  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ -- Signal expiration time
);

-- ============================================
-- 3. MQL Trades Table
-- ============================================
-- Stores executed trades from MQL strategies
CREATE TABLE IF NOT EXISTS public.mql_trades (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- User and strategy reference
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_id UUID REFERENCES public.mql_strategies(id) ON DELETE SET NULL,
  signal_id UUID REFERENCES public.mql_signals(id) ON DELETE SET NULL,
  
  -- Trade identification
  trade_ticket TEXT UNIQUE, -- MT4/MT5 ticket number
  symbol TEXT NOT NULL,
  trade_type TEXT NOT NULL CHECK (trade_type IN ('buy', 'sell')),
  
  -- Trade details
  entry_price DECIMAL(18, 8) NOT NULL,
  exit_price DECIMAL(18, 8),
  stop_loss DECIMAL(18, 8),
  take_profit DECIMAL(18, 8),
  lot_size DECIMAL(10, 2) NOT NULL,
  leverage INTEGER DEFAULT 1,
  
  -- Financials
  profit_loss DECIMAL(18, 8) DEFAULT 0,
  profit_loss_usd DECIMAL(18, 2) DEFAULT 0, -- Converted to USD
  commission DECIMAL(18, 8) DEFAULT 0,
  swap DECIMAL(18, 8) DEFAULT 0,
  
  -- Status
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed', 'pending', 'cancelled', 'rejected')),
  
  -- Timestamps
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at TIMESTAMPTZ,
  duration_seconds INTEGER, -- Trade duration in seconds
  
  -- Broker/Platform info
  broker_name TEXT,
  account_number TEXT,
  platform TEXT CHECK (platform IN ('MT4', 'MT5', 'cTrader', 'other')),
  
  -- Metadata
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================
-- 4. User Bot Connections Table
-- ============================================
-- Stores user connections to trading bots/platforms
CREATE TABLE IF NOT EXISTS public.user_bot_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- User reference
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Connection details
  connection_name TEXT NOT NULL, -- User-friendly name
  platform TEXT NOT NULL CHECK (platform IN ('MT4', 'MT5', 'cTrader', 'solana', 'other')),
  broker_name TEXT,
  account_number TEXT,
  account_type TEXT, -- 'demo', 'live', 'cent'
  
  -- API/Connection credentials (encrypted)
  api_key TEXT, -- Encrypted API key
  api_secret TEXT, -- Encrypted API secret
  server_name TEXT, -- MT4/MT5 server name
  
  -- Connection status
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_verified BOOLEAN NOT NULL DEFAULT false,
  last_connected_at TIMESTAMPTZ,
  last_sync_at TIMESTAMPTZ,
  
  -- Balance tracking
  account_balance DECIMAL(18, 2) DEFAULT 0,
  account_equity DECIMAL(18, 2) DEFAULT 0,
  account_currency TEXT DEFAULT 'USD',
  
  -- Risk settings
  max_lot_size DECIMAL(10, 2),
  max_daily_loss DECIMAL(18, 2),
  max_daily_trades INTEGER,
  risk_per_trade_percent DECIMAL(5, 2) DEFAULT 1.0, -- Percentage of balance
  
  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  UNIQUE(user_id, account_number, platform)
);

-- ============================================
-- 5. User Strategy Subscriptions Table
-- ============================================
-- Tracks which users are subscribed to which strategies
CREATE TABLE IF NOT EXISTS public.user_strategy_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- References
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_id UUID NOT NULL REFERENCES public.mql_strategies(id) ON DELETE CASCADE,
  connection_id UUID REFERENCES public.user_bot_connections(id) ON DELETE CASCADE,
  
  -- Subscription details
  subscription_type TEXT NOT NULL DEFAULT 'copy' CHECK (subscription_type IN ('copy', 'signal_only', 'full_access')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'cancelled', 'expired')),
  
  -- Copy trading settings
  copy_percentage DECIMAL(5, 2) DEFAULT 100.0, -- Percentage of signals to copy
  lot_multiplier DECIMAL(5, 2) DEFAULT 1.0, -- Multiply lot size by this factor
  max_lot_size DECIMAL(10, 2), -- Override max lot size for this strategy
  
  -- Financials
  total_profit_loss DECIMAL(18, 2) DEFAULT 0,
  total_trades INTEGER DEFAULT 0,
  subscription_fee_paid DECIMAL(10, 2) DEFAULT 0,
  
  -- Timestamps
  subscribed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  
  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  UNIQUE(user_id, strategy_id)
);

-- ============================================
-- 6. MQL Performance Analytics Table
-- ============================================
-- Daily/weekly performance snapshots
CREATE TABLE IF NOT EXISTS public.mql_performance_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- References
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_id UUID REFERENCES public.mql_strategies(id) ON DELETE CASCADE,
  connection_id UUID REFERENCES public.user_bot_connections(id) ON DELETE CASCADE,
  
  -- Time period
  period_type TEXT NOT NULL CHECK (period_type IN ('daily', 'weekly', 'monthly')),
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  
  -- Performance metrics
  total_trades INTEGER DEFAULT 0,
  winning_trades INTEGER DEFAULT 0,
  losing_trades INTEGER DEFAULT 0,
  win_rate DECIMAL(5, 2) DEFAULT 0,
  
  total_profit_loss DECIMAL(18, 2) DEFAULT 0,
  total_profit DECIMAL(18, 2) DEFAULT 0,
  total_loss DECIMAL(18, 2) DEFAULT 0,
  profit_factor DECIMAL(10, 2) DEFAULT 0,
  
  max_drawdown DECIMAL(10, 2) DEFAULT 0,
  max_profit DECIMAL(18, 2) DEFAULT 0,
  average_win DECIMAL(18, 2) DEFAULT 0,
  average_loss DECIMAL(18, 2) DEFAULT 0,
  
  -- Account metrics
  starting_balance DECIMAL(18, 2) DEFAULT 0,
  ending_balance DECIMAL(18, 2) DEFAULT 0,
  return_percentage DECIMAL(10, 2) DEFAULT 0,
  
  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  UNIQUE(user_id, strategy_id, connection_id, period_type, period_start)
);

-- ============================================
-- INDEXES for Performance
-- ============================================
CREATE INDEX IF NOT EXISTS idx_mql_strategies_active ON public.mql_strategies(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_mql_strategies_public ON public.mql_strategies(is_public) WHERE is_public = true;
CREATE INDEX IF NOT EXISTS idx_mql_strategies_created_by ON public.mql_strategies(created_by);

CREATE INDEX IF NOT EXISTS idx_mql_signals_strategy ON public.mql_signals(strategy_id);
CREATE INDEX IF NOT EXISTS idx_mql_signals_status ON public.mql_signals(status);
CREATE INDEX IF NOT EXISTS idx_mql_signals_symbol ON public.mql_signals(symbol);
CREATE INDEX IF NOT EXISTS idx_mql_signals_created_at ON public.mql_signals(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_mql_trades_user ON public.mql_trades(user_id);
CREATE INDEX IF NOT EXISTS idx_mql_trades_strategy ON public.mql_trades(strategy_id);
CREATE INDEX IF NOT EXISTS idx_mql_trades_status ON public.mql_trades(status);
CREATE INDEX IF NOT EXISTS idx_mql_trades_symbol ON public.mql_trades(symbol);
CREATE INDEX IF NOT EXISTS idx_mql_trades_opened_at ON public.mql_trades(opened_at DESC);
CREATE INDEX IF NOT EXISTS idx_mql_trades_ticket ON public.mql_trades(trade_ticket);

CREATE INDEX IF NOT EXISTS idx_user_bot_connections_user ON public.user_bot_connections(user_id);
CREATE INDEX IF NOT EXISTS idx_user_bot_connections_active ON public.user_bot_connections(is_active) WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_user_strategy_subs_user ON public.user_strategy_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_strategy_subs_strategy ON public.user_strategy_subscriptions(strategy_id);
CREATE INDEX IF NOT EXISTS idx_user_strategy_subs_status ON public.user_strategy_subscriptions(status) WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_mql_performance_user ON public.mql_performance_analytics(user_id);
CREATE INDEX IF NOT EXISTS idx_mql_performance_strategy ON public.mql_performance_analytics(strategy_id);
CREATE INDEX IF NOT EXISTS idx_mql_performance_period ON public.mql_performance_analytics(period_type, period_start);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS on all tables
ALTER TABLE public.mql_strategies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mql_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mql_trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_bot_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_strategy_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mql_performance_analytics ENABLE ROW LEVEL SECURITY;

-- ============================================
-- RLS Policies for mql_strategies
-- ============================================
-- Users can view public strategies and their own strategies
CREATE POLICY "Users can view public strategies"
ON public.mql_strategies FOR SELECT
USING (is_public = true OR created_by = auth.uid());

-- Users can create their own strategies
CREATE POLICY "Users can create strategies"
ON public.mql_strategies FOR INSERT
WITH CHECK (created_by = auth.uid());

-- Users can update their own strategies
CREATE POLICY "Users can update own strategies"
ON public.mql_strategies FOR UPDATE
USING (created_by = auth.uid())
WITH CHECK (created_by = auth.uid());

-- Admins can do everything
CREATE POLICY "Admins can manage all strategies"
ON public.mql_strategies FOR ALL
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- ============================================
-- RLS Policies for mql_signals
-- ============================================
-- Users can view signals from strategies they own or are subscribed to
CREATE POLICY "Users can view relevant signals"
ON public.mql_signals FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.mql_strategies s
    WHERE s.id = mql_signals.strategy_id
    AND (s.created_by = auth.uid() OR s.is_public = true)
  )
  OR EXISTS (
    SELECT 1 FROM public.user_strategy_subscriptions uss
    WHERE uss.strategy_id = mql_signals.strategy_id
    AND uss.user_id = auth.uid()
    AND uss.status = 'active'
  )
);

-- System can insert signals (via edge functions)
CREATE POLICY "System can insert signals"
ON public.mql_signals FOR INSERT
WITH CHECK (true); -- Edge functions will handle auth

-- Admins can manage all signals
CREATE POLICY "Admins can manage all signals"
ON public.mql_signals FOR ALL
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- ============================================
-- RLS Policies for mql_trades
-- ============================================
-- Users can only view their own trades
CREATE POLICY "Users can view own trades"
ON public.mql_trades FOR SELECT
USING (user_id = auth.uid());

-- System can insert trades (via edge functions)
CREATE POLICY "System can insert trades"
ON public.mql_trades FOR INSERT
WITH CHECK (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));

-- Users can update their own trades
CREATE POLICY "Users can update own trades"
ON public.mql_trades FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Admins can manage all trades
CREATE POLICY "Admins can manage all trades"
ON public.mql_trades FOR ALL
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- ============================================
-- RLS Policies for user_bot_connections
-- ============================================
-- Users can only view their own connections
CREATE POLICY "Users can view own connections"
ON public.user_bot_connections FOR SELECT
USING (user_id = auth.uid());

-- Users can create their own connections
CREATE POLICY "Users can create own connections"
ON public.user_bot_connections FOR INSERT
WITH CHECK (user_id = auth.uid());

-- Users can update their own connections
CREATE POLICY "Users can update own connections"
ON public.user_bot_connections FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Users can delete their own connections
CREATE POLICY "Users can delete own connections"
ON public.user_bot_connections FOR DELETE
USING (user_id = auth.uid());

-- Admins can manage all connections
CREATE POLICY "Admins can manage all connections"
ON public.user_bot_connections FOR ALL
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- ============================================
-- RLS Policies for user_strategy_subscriptions
-- ============================================
-- Users can view their own subscriptions
CREATE POLICY "Users can view own subscriptions"
ON public.user_strategy_subscriptions FOR SELECT
USING (user_id = auth.uid());

-- Users can create their own subscriptions
CREATE POLICY "Users can create own subscriptions"
ON public.user_strategy_subscriptions FOR INSERT
WITH CHECK (user_id = auth.uid());

-- Users can update their own subscriptions
CREATE POLICY "Users can update own subscriptions"
ON public.user_strategy_subscriptions FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Users can delete their own subscriptions
CREATE POLICY "Users can delete own subscriptions"
ON public.user_strategy_subscriptions FOR DELETE
USING (user_id = auth.uid());

-- Admins can manage all subscriptions
CREATE POLICY "Admins can manage all subscriptions"
ON public.user_strategy_subscriptions FOR ALL
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- ============================================
-- RLS Policies for mql_performance_analytics
-- ============================================
-- Users can view their own performance
CREATE POLICY "Users can view own performance"
ON public.mql_performance_analytics FOR SELECT
USING (user_id = auth.uid());

-- System can insert performance data (via edge functions)
CREATE POLICY "System can insert performance"
ON public.mql_performance_analytics FOR INSERT
WITH CHECK (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));

-- Admins can manage all performance data
CREATE POLICY "Admins can manage all performance"
ON public.mql_performance_analytics FOR ALL
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- ============================================
-- FUNCTIONS and TRIGGERS
-- ============================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_mql_strategies_updated_at
  BEFORE UPDATE ON public.mql_strategies
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_mql_trades_updated_at
  BEFORE UPDATE ON public.mql_trades
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_user_bot_connections_updated_at
  BEFORE UPDATE ON public.user_bot_connections
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_user_strategy_subscriptions_updated_at
  BEFORE UPDATE ON public.user_strategy_subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Function to calculate trade duration when closed
CREATE OR REPLACE FUNCTION public.calculate_trade_duration()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'closed' AND OLD.status != 'closed' AND NEW.closed_at IS NOT NULL THEN
    NEW.duration_seconds = EXTRACT(EPOCH FROM (NEW.closed_at - NEW.opened_at))::INTEGER;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER calculate_mql_trade_duration
  BEFORE UPDATE ON public.mql_trades
  FOR EACH ROW
  EXECUTE FUNCTION public.calculate_trade_duration();

-- ============================================
-- COMMENTS for Documentation
-- ============================================
COMMENT ON TABLE public.mql_strategies IS 'MQL4/MQL5 Expert Advisor strategies';
COMMENT ON TABLE public.mql_signals IS 'Trading signals generated by MQL strategies';
COMMENT ON TABLE public.mql_trades IS 'Executed trades from MQL strategies';
COMMENT ON TABLE public.user_bot_connections IS 'User connections to trading platforms (MT4/MT5/etc)';
COMMENT ON TABLE public.user_strategy_subscriptions IS 'User subscriptions to copy trading strategies';
COMMENT ON TABLE public.mql_performance_analytics IS 'Performance analytics and statistics for strategies and users';

