-- Soul Vault entries: Deep-Field Resonance Reports per user
CREATE TABLE IF NOT EXISTS public.soul_vault_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  activity TEXT,
  duration_minutes INTEGER,
  report TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_soul_vault_user_created
  ON public.soul_vault_entries(user_id, created_at DESC);

ALTER TABLE public.soul_vault_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own soul vault"
  ON public.soul_vault_entries FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own soul vault entries"
  ON public.soul_vault_entries FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Service role can manage soul vault"
  ON public.soul_vault_entries FOR ALL
  USING (auth.role() = 'service_role');

COMMENT ON TABLE public.soul_vault_entries IS 'Deep-Field Resonance Reports generated by SQI Digital Nadi 2050 scans.';

