// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjdzhrdpioxdeyyfogep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_H4AI2ZzqOL1Y7o6qRMr8ew_5-4pih8F";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
              storage: localStorage,
              persistSession: true,
              autoRefreshToken: true,
      }
});
