name: Fix Tiers
on:
  push:
    paths: ['scripts/fixtiers.js']
  workflow_dispatch:
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node scripts/fixtiers.js
        env:
          PAT: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
